pipelines/kernel/test/kconfig: allow testing for the absence of options

diff --git a/pipelines/kernel/test/kconfig.yaml b/pipelines/kernel/test/kconfig.yaml
--- a/pipelines/kernel/test/kconfig.yaml
+++ b/pipelines/kernel/test/kconfig.yaml
@@ -12,6 +12,8 @@ inputs:
   config-options:
     description: "The kconfig options to test for"
     required: true
+  absent-config-options:
+    description: "The kconfig options to test for the absence of."
 
 pipeline:
   - name: "check for required kernel config options"
@@ -28,31 +30,44 @@ pipeline:
       #   FOO
       #   BAR
       # and allow comments in multiline input.
-      kconfig_options=$(echo "${{inputs.config-options}}" | grep -Ev '^#|$^')
-      MISSING_OPTS=0
-      for kconf_opt in $kconfig_options; do
-        # Add CONFIG_ where it's not specified
-        case "$kconf_opt" in
-          "CONFIG_"*)
-            ;;
-          *)
-            kconf_opt="CONFIG_${kconf_opt}"
-            ;;
-        esac
-        # If the user specified CONFIG_*=? without an explicit option, assume y or m is ok.
-        case "$kconf_opt" in
-          "CONFIG_"*"="*)
-            ;;
-          *"=")
-            kconf_opt="${kconf_opt}[ym]"
-            ;;
-          *)
-            kconf_opt="${kconf_opt}=[ym]"
-            ;;
-        esac
+      # Add CONFIG_ where it's not specified, and if the user specified CONFIG_*=?
+      # without an explicit option, assume y or m is ok.
+      cleanup_input() {
+        input_options=$(echo "$@" | grep -Ev '^#|$^')
+        for kconf_opt in $input_options; do
+          case "$kconf_opt" in
+            "CONFIG_"*)
+              ;;
+            *)
+              kconf_opt="CONFIG_${kconf_opt}"
+              ;;
+          esac
+          case "$kconf_opt" in
+            "CONFIG_"*"="*)
+              ;;
+            *"=")
+              kconf_opt="${kconf_opt}[ym]"
+              ;;
+            *)
+              kconf_opt="${kconf_opt}=[ym]"
+              ;;
+          esac
+          printf "$kconf_opt "
+        done
+      }
+      EXIT=0
+      for kconf_opt in $(cleanup_input "${{inputs.config-options}}"); do
         if ! grep -Ex "$kconf_opt" "$kconf_path"; then
-          MISSING_OPTS=1
+          EXIT=1
           echo "Missing $kconf_opt"
         fi
       done
-      exit $MISSING_OPTS
+
+      for kconf_opt in $(cleanup_input "${{inputs.absent-config-options}}"); do
+        if grep -Ex "$kconf_opt" "$kconf_path"; then
+          EXIT=1
+          echo "Found $kconf_opt which should be missing"
+        fi
+      done
+
+      exit $EXIT
