helpers/test-wolfi-vm: implement test configuration v1 parsing for Azure

diff --git a/helpers/test-wolfi-vm-azure b/helpers/test-wolfi-vm-azure
--- a/helpers/test-wolfi-vm-azure
+++ b/helpers/test-wolfi-vm-azure
@@ -12,8 +12,6 @@ Usage: ${0##*/} [ options ] cloud out-dir -- [ azure options ]
        -s|--subscription-id SUBSCRIPTION       subscription id for running tests
        -r|--region REGION                      azure region to run tests in
        -g|--resource-group GROUP               azure resource group to run tests in
-       -u|--test-user USER                     user to run tests as on the image
-       -v|--vm-size SIZE                       VM size to use for testing
        -i|--azure-inputs DIR or FILE           directory of files with 'az sig image-defintion' and 'az sig image-version create' output
           --azure-input-filename PATTERN       look for filenames matching this pattern
 
@@ -37,8 +35,8 @@ setup_azure() {
 }
 
 test_azure() {
-    local short_opts="h,s:,r:,g:,u:,v:,i:"
-    local long_opts="help,subscription-id:,region:,resource-group:,test-user:,vm-size:,azure-inputs:,azure-input-filename:"
+    local short_opts="h,s:,r:,g:,i:"
+    local long_opts="help,subscription-id:,region:,resource-group:,azure-inputs:,azure-input-filename:"
     local getopt_out=""
     getopt_out=$(getopt --options "${short_opts}" \
         --long "${long_opts}" -- "$@") &&
@@ -46,7 +44,7 @@ test_azure() {
         { bad_azure_usage; return; }
 
     local cur="" next=""
-    local subscription="" region="" resource_group="" test_user="azureuser" vm_size="" azure_inputs="" azure_input_filename="publish.*.json"
+    local subscription="" region="" resource_group="" azure_inputs="" azure_input_filename="publish.*.json"
     while [ $# -ne 0 ]; do
         { cur="$1"; next="$2"; }
         case "$cur" in
@@ -54,8 +52,6 @@ test_azure() {
             -s|--subscription-id) subscription="$next"; shift;;
             -r|--region) region="$next"; shift;;
             -g|--resource-group) resource_group="$next"; shift;;
-            -u|--test-user) test_user="$next"; shift;;
-            -v|--vm-size) vm_size="$next"; shift;;
             -i|--azure-inputs) azure_inputs="$next"; shift;;
                --azure-input-filename) azure_input_filename="$next"; shift;;
             --) shift; break;;
@@ -66,15 +62,14 @@ test_azure() {
     [ -n "$subscription" ] || { bad_azure_usage "--subscription-id is required"; return 1; }
     [ -n "$region" ] || { bad_azure_usage "--region is required"; return 1; }
     [ -n "$resource_group" ] || { bad_azure_usage "--resource-group is required"; return 1; }
-    [ -n "$vm_size" ] || { bad_azure_usage "--vm-size is required"; return 1; }
     [ -n "$azure_inputs" ] || { bad_azure_usage "--azure-inputs is required"; return 1; }
     if [ -f "$azure_inputs" ] && [ -d "$azure_inputs" ]; then
         { bad_azure_usage "--azure-inputs '$azure_inputs' is not a file or directory"; return 1; }
     fi
 
     local resource_basename="vms-test-$RANDOM"
-    local outd="$1"
-    shift 1
+    local wolfivmd="$1" outd="$2"
+    shift 2
 
     TEMP_D=$(mktemp -d) || return
     runner="$TOP_D/runner/azure"
@@ -100,7 +95,7 @@ test_azure() {
     # Expanding now is fine, these are static
     trap "cleanup_azure '$subscription' '$resource_group' '$resource_basename'" EXIT
 
-    local publish_file="" vmname="" az_arch="" arch="" tfile="" tname="" vfails="" voutd="" fails="" image_uri=""
+    local publish_file="" vfails="" fails="" image_uri="" arch="" az_arch="" imagename="" localname="" testconfig="" vmconfigs="" user="" num_vmconfigs=""
     for publish_file in $publish_files; do
         vfails=""
         image_uri=$(jq -rse '.[1].id' < "$publish_file") || \
@@ -113,60 +108,113 @@ test_azure() {
               fails="${fails+$fails }$vfails"; continue; }
         [ "$az_arch" == "x64" ] && arch="x86_64" || arch="aarch64"
         # Should look like $image_name-$image_version
-        vmname=$(jq -rse 'map(.name) | join("-")' < "$publish_file") || \
+        imagename=$(jq -rse '"\(.[0].name)-\(.[1].name)"' < "$publish_file") || \
             { vfails="$publish_file/read-image-name"; \
               log "finished $publish_file FAIL - $vfails"; \
               fails="${fails+$fails }$vfails"; continue; }
-        voutd="$outd/$arch/$vmname"
-        log "launching $vmname, detected arch $arch"
-        rq mkdir -p "$voutd" || { stderr "failed creating $voutd"; return 1; }
-        vmtag="$resource_basename-vm-$RANDOM"
-        # Start VM
-        vr "$runner" launch --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag" \
-            --vnet "$resource_basename-vnet" --subnet "$resource_basename-subnet" --name "$vmtag" --region "$region" \
-            --image-uri="$image_uri" --public-key="$key.pub" --admin-username "$test_user" --vm-size="$vm_size"
-        local launch_code=$?
+        localname=$(jq -rse '.[0].tags."local-name"' < "$publish_file" ) || \
+            { vfails="$publish_file/read-local-name"; \
+              log "finished $publish_file FAIL - $vfails"; \
+              fails="${fails+$fails }$vfails"; continue; }
+        testconfig="$wolfivmd/configs/$localname/test.yaml"
+        [ -f "$testconfig" ] || \
+            { vfails="$arch-$imagename/missing-test-config"; \
+              log "finished $arch-$imagename FAIL - $vfails"; \
+              fails="${fails+$fails }$vfails"; continue; }
+        [ "$(yq -re 'explode(.) | .version' "$testconfig")" == "1" ] || \
+            { vfails="$arch-$imagename/version-mismatch"; \
+              log "finished $arch-$imagename FAIL - $vfails"; \
+              fails="${fails+$fails }$vfails"; continue; }
+        [ "$(yq -re 'explode(.) | .cloud' "$testconfig")" == "azure" ] || \
+            { vfails="$arch-$imagename/cloud-mismatch"; \
+              log "finished $arch-$imagename FAIL - $vfails"; \
+              fails="${fails+$fails }$vfails"; continue; }
+        # convert to json because bash mangles yaml
+        vmconfigs=$(yq -o json -re "explode(.) | .vmconfigs.$arch" "$testconfig") || \
+            { vfails="$arch-$imagename/read-vmconfigs"; \
+              log "finished $arch-$imagename FAIL - $vfails"; \
+              fails="${fails+$fails }$vfails"; continue; }
+        user=$(yq -re "explode(.) | .data.user" "$testconfig") || user="azureuser"
+        log "launching $imagename, detected arch $arch"
+        num_vmconfigs=$(echo "$vmconfigs" | jq 'length') || \
+            { vfails="$arch-$imagename/malformed-vmconfigs"; \
+              log "finished $arch-$imagename FAIL - $vfails"; \
+              fails="${fails+$fails }$vfails"; continue; }
 
-        if [ $launch_code -eq 0 ]; then
-            vr "$runner" --timeout="${WAIT_SSH_TIMEOUT}" wait-for-ssh \
-                --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag" \
-                >> "$known_hosts"
+        local i="" vmtag="" vm_size="" disk_type="" vmconfig_name="" vm_tests="" launchuser="" vm_testd="" voutd="" launcher="" launch_code="" tname="" tfile="" location=""
+        for i in $(seq 0 $((num_vmconfigs-1))); do
+            vmtag="$resource_basename-vm-$RANDOM"
+            vm_size=$(echo "$vmconfigs" | jq -re ".[$i].vm_size") || { vfails="$vfails $arch-$imagename/missing-vm-size"; continue; }
+            disk_type=$(echo "$vmconfigs" | jq -re ".[$i].disk_type") || { vfails="$vfails $arch-$imagename/missing-disk-type"; continue; }
+            vmconfig_name=$(echo "$vmconfigs" | jq -re ".[$i].name" 2>/dev/null) || vmconfig_name="$vm_size-$disk_type"
+            vm_tests=$(echo "$vmconfigs" | jq -re ".[$i].tests[].name") || { vfails="$vfails $arch-$imagename/$vmconfig_name/read-tests"; continue; }
+            vm_tests="${vm_tests/_builtin/"$BUILTIN_TESTS"}"
+            launchuser=$(echo "$vmconfigs" | jq -re ".[$i].launchuser" 2>/dev/null) || launchuser=$(yq -re "explode(.) | .data.launchuser" "$testconfig" 2>/dev/null) || launchuser="$user"
 
-            log "started testing $arch/$vmname"
-            # Run tests, collect metrics
-            for tfile in "${TOP_D}/test/$arch"/*; do
-                tname=${tfile##*/}
-                vrl "$voutd/test-$tname" "$runner" run-remote --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag" \
-                    --private-key "$key" --user "$test_user" --file="$tfile" --known-hosts="$known_hosts" -- \
-                       -test.v -metric-tags "arch:$arch,$METRIC_TAGS" ||
-                       vfails="$vfails $arch-$vmname/test-$tname"
+            vm_testd="$TEMP_D/$arch/$imagename/$vmconfig_name"
+            rq mkdir -p "$vm_testd" || { stderr "failed creating $vm_testd"; return 1; }
+            voutd="$outd/$arch/$imagename/$vmconfig_name"
+            rq mkdir -p "$voutd" || { stderr "failed creating $voutd"; return 1; }
+            launcher=$(dirname "$testconfig")"/"$(echo "$vmconfigs" | jq -re ".[$i].launch" 2>/dev/null) || launcher="$runner launch"
+            # Start VM
+            # shellcheck disable=SC2086
+            # Intentional wordsplitting.
+            vr env RUNNER="$runner" $launcher --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag" \
+                --vnet "$resource_basename-vnet" --subnet "$resource_basename-subnet" --name "$vmtag" --region "$region" \
+                --image-uri="$image_uri" --public-key="$key.pub" --admin-username "$launchuser" --vm-size="$vm_size" --disk-type="$disk_type"
+            launch_code=$?
+            if [ $launch_code -eq 0 ]; then
+                vr "$runner" --timeout="${WAIT_SSH_TIMEOUT}" wait-for-ssh \
+                    --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag" \
+                    >> "$known_hosts"
+                log "started testing $arch/$imagename/$vmconfig_name"
+                # Run tests, collect metrics
+                for tname in $vm_tests; do
+                    tfile=""
+                    if [ -f "$TOP_D/test/$arch/$tname" ]; then
+                        tfile="$TOP_D/test/$arch/$tname"
+                    else
+                        location=$(dirname "$testconfig")"/"$(echo "$vmconfigs" | jq -re ".[$i].tests[] | select(.name==\"$tname\").location") || { vfails="$vfails $arch/$imagename/$vmconfig_name/missing-test-location-$tname"; continue; }
+                        goarch=$(goarch "$arch") || { vfails="$vfails $arch/$imagename/$vmconfig_name/invalid-test-arch-$tname"; continue; }
+                        tfile="$vm_testd/$tname"
+                        rq env GOOS="linux" GOARCH="$goarch" go test -C "$location" -c -o "$tfile" -tags vmtest || { vfails="$vfails $arch/$imagename/$vmconfig_name/compile-test-$tname"; continue; }
+                    fi
+                    test_user=$(echo "$vmconfigs" | jq -re ".[$i].user") || test_user="$user"
+                    vrl "$voutd/test-$tname" "$runner" run-remote --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag" \
+                        --private-key "$key" --user "$test_user" --file="$tfile" --known-hosts="$known_hosts" -- \
+                        -test.v -metric-tags "arch:$arch,$METRIC_TAGS" ||
+                        vfails="$vfails $arch-$imagename/$vmconfig_name/test-$tname"
 
-                "$runner" ssh --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag" \
-                    --private-key "$key" --user "$test_user" --known-hosts="$known_hosts" \
-                    "cat $METD/$tname" \
-                       > "$voutd/$tname-metrics.json" ||
-                       vfails="$vfails $arch-$vmname/$tname-metrics"
-            done
+                    # Don't try to collect metrics unless the test binary actually calls metrics.Log()
+                    metric_logs=$(strings "$tfile" | grep "chainguard.dev/wolfi-vm/vm-test/pkg/metrics.Log")
+                    if [ -n "$metric_logs" ]; then
+                        "$runner" ssh --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag" \
+                            --private-key "$key" --user "$test_user" --known-hosts="$known_hosts" \
+                            "cat $METD/$tname" \
+                            > "$voutd/$tname-metrics.json" || vfails="$vfails $arch/$imagename/$vmconfig_name/$tname-metrics"
+                    fi
 
-            "$runner" console-log --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag" \
-                --timeout="${WAIT_CONSOLE_TIMEOUT}" --wait > "$voutd/console.log" ||
-                vfails="$vfails $arch-$vmname/console-log"
+                done
+                "$runner" console-log --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag" \
+                    --timeout="${WAIT_CONSOLE_TIMEOUT}" --wait > "$voutd/console.log" ||
+                    vfails="$vfails $arch-$imagename/$vmconfig_name/console-log"
 
-            log "finished testing $arch/$vmname"
-        else
-            # azure reserves resources for 180s after failed VM creation...
-            log "waiting 180s for azure to release resources from failed vm launch"
-            vfails="$vfails $arch-$vmname/launch"
-            sleep 180
-        fi
-        # Terminate VM
-        vr "$runner" terminate --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag"
+                log "finished testing $arch/$imagename/$vmconfig_name"
+            else
+                # azure reserves resources for 180s after failed VM creation...
+                log "waiting 180s for azure to release resources from failed vm launch"
+                vfails="$vfails $arch-$imagename/$vmconfig_name/launch"
+                sleep 180
+            fi
+            # Terminate VM
+            vr "$runner" terminate --resource-group "$resource_group" --subscription-id "$subscription" --tag "$vmtag"
+        done
 
         vfails=${vfails# }
         if [ -z "$vfails" ]; then
-            log "finished $arch/$vmname PASS"
+            log "finished $arch/$imagename PASS"
         else
-            log "finished $arch/$vmname FAIL - $vfails"
+            log "finished $arch/$imagename FAIL - $vfails"
         fi
         fails="${fails:+$fails }$vfails"
     done
