arangodb-3.11.yaml: fix shellcheck errors (#29225)
* arangodb-3.11.yaml: fix shellcheck errors

Signed-off-by: Azimjon Ulmasov <azimjon.ulmasov@chainguard.dev>

* arangodb-3.11: Use jq -r instead of piping to tr

This avoids hiding jq's error code.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

---------

Signed-off-by: Azimjon Ulmasov <azimjon.ulmasov@chainguard.dev>
Signed-off-by: dann frazier <dann.frazier@chainguard.dev>
Co-authored-by: dann frazier <dann.frazier@chainguard.dev>

diff --git a/arangodb-3.11.yaml b/arangodb-3.11.yaml
--- a/arangodb-3.11.yaml
+++ b/arangodb-3.11.yaml
@@ -1,7 +1,7 @@
 package:
   name: arangodb-3.11
   version: "3.11.14.1"
-  epoch: 4
+  epoch: 5
   description: "Native multi-model database with flexible data models for documents, graphs, and key-values."
   copyright:
     - license: "BUSL-1.1"
@@ -242,37 +242,41 @@ test:
         fi
 
         # Check the version.
-        version=$(jq '.version' < <(curl --silent --fail $AUTH_HEADER "$ARANGO_HOST/_api/version") | tr -d '"')
+        curl_output=$(curl --silent --fail $AUTH_HEADER "$ARANGO_HOST/_api/version") || exit $?
+        version=$(echo "$curl_output" | jq -r '.version')
         if [[ ${version//-/.} != ${{package.version}} ]]; then
           echo "Version ${version//-/.} does not match package version ${{package.version}}"
           exit 1
         fi
 
         # Create a database.
-        err=$(jq '.error' < <(curl --silent --fail -X POST $AUTH_HEADER \
+        curl_output=$(curl --silent --fail -X POST $AUTH_HEADER \
+          "$ARANGO_HOST/_api/database" \
           -H "Content-Type: application/json" \
-          -d "{\"name\": \"$DB_NAME\"}" \
-          "$ARANGO_HOST/_api/database"))
+          -d '{"name": "'$DB_NAME'"}') || exit $?
+        err=$(echo "$curl_output" | jq '.error')
         if [[ $err != "false" ]]; then
           echo "Failed creating a database"
           exit 1
         fi
 
         # Create a collection.
-        err=$(jq '.error' < <(curl --silent --fail -X POST $AUTH_HEADER \
+        curl_output=$(curl --silent --fail -X POST $AUTH_HEADER \
           -H "Content-Type: application/json" \
           -d "{\"name\": \"$COLLECTION_NAME\"}" \
-          "$ARANGO_HOST/_db/$DB_NAME/_api/collection"))
+          "$ARANGO_HOST/_db/$DB_NAME/_api/collection") || exit $?
+        err=$(echo "$curl_output" | jq '.error')
         if [[ $err != "false" ]]; then
           echo "Failed creating a collection"
           exit 1
         fi
 
         # Create a document.
-        id=$(jq '._id' < <(curl --silent --fail -X POST $AUTH_HEADER \
+        curl_output=$(curl --silent --fail -X POST $AUTH_HEADER \
           -H "Content-Type: application/json" \
           -d "{\"_key\": \"${DOC_NAME}\", \"name\": \"Test\"}" \
-          "$ARANGO_HOST/_db/$DB_NAME/_api/document/$COLLECTION_NAME"))
+          "$ARANGO_HOST/_db/$DB_NAME/_api/document/$COLLECTION_NAME") || exit $?
+        id=$(echo "$curl_output" | jq '._id')
         if [[ "${id//\"/}" != "${COLLECTION_NAME}/${DOC_NAME}" ]]; then
           echo "Failed inserting a document"
           exit 1
@@ -284,25 +288,27 @@ test:
           -d "{\"query\": \"FOR doc IN $COLLECTION_NAME FILTER doc._key == \\\"$DOC_NAME\\\" RETURN doc\"}" \
           "$ARANGO_HOST/_db/$DB_NAME/_api/cursor")
 
-        error=$(jq '.error' < <(echo $res))
+        error=$(echo "$res" | jq '.error')
         if [[ $error != "false" ]]; then
           echo "Failed querying document"
           exit 1
         fi
-        id=$(jq '.result[0]._id' < <(echo $res))
+        id=$(echo "$res" | jq '.result[0]._id')
         if [[ ${id//\"/} != "${COLLECTION_NAME}/${DOC_NAME}" ]]; then
           echo "Failed querying document"
           exit 1
         fi
 
         # Cleanup.
-        err=$(jq '.error' < <(curl --silent -X DELETE $AUTH_HEADER "$ARANGO_HOST/_db/$DB_NAME/_api/collection/$COLLECTION_NAME"))
+        curl_output=$(curl --silent -X DELETE $AUTH_HEADER "$ARANGO_HOST/_db/$DB_NAME/_api/collection/$COLLECTION_NAME") || exit $?
+        err=$(echo "$curl_output" | jq '.error')
         if [[ $err != "false" ]]; then
           echo "Failed cleaning up collection"
           exit 1
         fi
 
-        err=$(jq '.error' < <(curl --silent -X DELETE $AUTH_HEADER "$ARANGO_HOST/_api/database/$DB_NAME"))
+        curl_output=$(curl --silent -X DELETE $AUTH_HEADER "$ARANGO_HOST/_api/database/$DB_NAME") || exit $?
+        err=$(echo "$curl_output" | jq '.error')
         if [[ $err != "false" ]]; then
           echo "Failed cleaning up database"
           exit 1
