feat(beats): add https based test ; properly bump vulnerability in beats-7 (#19459)

diff --git a/beats-7.yaml b/beats-7.yaml
--- a/beats-7.yaml
+++ b/beats-7.yaml
@@ -1,7 +1,7 @@
 package:
   name: beats-7
   version: "7.17.28"
-  epoch: 6
+  epoch: 7
   description: The Beats are lightweight data shippers, written in Go, that you install on your servers to capture all sorts of operational data (think of logs, metrics, or network packet data). The Beats send the operational data to Elasticsearch, either directly or via Logstash, so it can be visualized with Kibana.
   resources:
     cpu: 16
@@ -217,7 +217,7 @@ subpackages:
         with:
           packages: ./metricbeat
           output: metricbeat
-          deps: k8s.io/klog/v2@v2.110.1 github.com/containerd/containerd@v1.6.26
+          deps: k8s.io/klog/v2@v2.110.1
       - runs: |
           mkdir -p "${{targets.subpkgdir}}"/usr/bin
           mkdir -p "${{targets.subpkgdir}}"/usr/share/metricbeat/modules.d
@@ -384,6 +384,7 @@ subpackages:
           packages:
             - nginx
             - sudo
+            - openssl
       pipeline:
         - runs: |
             cd /usr/share/heartbeat
@@ -394,12 +395,26 @@ subpackages:
           uses: test/daemon-check-output
           with:
             setup: |
+              # setup is not running with error handling
+              set -eu -o pipefail -x
+              certs_dir=/etc/nginx/certs
+              # Generate root CA (FIPS-compliant: 4096-bit RSA key)
+              mkdir -p $certs_dir
+              openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out $certs_dir/ca.key
+              openssl req -x509 -new -nodes -key $certs_dir/ca.key -sha256 -days 1024 -out $certs_dir/ca.crt -subj "/CN=localhost"
+
+              # Generate SSL certificates for server (FIPS-compliant: 4096-bit RSA key)
+              openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out $certs_dir/server.key
+              openssl req -new -key $certs_dir/server.key -out $certs_dir/server.csr -subj "/CN=localhost"
+              openssl x509 -req -in $certs_dir/server.csr -CA $certs_dir/ca.crt -CAkey $certs_dir/ca.key -CAcreateserial -out $certs_dir/server.crt -days 365
+              chown nonroot: -fR /etc/nginx/certs
+
               echo TEST >/var/lib/nginx/html/test.html
+              echo TEST >/var/lib/nginx/html/test-tls.html
               mkdir -p /var/lib/nginx/tmp /run/nginx
               chown nonroot -fR /var/lib/nginx /run/nginx
 
-              # patch nginx conf to allow writing to log file that can be grepped later
-              sed -E -i "s|access_log.*;|access_log /tmp/nginx.log;|;s|error_log.*;|error_log /tmp/nginx.err;|" /etc/nginx/nginx.conf
+              cp test-nginx.conf /etc/nginx/nginx.conf
               sudo -u nonroot nginx -c /etc/nginx/nginx.conf
 
               cp test-heartbeat.yml /usr/share/heartbeat/heartbeat.yml
@@ -412,7 +427,11 @@ subpackages:
               # kill the nginx processes
               pkill nginx
               if ! grep "/test\\.html" /tmp/nginx.log ; then
-                echo "Heartbeat request not found in nginx log"
+                echo "Heartbeat http request not found in nginx log"
+                exit 1
+              fi
+              if ! grep "/test-tls\\.html" /tmp/nginx.log ; then
+                echo "Heartbeat https request not found in nginx log"
                 exit 1
               fi
 
