claude - update to 1.0.43 and improve install script to ~/.claude (#2931)
Running 'claude' installed by this package would fail as it
wanted to update /usr/local and non-root user woudl not have
permissions to do so.

Running /migrate-installer
was an option to get that installer moved from the global install
dir to per-user.  And it would install to with
npm --prefix=$HOME/.claude/local/

So, that is what we do here.

First time running /usr/bin/claude, it will install the expected
version to ~/.claude/local/claude and then execute that.

Second time running, it will just exec ~/.claude/local/claude
straight away.

diff --git a/claude.yaml b/claude.yaml
--- a/claude.yaml
+++ b/claude.yaml
@@ -20,23 +20,44 @@ package:
 environment:
   contents:
     packages:
-      - build-base
       - busybox
       - ca-certificates-bundle
 
 pipeline:
   - runs: |
       # Install the binary, proprietary claude-code from npm
-      mkdir -p ${{targets.destdir}}/usr/bin
-      cat >${{targets.destdir}}/usr/bin/claude <<EOF
+      # into ~/.claude/local as happens if you did a `-g` install and then
+      # ran `/migrate-installer`
+      # Each user gets their own claude installation,
+      # which is how claude wants it.
+      fpath="${{targets.destdir}}/usr/bin/claude"
+      mkdir -p $(dirname "$fpath")
+
+      cat >"$fpath" <<"EOF"
       #!/bin/sh
+      # shellcheck disable=SC3043
       set -e
-      # Install claude from npm, since we're not allowed to distribute
-      npm install -g @anthropic-ai/claude-code@${{package.version}} -prefix /usr/local 2>&1 >/dev/null
-      # Launch claude, with whatever parameters we were passed
-      exec claude \$@
+      package="@anthropic-ai/claude-code@${{package.version}}"
+      prefix="$HOME/.claude/local"
+      bin="$prefix/node_modules/.bin/claude"
+
+      _install() {
+          local out="" rc=""
+          set -- npm install --prefix="$1" "$2"
+          echo "installing $package via: $*" 1>&2
+          out=$("$@" 2>&1) && return 0
+          rc=$?
+          printf "%s\n%s\n\n%s\n" "ERROR: $*" "$out" \
+              "ERROR: installation of $package with npm failed $rc. see above."
+      }
+
+      if [ ! -x "$bin" ]; then
+          _install "$prefix" "$package"
+      fi
+
+      exec "$bin" "$@"
       EOF
-      chmod 755 ${{targets.destdir}}/usr/bin/claude
+      chmod 755 "$fpath"
 
 update:
   enabled: true
