Added test for cluster-autoscaler-fips-1.32

diff --git a/cluster-autoscaler-fips-1.32.yaml b/cluster-autoscaler-fips-1.32.yaml
--- a/cluster-autoscaler-fips-1.32.yaml
+++ b/cluster-autoscaler-fips-1.32.yaml
@@ -51,6 +51,20 @@ subpackages:
       provides:
         - cluster-autoscaler-fips-compat=${{package.full-version}}
 
+test:
+  pipeline:
+    - name: Check binary help output
+      runs: |
+        # Check that the help output contains a usage message
+        # Returns exit code 2 for some reason; this appears to be expected though so we ignore it.
+        cluster-autoscaler --help > /tmp/help.txt 2>&1 || true
+        if ! grep -q "Usage of cluster-autoscaler:" /tmp/help.txt; then
+          echo "Usage not found in help output" >&2
+          exit 1
+        fi
+        echo "Cluster Autoscaler help output valid."
+    - uses: test/go-fips-check
+
 update:
   enabled: true
   github:
