crossplane-function-environment-configs-fips: refresh package.yaml to don't require an upstream artifact
Craft the package.yaml file purely from source, don't require an upstream artifact, which may or may not
be published.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/crossplane-function-environment-configs-fips.yaml b/crossplane-function-environment-configs-fips.yaml
--- a/crossplane-function-environment-configs-fips.yaml
+++ b/crossplane-function-environment-configs-fips.yaml
@@ -6,11 +6,6 @@ package:
   copyright:
     - license: Apache-2.0
 
-environment:
-  contents:
-    packages:
-      - crossplane-crank
-
 pipeline:
   - uses: git-checkout
     with:
@@ -38,17 +33,34 @@ update:
 subpackages:
   - name: crossplane-function-environment-configs-compat-fips
     pipeline:
+      - name: "create compat symlink"
       - runs: |
           mkdir -p "${{targets.subpkgdir}}"
           ln -s /usr/bin/function-environment-configs ${{targets.subpkgdir}}/function
-          crank xpkg extract xpkg.upbound.io/crossplane-contrib/function-environment-configs:v${{package.version}} -o out.gz
-          gunzip -c ./out.gz | tee ${{targets.subpkgdir}}/package.yaml
+      # NOTE: previously, to generate this package.yaml file we would download the OCI artifact from
+      # https://marketplace.upbound.io/functions/crossplane-contrib/function-environment-configs/
+      - name: "craft package.yaml"
+        runs: |
+          dest="${{targets.subpkgdir}}/package.yaml"
+          cat package/crossplane.yaml >> "$dest"
+          cat package/input/environmentconfigs.fn.crossplane.io_inputs.yaml >> "$dest"
     test:
       pipeline:
         - name: "Verify the symlink"
           runs: |
             test "$(readlink /function)" = "/usr/bin/function-environment-configs"
-            stat /package.yaml
+        - name: "verify the package.yaml file"
+          runs: |
+            file="/package.yaml"
+            # NOTE: may just need a manual update to these checks
+            if ! grep -q "apiVersion: meta.pkg.crossplane.io/v1beta1" "$file" \
+                || ! grep -q "kind: Function" "$file" \
+                || ! grep -q "apiVersion: apiextensions.k8s.io/v1" "$file" \
+                || ! grep -q "kind: CustomResourceDefinition" "$file" ; then
+              echo "FAIL: the file $file doesn't have the expected content, please review by hand." >&2
+              exit 1
+            fi
+            echo "PASS: the file $file has the expected content."
 
 test:
   environment:
