ct-manylinux-2.28: test: verify that oldglibc headers are preferred
Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

diff --git a/ct-manylinux-2.28.yaml b/ct-manylinux-2.28.yaml
--- a/ct-manylinux-2.28.yaml
+++ b/ct-manylinux-2.28.yaml
@@ -294,6 +294,36 @@ test:
     - uses: test/compiler/hardening-check
       with:
         cc: gcc
+    - name: oldglibc headers should win
+      runs: |
+        stdio="/usr/lib/oldglibc/usr/include/stdio.h"
+        tmpdir="$(mktemp -d)"
+        cd "$tmpdir"
+        trap "rm -rf $tmpdir; mv ${stdio}.bak ${stdio}" EXIT
+        cp "${stdio}" "${stdio}.bak"
+        echo "#error oldglibc headers did win (not really an error)" > "${stdio}"
+        cat > smoke.c <<EOF
+        #include <stdio.h>
+        int main() { printf("OK"); }
+        EOF
+        gcc smoke.c -o smoke 2>&1 | grep "oldglibc headers did win"
+        clang smoke.c -o smoke 2>&1 | grep "oldglibc headers did win"
+    - name: system glibc headers should be ignored
+      runs: |
+        stdio="/usr/include/stdio.h"
+        tmpdir="$(mktemp -d)"
+        cd "$tmpdir"
+        trap "rm -rf $tmpdir; mv ${stdio}.bak ${stdio}" EXIT
+        cp "${stdio}" "${stdio}.bak"
+        echo "#error this file should not be in your include path" > "${stdio}"
+        cat > smoke.c <<EOF
+        #include <stdio.h>
+        int main() { printf("OK"); }
+        EOF
+        gcc smoke.c -o smoke
+        ./smoke
+        clang smoke.c -o smoke
+        ./smoke
     - uses: git-checkout
       with:
         destination: openssl
