Updated to 7.73.1, aligned with non-fips version to fix a variety of issues

diff --git a/datadog-agent-fips-7.73.yaml b/datadog-agent-fips-7.73.yaml
--- a/datadog-agent-fips-7.73.yaml
+++ b/datadog-agent-fips-7.73.yaml
@@ -2,7 +2,7 @@ package:
   name: datadog-agent-fips-7.73
   # This package has two git checkouts. For each new release, the commit SHA for
   # DataDog/integrations-core must also be updated.
-  version: "7.73.0"
+  version: "7.73.1"
   epoch: 0 # GHSA-2xpw-w6gg-jr37, GHSA-gm62-xv2j-4w53
   description: "Collect events and metrics from your hosts that send data to Datadog."
   copyright:
@@ -108,7 +108,7 @@ pipeline:
     with:
       repository: https://github.com/DataDog/datadog-agent
       tag: ${{package.version}}
-      expected-commit: 6d381383230cdaf13b4ee05e0d1bdaf604a190ed
+      expected-commit: 1d2fbb7d72285ca46bbe74b48100d2aa48cb8789
 
   - runs: |
       sed -i'' 's/v1\.3\.7/v1.6.1/g' go.mod
@@ -117,7 +117,7 @@ pipeline:
   # https://github.com/DataDog/datadog-agent/pull/31426
   - uses: patch
     with:
-      patches: fix-7.66.0-ftbfs.patch
+      patches: fix-7.66.0-ftbfs.patch fix-sqlite-double-registration.patch
 
   # Ensure that we don't run into nvidia GPU issues at runtime.
   - runs: |
@@ -128,20 +128,20 @@ pipeline:
   # these won't leak into the package.
   - runs: |
       # install `invoke` and its dependencies
-      python${{vars.python-version}} -m pip install invoke requests toml pyyaml packaging codeowners
+      python${{vars.python-version}} -m pip install invoke requests toml pyyaml packaging codeowners --root-user-action ignore
 
       # install `gitlab`
-      python${{vars.python-version}} -m pip install python-gitlab
+      python${{vars.python-version}} -m pip install python-gitlab --root-user-action ignore
 
   - if: ${{build.arch}} == 'aarch64'
     name: Install clang-12
     runs: |
       mkdir -p /usr/src
-      wget -O arch.deb http://deb.debian.org/debian-security/pool/updates/main/l/linux/linux-headers-${LINUX_HEADERS_VERSION}-arm64_${LINUX_KERNEL_VERSION}_arm64.deb
+      wget -O arch.deb "http://deb.debian.org/debian-security/pool/updates/main/l/linux/linux-headers-${LINUX_HEADERS_VERSION}-arm64_${LINUX_KERNEL_VERSION}_arm64.deb"
       echo "1966681f404272bcee4e6270b4fc4b5e43f31378a9ef8a2918f61f7e64500bed arch.deb" | sha256sum -c
 
       dpkg -x arch.deb /tmp/arch
-      ln -s /tmp/arch/usr/src/linux-headers-${LINUX_HEADERS_VERSION}-arm64 /usr/src/linux-headers-${LINUX_HEADERS_VERSION}-arm64
+      ln -s "/tmp/arch/usr/src/linux-headers-${LINUX_HEADERS_VERSION}-arm64" "/usr/src/linux-headers-${LINUX_HEADERS_VERSION}-arm64"
 
       wget "https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang+llvm-12.0.1-aarch64-linux-gnu.tar.xz" -O /tmp/clang.tar.xz  -o /dev/null
       echo "3d4ad804b7c85007686548cbc917ab067bf17eaedeab43d9eb83d3a683d8e9d4  /tmp/clang.tar.xz" | sha256sum --check
@@ -150,11 +150,11 @@ pipeline:
     name: Install clang-12
     runs: |
       mkdir -p /usr/src
-      wget -O arch.deb http://deb.debian.org/debian-security/pool/updates/main/l/linux/linux-headers-${LINUX_HEADERS_VERSION}-amd64_${LINUX_KERNEL_VERSION}_amd64.deb
+      wget -O arch.deb "http://deb.debian.org/debian-security/pool/updates/main/l/linux/linux-headers-${LINUX_HEADERS_VERSION}-amd64_${LINUX_KERNEL_VERSION}_amd64.deb"
       echo "aa67676e2ee7a23eace9cf3c97b7f3d498794a15e1b39f0945def0e7231a14a5 arch.deb" | sha256sum -c
 
       dpkg -x arch.deb /tmp/arch
-      ln -s /tmp/arch/usr/src/linux-headers-${LINUX_HEADERS_VERSION}-amd64 /usr/src/linux-headers-${LINUX_HEADERS_VERSION}-amd64
+      ln -s "/tmp/arch/usr/src/linux-headers-${LINUX_HEADERS_VERSION}-amd64" "/usr/src/linux-headers-${LINUX_HEADERS_VERSION}-amd64"
 
       # https://github.com/DataDog/datadog-agent-buildimages/blob/main/system-probe_x64/Dockerfile#L80
       wget "https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz" -O /tmp/clang.tar.xz  -o /dev/null
@@ -168,9 +168,9 @@ pipeline:
 
   - name: Build the System Probe
     runs: |
-      wget -O common.deb http://deb.debian.org/debian-security/pool/updates/main/l/linux/linux-headers-${LINUX_HEADERS_VERSION}-common_${LINUX_KERNEL_VERSION}_all.deb
+      wget -O common.deb "http://deb.debian.org/debian-security/pool/updates/main/l/linux/linux-headers-${LINUX_HEADERS_VERSION}-common_${LINUX_KERNEL_VERSION}_all.deb"
       dpkg -x common.deb /tmp/common
-      ln -s /tmp/common/usr/src/linux-headers-${LINUX_HEADERS_VERSION}-common /usr/src/linux-headers-${LINUX_HEADERS_VERSION}-common
+      ln -s "/tmp/common/usr/src/linux-headers-${LINUX_HEADERS_VERSION}-common" "/usr/src/linux-headers-${LINUX_HEADERS_VERSION}-common"
 
       mkdir -p /opt/clang
       tar xf /tmp/clang.tar.xz --no-same-owner -C /opt/clang --strip-components=1
@@ -180,7 +180,7 @@ pipeline:
       ln -s /usr/lib/libncursesw.so.6 /usr/lib/libtinfo.so.5
 
       # There's a go version issue for some reason (possibly related to the use of gobumps), so we have to fix it. Otherwise, we get this build error:
-      # go: module . listed in go.work file requires go >= 1.23.6, but go.work lists go 1.23.1; to update it:
+      # go: module . listed in go.work file requires go >= 1.24.0, but go.work lists go 1.23.1; to update it:
       #      go work use
       go work use
 
@@ -230,7 +230,7 @@ pipeline:
 
   - name: Setup Python libraries and symlinks
     runs: |
-      # Create embedded directory
+      # Create embedded directory structure
       mkdir -p ${{targets.contextdir}}${{vars.destd}}/embedded/bin
       mkdir -p ${{targets.contextdir}}${{vars.destd}}/embedded/lib
 
@@ -273,7 +273,7 @@ pipeline:
         --no-development \
         --python-home-3=/opt/datadog-agent/embedded \
         --embedded-path /usr/lib
-        #--bundle-ebpf # Same as above for the system-probe.build Invoke task.
+        #--bundle-ebpf \ # Same as above for the system-probe.build Invoke task.
 
   - name: Build trace-loader
     runs: |
@@ -287,10 +287,10 @@ pipeline:
 
       install -Dm755 bin/agent/agent ${{targets.contextdir}}${{vars.destd}}/bin/agent
       # *-agent is just a symlink to the "agent" multicall
-      ln -s ${{vars.destd}}/bin/agent/agent ${{targets.contextdir}}${{vars.destd}}/embedded/bin/process-agent
-      ln -s ${{vars.destd}}/bin/agent/agent ${{targets.contextdir}}${{vars.destd}}/embedded/bin/security-agent
-      ln -s ${{vars.destd}}/bin/agent/agent ${{targets.contextdir}}${{vars.destd}}/embedded/bin/trace-agent
-      ln -s ${{vars.destd}}/bin/agent/agent ${{targets.contextdir}}${{vars.destd}}/embedded/bin/system-probe
+      ln -s "${{vars.destd}}/bin/agent/agent" "${{targets.contextdir}}${{vars.destd}}/embedded/bin/process-agent"
+      ln -s "${{vars.destd}}/bin/agent/agent" "${{targets.contextdir}}${{vars.destd}}/embedded/bin/security-agent"
+      ln -s "${{vars.destd}}/bin/agent/agent" "${{targets.contextdir}}${{vars.destd}}/embedded/bin/trace-agent"
+      ln -s "${{vars.destd}}/bin/agent/agent" "${{targets.contextdir}}${{vars.destd}}/embedded/bin/system-probe"
 
       mkdir -p ${{targets.contextdir}}/etc/datadog-agent/
 
@@ -350,7 +350,7 @@ subpackages:
     pipeline:
       - runs: |
           mkdir -p ${{targets.contextdir}}/usr/bin/dist/jmx
-          ln -sf ${{vars.destd}}/bin/agent/dist/jmx/jmxfetch.jar ${{targets.contextdir}}/usr/bin/dist/jmx/jmxfetch.jar
+          ln -sf "${{vars.destd}}/bin/agent/dist/jmx/jmxfetch.jar" "${{targets.contextdir}}/usr/bin/dist/jmx/jmxfetch.jar"
 
   - name: ${{package.name}}-oci-compat
     dependencies:
@@ -414,10 +414,25 @@ subpackages:
             with:
               repository: https://github.com/DataDog/integrations-core
               branch: ${{vars.datadog-major-minor-x}} # 7.x.y
-              expected-commit: 3f86977e74b254f8324d870a35c4f864e3a5d714 # needs to be updated with each new release
+              expected-commit: c2376aa55bec2cca05988e6e29101b42d833c684 # needs to be updated with each new release
+          - name: Verify expected-commit is latest
+            runs: |
+              # Check if the expected-commit matches the latest commit on the branch
+              # Extract the current commit from HEAD (which git-checkout set to expected-commit)
+              EXPECTED_COMMIT=$(git rev-parse HEAD)
+              LATEST_COMMIT=$(git ls-remote https://github.com/DataDog/integrations-core refs/heads/${{vars.datadog-major-minor-x}} | cut -f1)
+
+              if [ "$EXPECTED_COMMIT" != "$LATEST_COMMIT" ]; then
+                echo "ERROR: expected-commit ($EXPECTED_COMMIT) is not the latest commit on branch ${{vars.datadog-major-minor-x}}"
+                echo "Latest commit is: $LATEST_COMMIT"
+                echo "Please update the expected-commit in datadog-agent.yaml"
+                exit 1
+              fi
+
+              echo "Verified: expected-commit matches the latest commit on branch ${{vars.datadog-major-minor-x}}"
           - uses: patch
             with:
-              patches: /home/build/int-core-datadog_checks_dev-pyproject-toml.patch /home/build/int-core-mysql-hatch-toml.patch /home/build/int-core-singlestore-hatch-toml.patch /home/build/int-core-agent_requirements-in.patch /home/build/urlib3-GHSA-2xpw-w6gg-jr37.patch
+              patches: /home/build/int-core-datadog_checks_dev-pyproject-toml.patch /home/build/int-core-mysql-hatch-toml.patch /home/build/int-core-singlestore-hatch-toml.patch
           - runs: |
               # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
               SOURCE_DATE_EPOCH=315532800
@@ -539,13 +554,14 @@ subpackages:
     pipeline:
       - runs: |
           mkdir -p ${{targets.subpkgdir}}${{vars.destd}}/bin/
-          ln -s /usr/bin/datadog-cluster-agent ${{targets.subpkgdir}}${{vars.destd}}/bin/datadog-cluster-agent
-          ln -s /usr/bin/datadog-cluster-agent ${{targets.subpkgdir}}${{vars.destd}}/bin/agent
+          ln -s "/usr/bin/datadog-cluster-agent" "${{targets.subpkgdir}}${{vars.destd}}/bin/datadog-cluster-agent"
+          ln -s "/usr/bin/datadog-cluster-agent" "${{targets.subpkgdir}}${{vars.destd}}/bin/agent"
       - working-directory: Dockerfiles/cluster-agent
         runs: |
           install -Dm755 entrypoint.sh ${{targets.subpkgdir}}/entrypoint.sh
           install -Dm755 readsecret.sh ${{targets.subpkgdir}}/readsecret.sh
           install -Dm755 readsecret_multiple_providers.sh ${{targets.subpkgdir}}/readsecret_multiple_providers.sh
+    # test added by a robot (compat)
     test:
       pipeline:
         - runs: |
@@ -606,7 +622,7 @@ subpackages:
             ;;
           esac
 
-          wget -O s6-overlay.tgz https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-${_arch}.tar.gz
+          wget -O s6-overlay.tgz "https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-${_arch}.tar.gz"
 
           echo "${expected_sha256}  s6-overlay.tgz" | sha256sum -c
 
