Add test pipelines for script files
List the scripts in subpackages and check the executable files

diff --git a/gitlab-cng-ee-17.8.yaml b/gitlab-cng-ee-17.8.yaml
--- a/gitlab-cng-ee-17.8.yaml
+++ b/gitlab-cng-ee-17.8.yaml
@@ -49,6 +49,17 @@ subpackages:
             mkdir -p ${{targets.subpkgdir}}/$(dirname $x)
             cp -r $x ${{targets.subpkgdir}}/$x
           done
+    test:
+      pipeline:
+        - name: List all files in the package's scripts directory
+          runs: |
+            # List all files in the package's scripts directory
+            find /scripts -type f | while read -r file; do
+              if [ ! -f "$file" ]; then
+                echo "Missing file: $file"
+                exit 1
+              fi
+            done
 
   - name: gitlab-toolbox-ee-scripts-${{vars.major-minor-version}}
     dependencies:
@@ -60,6 +71,19 @@ subpackages:
           mkdir -p ${{targets.subpkgdir}}/usr/lib/ruby/vendor_ruby
           cp -r ./gitlab-toolbox/scripts/bin/* ${{targets.subpkgdir}}/usr/local/bin
           cp -r ./gitlab-toolbox/scripts/lib/* ${{targets.subpkgdir}}/usr/lib/ruby/vendor_ruby
+    test:
+      pipeline:
+        - runs: |
+            test -x /usr/local/bin/backup-utility
+            test -x /usr/local/bin/entrypoint.sh
+            test -x /usr/local/bin/entrypoint-ubi.sh
+            test -x /usr/local/bin/gitlab-backup-cli
+            test -x /usr/local/bin/gitlab-rails
+            test -x /usr/local/bin/gitlab-rake
+            test -x /usr/local/bin/object-storage-azure-token
+            test -x /usr/local/bin/object-storage-azure-url
+            test -x /usr/local/bin/object-storage-backup
+            test -x /usr/local/bin/object-storage-restore
 
   - name: gitlab-toolbox-ee-${{vars.major-minor-version}}
     dependencies:
