Package update, remove manual: true, Validate vars correctness in GitLab CNG package fips 17.3 (#14601)
with this check we wi;ll not need to check manually every update and most of package update will be done by the automation

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

diff --git a/gitlab-cng-fips-17.4.yaml b/gitlab-cng-fips-17.4.yaml
--- a/gitlab-cng-fips-17.4.yaml
+++ b/gitlab-cng-fips-17.4.yaml
@@ -6,8 +6,8 @@
 # Additionally, the latest 'gitaly-backup-fips' package (part of gitlab-cng), must be built first.
 vars:
   # Container registry tags: https://gitlab.com/gitlab-org/container-registry/-/tags
-  registry-commit: 40a0e35e6756881c8387be33b6ad2f5d9e3f013e
-  registry-tag: 4.7.0
+  registry-commit: 8834b7574d418da55f227df987abe01c6c721057
+  registry-tag: 4.9.0
   # ElasticSearch indexer tags: https://gitlab.com/gitlab-org/gitlab-elasticsearch-indexer/-/tags
   indexer-commit: 14b00006696474cc3a0e42c43f1cf8b1bd63914c
   indexer-tag: 5.2.0
@@ -20,8 +20,8 @@ vars:
 
 package:
   name: gitlab-cng-fips-17.4
-  version: 17.4.5
-  epoch: 4
+  version: 17.4.6
+  epoch: 0
   description: Cloud Native container images per component of GitLab
   copyright:
     - license: MIT
@@ -51,7 +51,28 @@ pipeline:
     with:
       repository: https://gitlab.com/gitlab-org/build/CNG.git
       tag: v${{package.version}}
-      expected-commit: 89e2674ac5c17f9344597fbda7a37e46b96faa7b
+      expected-commit: 9d2884c9e1248d47f75894adf3d24eed52890926
+
+  - name: Verify all the vars tags are uptodate with the upstream
+    runs: |
+      REGISTRY_TAG=$(sed -n 's/.*GITLAB_CONTAINER_REGISTRY_VERSION: *v\([^"]*\).*/\1/p' ./ci_files/variables.yml | sed 's/-gitlab//')
+      INDEXER_TAG=$(sed -n 's/.*GITLAB_ELASTICSEARCH_INDEXER_VERSION: *v\([^"]*\).*/\1/p' ./ci_files/variables.yml)
+      LOGGER_TAG=$(sed -n 's/.*GITLAB_LOGGER_VERSION: *v\([^"]*\).*/\1/p' ./ci_files/variables.yml)
+      SHELL_TAG=$(sed -n 's/.*GITLAB_SHELL_VERSION: *v\([^"]*\).*/\1/p' ./ci_files/variables.yml)
+      check_version() {
+        local vars_name=$1
+        local expected_value=$2
+        local actual_value=$3
+        if [ "$expected_value" != "$actual_value" ]; then
+          echo "Error: Expected $vars_name: $expected_value but got: $actual_value"
+          exit 1
+        fi
+      }
+      # Run checks
+      check_version "registry-tag" "${{vars.registry-tag}}" "$REGISTRY_TAG"
+      check_version "indexer-tag" "${{vars.indexer-tag}}" "$INDEXER_TAG"
+      check_version "logger-tag" "${{vars.logger-tag}}" "$LOGGER_TAG"
+      check_version "shell-tag" "${{vars.shell-tag}}" "$SHELL_TAG"
 
 subpackages:
   - name: gitlab-base-fips-${{vars.major-minor-version}}
@@ -290,8 +311,6 @@ subpackages:
 
 update:
   enabled: true
-  # Requires manual steps when updating
-  manual: true
   git:
     strip-prefix: v
     tag-filter-prefix: v17.4
