Change default value for go telemetry from 'local' to 'off'
See attached patches for further explaination.

Go 1.23 introduced a telemetry feature that collects local audit data
about the Go toolchain, storing it by default in
$HOME/.config/go/telemetry. While this data is not sent externally by
default, the local storage path can trigger security alerts in tools
like Falco, as it writes to a sensitive location under /root.

The behavior can be disabled with 'go telemetry off', which writes
to the config file above, but that means the user needs to do so
before calling 'go' in any other manner.  Doing so for a container
is non-obvious.  We could build /root/.config/go/telemetry into
a 'go' image, but that would still provide a problem for any user
other than uid 0.

There is no mechanism to change the behavior "system wide" or an
environment variable that can set the value.

See https://github.com/golang/go/issues/68960 and
https://github.com/golang/go/issues/69113. The second one requests that
env GOTELEMETRY=off would disable telemetry. That would be easy for us
to utilize but it was rejected upstream.

Instead, we just change the default value returned if there is no
.config/go/telemetry file present.

Fixes: https://github.com/chainguard-dev/customer-issues/issues/1842

diff --git a/go-fips-1.23.yaml b/go-fips-1.23.yaml
--- a/go-fips-1.23.yaml
+++ b/go-fips-1.23.yaml
@@ -2,7 +2,7 @@
 package:
   name: go-fips-1.23
   version: 1.23.3
-  epoch: 0
+  epoch: 1
   description: "the Go programming language"
   copyright:
     - license: BSD-3-Clause
@@ -118,7 +118,9 @@ pipeline:
           patches: /home/build/extra/0002-boring-always-enable-access-to-boring.Enabled-functi.patch
       - uses: patch
         with:
-          patches: /home/build/extra/cmd-go-always-emit-ldflags-version-information.patch
+          patches: |
+            ../extra/cmd-go-always-emit-ldflags-version-information.patch
+            ../extra/change-default-telemetry-from-local-to-off.patch
 
   - runs: |
       cd go/src
@@ -307,3 +309,41 @@ test:
             cat decrypt.out
             fail "test-parallel-decrypt.go exited $rc"
         }
+    - name: Test telemetry settings - should be off by default.
+      runs: |
+        fail() { echo "FAIL:" "$@" 1>&2; exit 1; }
+
+        tmpd=$(mktemp -d)
+        trap "rm -R '$tmpd'" EXIT
+        export HOME="$tmpd/home"
+        mkdir "$HOME"
+
+        out=$(go telemetry) || fail "'go telemetry' exited $?"
+        [ "$out" = "off" ] ||
+          fail "go telemetry output '$out'. expected 'off'"
+
+        cfgdir="$HOME/.config/go/telemetry"
+        if [ -d "$cfgdir" ]; then
+          fail "$cfgdir was created by running 'go telemetry'"
+        fi
+
+        go telemetry on ||
+          fail "'go telemetry on' exited $?"
+        out=$(go telemetry) || fail "'go telemetry' after 'on' exited $?"
+        [ "$out" = "on" ] ||
+          fail "go telemetry after 'on' output '$out'. expected 'on'"
+
+        [ -f "$cfgdir/mode" ] ||
+          fail "ERROR: 'go telemetry on' did not write ~/${cfgdir#$HOME/}"
+
+        go telemetry local ||
+          fail "'go telemetry local' exited $?"
+        out=$(go telemetry) || fail "'go telemetry' after 'local' exited $?"
+        [ "$out" = "local" ] ||
+          fail "go telemetry after 'local' output '$out'. expected 'local'"
+
+        go telemetry off ||
+          fail "explicit 'go telemetry off' exited $?"
+        out=$(go telemetry) || fail "'go telemetry' after explicit off exited $?"
+        [ "$out" = "off" ] ||
+          fail "go telemetry after explicit off output '$out'. expected 'off'"
diff --git a/go-msft-1.23.yaml b/go-msft-1.23.yaml
--- a/go-msft-1.23.yaml
+++ b/go-msft-1.23.yaml
@@ -1,7 +1,7 @@
 package:
   name: go-msft-1.23
   version: 1.23.3.1
-  epoch: 0
+  epoch: 1
   description: "golang toolchain with patches/enhancements from Microsoft"
   copyright:
     - license: BSD-3-Clause
@@ -283,3 +283,41 @@ test:
             cat decrypt.out
             fail "test-parallel-decrypt.go exited $rc"
         }
+    - name: Test telemetry settings - should be off by default.
+      runs: |
+        fail() { echo "FAIL:" "$@" 1>&2; exit 1; }
+
+        tmpd=$(mktemp -d)
+        trap "rm -R '$tmpd'" EXIT
+        export HOME="$tmpd/home"
+        mkdir "$HOME"
+
+        out=$(go telemetry) || fail "'go telemetry' exited $?"
+        [ "$out" = "off" ] ||
+          fail "go telemetry output '$out'. expected 'off'"
+
+        cfgdir="$HOME/.config/go/telemetry"
+        if [ -d "$cfgdir" ]; then
+          fail "$cfgdir was created by running 'go telemetry'"
+        fi
+
+        go telemetry on ||
+          fail "'go telemetry on' exited $?"
+        out=$(go telemetry) || fail "'go telemetry' after 'on' exited $?"
+        [ "$out" = "on" ] ||
+          fail "go telemetry after 'on' output '$out'. expected 'on'"
+
+        [ -f "$cfgdir/mode" ] ||
+          fail "ERROR: 'go telemetry on' did not write ~/${cfgdir#$HOME/}"
+
+        go telemetry local ||
+          fail "'go telemetry local' exited $?"
+        out=$(go telemetry) || fail "'go telemetry' after 'local' exited $?"
+        [ "$out" = "local" ] ||
+          fail "go telemetry after 'local' output '$out'. expected 'local'"
+
+        go telemetry off ||
+          fail "explicit 'go telemetry off' exited $?"
+        out=$(go telemetry) || fail "'go telemetry' after explicit off exited $?"
+        [ "$out" = "off" ] ||
+          fail "go telemetry after explicit off output '$out'. expected 'off'"
