go-fips-1.25: Adjust OpenSSL symbol to match for FIPS check
Signed-off-by: Sergio Durigan Junior <sergiodj@chainguard.dev>

diff --git a/go-fips-1.25.yaml b/go-fips-1.25.yaml
--- a/go-fips-1.25.yaml
+++ b/go-fips-1.25.yaml
@@ -16,9 +16,7 @@ package:
       - openssl-config-fipshardened
 
 vars:
-  # https://github.com/chainguard-images/images-private/pull/2752/files
-  # uses a different symbol ('_Cfunc__goboringcrypto_')
-  uses-boring-crypto-symbol: "v2._Cfunc_go_openssl"
+  uses-openssl-crypto-symbol: "mkcgo_EVP_default_properties_is_fips_enabled"
 
 # Transform melange version to replace last dot "." with "-".
 var-transforms:
@@ -181,8 +179,8 @@ test:
         export GOCOVERDIR=coveragedata
 
         go tool nm ./sha256 > nm.out
-        if ! grep -q "${{vars.uses-boring-crypto-symbol}}" nm.out; then
-            echo "built sha256 was missing ${{vars.uses-boring-crypto-symbol}} symbol"
+        if ! grep -q "${{vars.uses-openssl-crypto-symbol}}" nm.out; then
+            echo "built sha256 was missing ${{vars.uses-openssl-crypto-symbol}} symbol"
             cat nm.out
             exit 1
         fi
@@ -230,8 +228,8 @@ test:
         go build -tags requirefips -o md5 md5.go
 
         go tool nm ./md5 > nm.out
-        if ! grep -q "${{vars.uses-boring-crypto-symbol}}" nm.out; then
-            echo "built md5 was missing ${{vars.uses-boring-crypto-symbol}} symbol"
+        if ! grep -q "${{vars.uses-openssl-crypto-symbol}}" nm.out; then
+            echo "built md5 was missing ${{vars.uses-openssl-crypto-symbol}} symbol"
             cat nm.out
             exit 1
         fi
@@ -292,8 +290,8 @@ test:
         go build -tags requirefips -o natstest natstest.go
 
         go tool nm ./natstest > nm.out
-        if ! grep -q "${{vars.uses-boring-crypto-symbol}}" nm.out; then
-            echo "built natstest was missing ${{vars.uses-boring-crypto-symbol}} symbol"
+        if ! grep -q "${{vars.uses-openssl-crypto-symbol}}" nm.out; then
+            echo "built natstest was missing ${{vars.uses-openssl-crypto-symbol}} symbol"
             cat nm.out
             exit 1
         fi
