go-fips-1.22: Verify that go-fips-1.22 sha256 test fails as expected.

diff --git a/go-fips-1.22.yaml b/go-fips-1.22.yaml
--- a/go-fips-1.22.yaml
+++ b/go-fips-1.22.yaml
@@ -169,6 +169,7 @@ test:
         go run /tmp/main.go
     - name: "sha256 test"
       runs: |
+        fail() { echo "$@" 1>&2; exit 1; }
         export HOME=$PWD
         export GOPATH=$PWD
 
@@ -200,10 +201,13 @@ test:
             exit 1
         fi
 
-        # you can't actually run this here because you'd need the fips provider.
-        #expected=e6f9203564e78f0a61c829906c1a8fe1303767d06f2b96d6185f10950baa44ae
-        #found=$(./sha256 "Go Cubs Go")
-        #[ "$found" = "$expected" ]
+        ./sha256 "Go Cubs Go" > sha256.out 2>&1 && rc=0 || rc=$?
+        [ $rc -eq 0 ] && fail "ERROR: sha256 ran successfully without fips provider"
+        [ $rc -eq 2 ] || { cat sha256.out; fail "ERROR: expected rc=2 found rc=$rc:"; }
+        grep -q "panic.*opensslcrypto" sha256.out || {
+          cat sha256.out
+          fail "sha256 output did not contain panic.*opensslcrypto"
+        }
     - name: "md5 test"
       runs: |
         export HOME=$PWD
