go-fips-1.24: add test for NATS ED25519 usage.
Signed-off-by: James Page <james.page@chainguard.dev>

diff --git a/go-fips-1.24.yaml b/go-fips-1.24.yaml
--- a/go-fips-1.24.yaml
+++ b/go-fips-1.24.yaml
@@ -226,6 +226,68 @@ test:
         fi
 
         ./md5 "Go Cubs Go"
+    - name: "NATS ED25519 test"
+      runs: |
+        fail() { echo "$@" 1>&2; exit 1; }
+
+        cat <<EOF > go.mod
+        module natstest
+
+        go 1.24
+
+        require (
+          github.com/nats-io/nkeys v0.4.7
+        )
+        EOF
+
+        cat <<EOF > natstest.go
+        package main
+
+        import (
+          "fmt"
+          "log"
+
+          "github.com/nats-io/nkeys"
+        )
+
+        func main() {
+          kp, err := nkeys.CreateUser()
+          if err != nil {
+            log.Fatalf("failed to create NKey: %v", err)
+          }
+
+          pub, err := kp.PublicKey()
+          if err != nil {
+            log.Fatalf("failed to get public key: %v", err)
+          }
+          fmt.Println("Public Key:", pub)
+
+          message := []byte("hello, world")
+          sig, err := kp.Sign(message)
+          if err != nil {
+            log.Fatalf("failed to sign message: %v", err)
+          }
+          fmt.Println("Signature created successfully!")
+
+          err = kp.Verify(message, sig)
+          if err != nil {
+            log.Fatalf("signature verification failed: %v", err)
+          }
+          fmt.Println("Signature verified successfully!")
+        }
+        EOF
+
+        go mod tidy
+        go build -tags requirefips -o natstest natstest.go
+
+        go tool nm ./natstest > nm.out
+        if ! grep -q "${{vars.uses-boring-crypto-symbol}}" nm.out; then
+            echo "built natstest was missing ${{vars.uses-boring-crypto-symbol}} symbol"
+            cat nm.out
+            exit 1
+        fi
+
+        ./natstest
     - name: "parallel decrypt test"
       runs: |
         fail() { echo "$@" 1>&2; exit 1; }
