go-msft: Enable coverage under fips mode; whilst blocking md5 usage under FIPS (#8171)
Patch exception reason:
- Improves FIPS support, by blocking unapproved MD5 (RC4 DES 3DES) algorithm
- Does not regress upstream standard features support (coverage)

Not sure what is better - patching in a copy of src/crypto/md5, or do `cp -r src/crypto/md5 src/internal/coverage/md5` and then only have the patch that changes imports.

The customer issue is that "but it is being blocked by go-msft image provided by MS on Mariner / Azure Linux container images" and they observed that it wasn't on Chainguard.

This is due to the checks in this go-msft toolchain in combination with openssl fips 1.1.1 shipped in Mariner image. Our openssl FIPS doesn't have these obsolete algorithms and reports them as not-available. openssl fips 1.1.1 reports them as available, but then causes them to fail at runtime. Hence this patch to remove this discrepancy.

Refactoring this and submitting it upstream with extra support for all other backends too, which we do not use in wofli:
- https://github.com/microsoft/go/pull/1346
- https://github.com/microsoft/go/pull/1348

Thus once those make it into microsoft/go release, we will be able to drop these extra patches.

diff --git a/go-msft-1.23.yaml b/go-msft-1.23.yaml
--- a/go-msft-1.23.yaml
+++ b/go-msft-1.23.yaml
@@ -1,7 +1,7 @@
 package:
   name: go-msft-1.23
   version: 1.23.2.1
-  epoch: 0
+  epoch: 1
   description: "golang toolchain with patches/enhancements from Microsoft"
   copyright:
     - license: BSD-3-Clause
@@ -137,8 +137,6 @@ test:
         export HOME=$PWD
         export GOPATH=$PWD
 
-        mkdir sha256
-        cd sha256
         cat >sha256.go <<"EOF"
         package main
 
@@ -153,10 +151,9 @@ test:
         }
         EOF
 
-        go mod init example.com/go/sha256
-        go mod tidy
-
-        go build -tags requirefips .
+        go build -cover -tags requirefips -o sha256 sha256.go
+        mkdir coveragedata
+        export GOCOVERDIR=coveragedata
 
         go tool nm ./sha256 > nm.out
         if ! grep -q "${{vars.uses-boring-crypto-symbol}}" nm.out; then
@@ -173,6 +170,48 @@ test:
         grep -q "panic.*opensslcrypto" sha256.out || {
           cat sha256.out
           fail "sha256 output did not contain panic.*opensslcrypto"
+        }
+        ./sha256 "Go Cubs Go" >/dev/null
+        go tool covdata percent -i=coveragedata > cov.out 2>&1
+        grep -q "coverage: 100.0% of statements" cov.out || {
+          cat cov.out
+          fail "coverage output did not cover 100.0% of statements"
+        }
+    - name: "md5 blocked test"
+      runs: |
+        fail() { echo "$@" 1>&2; exit 1; }
+        export HOME=$PWD
+        export GOPATH=$PWD
+
+        cat >md5.go <<"EOF"
+        package main
+
+        import (
+            "crypto/md5"
+            "fmt"
+            "os"
+        )
+
+        func main() {
+            fmt.Printf("%x\n", md5.Sum([]byte(os.Args[1])))
+        }
+        EOF
+
+        go build -tags requirefips -o md5 md5.go
+
+        go tool nm ./md5 > nm.out
+        if ! grep -q "${{vars.uses-boring-crypto-symbol}}" nm.out; then
+            echo "built md5 was missing ${{vars.uses-boring-crypto-symbol}} symbol"
+            cat nm.out
+            exit 1
+        fi
+
+        ./md5 "Go Cubs Go" >md5.out 2>&1 && rc=0 || rc=$?
+        [ $rc -eq 0 ] && fail "ERROR: md5 ran successfully when should have been blocked"
+        [ $rc -eq 2 ] || { cat md5.out; fail "ERROR: expected rc=2 found rc=$rc:"; }
+        grep -q "panic: openssl: MD5 failed" md5.out || {
+          cat md5.out
+          fail "md5 output did not contain panic: openssl: MD5 failed"
         }
     - name: "parallel decrypt test"
       runs: |
