hadoop-fips-3.3.6: add some basic smoke test
Add some basic smoke test.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/hadoop-fips-3.3.6.yaml b/hadoop-fips-3.3.6.yaml
--- a/hadoop-fips-3.3.6.yaml
+++ b/hadoop-fips-3.3.6.yaml
@@ -86,3 +86,13 @@ pipeline:
 update:
   enabled: false
   manual: true
+
+test:
+  pipeline:
+    - name: "verify the package has .jar files in a well known location"
+      runs: |
+        path="/usr/share/m2/repository/org/apache/hadoop/"
+        if ! find "${path}" -name "*.jar" | grep -q . ; then
+            echo "FAIL: no .jar files found in path '${path}'" >&2
+            exit 1
+        fi
