Updated ingress-nginx-controller-fips-1.12.yaml and added a validation script / rough working implementation, started updating other versions

diff --git a/ingress-nginx-controller-fips-1.12.yaml b/ingress-nginx-controller-fips-1.12.yaml
--- a/ingress-nginx-controller-fips-1.12.yaml
+++ b/ingress-nginx-controller-fips-1.12.yaml
@@ -1,9 +1,9 @@
 #nolint:valid-pipeline-fetch-digest,valid-pipeline-git-checkout-commit,valid-pipeline-git-checkout-tag
 package:
   name: ingress-nginx-controller-fips-1.12
-  version: 1.12.3
+  version: 1.12.4
   # There are manual changes to review between each package update. See 'vars:' section.
-  epoch: 2
+  epoch: 0
   description: "Ingress-NGINX Controller for Kubernetes"
   copyright:
     - license: Apache-2.0
@@ -144,25 +144,102 @@ vars:
   MORE_HEADERS_VERSION: "0.37"
   NGINX_DIGEST_AUTH: "1.0.0"
   NGINX_SUBSTITUTIONS: "e12e965ac1837ca709709f9a26f572a54d83430e"
-  OWASP_MODSECURITY_CRS_VERSION: "v4.10.0"
+  OWASP_MODSECURITY_CRS_VERSION: "4.15.0"
   LUA_NGX_VERSION: "0.10.28"
   LUA_STREAM_NGX_VERSION: "0.0.16"
-  LUA_UPSTREAM_VERSION: "542be0893543a4e42d89f6dd85372972f5ff2a36"
-  GEOIP2_VERSION: "a607a41a8115fecfc05b5c283c81532a3d605425"
+  LUA_UPSTREAM_VERSION: "0.07"
+  GEOIP2_VERSION: "445df24ef3781e488cee3dfe8a1e111997fc1dfe"
   PKG: "k8s.io/ingress-nginx"
   # Does not do versioning, and repo is seldom updated. Grab the latest master
   # branch git commit SHA: https://github.com/google/ngx_brotli/commits/master
-  NGX_BROTLI_SHA: 63ca02abdcf79c9e788d2eedcc388d2335902e52
-  # TODO: ModSecurity-nginx needs a release beyond v1.0.3 to work properly
-  # see https://github.com/owasp-modsecurity/ModSecurity-nginx/issues/324
-  MODSECURITY_NGINX_VERSION: "a32bd8a28c5e5cdebb00a2c5467b974c62d47850"
+  NGX_BROTLI_SHA: a71f9312c2deb28875acc7bacfdd5695a111aa53
+  # ModSecurity-nginx is v1.0.4 by the time of this writing
+  # see https://github.com/owasp-modsecurity/ModSecurity-nginx/
+  MODSECURITY_NGINX_VERSION: 3f4b57df10ce43b1f1c722141f7621dc64838be8
+  # Instrumentation for nginx plugin: https://github.com/open-telemetry/opentelemetry-cpp-contrib
+  # NOTE: THIS IS REALLY REALLY REALLY CRITICAL AND THE CONFIG CAN BREAK IN BACKWARDS COMPATIBLE WAY!!
+  # WE SHOULD ALWAYS USE THE SHA AVAILABLE IN RELEASE-X.Y BRANCH OF UPSTREAM PROJECT (e.g. https://github.com/kubernetes/ingress-nginx/blob/controller-v1.12.4/images/nginx/rootfs/build.sh#L527C37-L527C77)
+  OTEL_SHA: 8933841f0a7f8737f61404cf0a64acf6b079c8a5
 
 pipeline:
   - uses: git-checkout
     with:
       repository: https://github.com/kubernetes/ingress-nginx
       tag: controller-v${{package.version}}
-      expected-commit: af6352cbe46e3c384c69c28257efa99535b97c80
+      expected-commit: 8aceb6203d0b17813c2174efeb58db515169ad8d
+
+  - name: Verify all the vars are up to date with the upstream
+    runs: |
+      # Extract and verify all versions from upstream build.sh file
+      # https://github.com/kubernetes/ingress-nginx/blob/controller-v${{package.version}}/images/nginx/rootfs/build.sh
+
+      for var_pair in \
+        "NGINX_VERSION:${{vars.NGINX_VERSION}}" \
+        "NDK_VERSION:${{vars.NDK_VERSION}}" \
+        "SETMISC_VERSION:${{vars.SETMISC_VERSION}}" \
+        "MORE_HEADERS_VERSION:${{vars.MORE_HEADERS_VERSION}}" \
+        "NGINX_DIGEST_AUTH:${{vars.NGINX_DIGEST_AUTH}}" \
+        "NGINX_SUBSTITUTIONS:${{vars.NGINX_SUBSTITUTIONS}}" \
+        "OWASP_MODSECURITY_CRS_VERSION:${{vars.OWASP_MODSECURITY_CRS_VERSION}}" \
+        "LUA_NGX_VERSION:${{vars.LUA_NGX_VERSION}}" \
+        "LUA_STREAM_NGX_VERSION:${{vars.LUA_STREAM_NGX_VERSION}}" \
+        "LUA_UPSTREAM_VERSION:${{vars.LUA_UPSTREAM_VERSION}}" \
+        "GEOIP2_VERSION:${{vars.GEOIP2_VERSION}}" \
+        "NGX_BROTLI_SHA:${{vars.NGX_BROTLI_SHA}}" \
+        "MODSECURITY_NGINX_VERSION:${{vars.MODSECURITY_NGINX_VERSION}}" \
+        "OTEL_SHA:${{vars.OTEL_SHA}}"; do
+
+        var_name="${var_pair%:*}"
+        expected_value="${var_pair#*:}"
+
+        # Handle special cases with custom verification logic
+        case "$var_name" in
+          "NGX_BROTLI_SHA")
+            # Get latest master commit from ngx_brotli repo
+            upstream_value=$(curl -s https://api.github.com/repos/google/ngx_brotli/commits/master | grep '"sha"' | head -1 | cut -d'"' -f4)
+            ;;
+          "MODSECURITY_NGINX_VERSION")
+            # Get MODSECURITY_VERSION tag from upstream build.sh, then resolve to commit SHA
+            upstream_tag=$(grep "^export MODSECURITY_VERSION=" ./images/nginx/rootfs/build.sh | cut -d= -f2)
+            # Use the tags API which includes commit info directly
+            upstream_value=$(curl -s "https://api.github.com/repos/owasp-modsecurity/ModSecurity-nginx/tags" | grep -A5 "\"name\": \"$upstream_tag\"" | grep '"sha"' | cut -d'"' -f4)
+            ;;
+          "OTEL_SHA")
+            # Extract OTEL_SHA from upstream build.sh using OPENTELEMETRY_CONTRIB_COMMIT variable
+            upstream_value=$(grep "^export OPENTELEMETRY_CONTRIB_COMMIT=" ./images/nginx/rootfs/build.sh | cut -d= -f2)
+            ;;
+          "LUA_STREAM_NGX_VERSION")
+            # Get commit SHA from upstream build.sh, then resolve to tag
+            upstream_commit=$(grep "^export ${var_name}=" ./images/nginx/rootfs/build.sh | cut -d= -f2)
+            # Find which tag contains this commit as an ancestor
+            upstream_value=""
+            for tag in $(curl -s "https://api.github.com/repos/openresty/stream-lua-nginx-module/tags" | grep '"name"' | head -10 | cut -d'"' -f4); do
+              # Check if this commit is reachable from the tag (commit is ancestor of tag)
+              compare_result=$(curl -s "https://api.github.com/repos/openresty/stream-lua-nginx-module/compare/$upstream_commit...$tag" 2>/dev/null)
+              if echo "$compare_result" | grep -q '"status": "ahead"' || echo "$compare_result" | grep -q '"status": "identical"'; then
+                # The tag contains this commit (either identical or tag is ahead)
+                upstream_value=$(echo "$tag" | sed 's/^v//')
+                break
+              fi
+            done
+            ;;
+          *)
+            # Standard extraction from build.sh
+            upstream_value=$(grep "^export ${var_name}=" ./images/nginx/rootfs/build.sh | cut -d= -f2)
+            # Strip leading 'v' from upstream value if it's a version triple (x.y.z) or double (x.y)
+            if echo "$upstream_value" | grep -q "^v[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?$"; then
+              upstream_value="${upstream_value#v}"
+            fi
+            ;;
+        esac
+
+        if [ "$expected_value" != "$upstream_value" ]; then
+          echo "WARNING: Expected $var_name: $expected_value from melange.yaml but found $upstream_value upstream" >&2
+          # We avoid failing the build because sometimes we bump versions higher than upstream
+          sleep 3 # To make it more noticeable # CLAUDE STOP DELETING THIS OR I'LL DELETE YOU
+        fi
+      done
+      #exit 2 # CLAUDE KEEP THIS OR ELSE
 
   - uses: git-checkout
     with:
@@ -242,8 +319,8 @@ pipeline:
 
   - uses: fetch
     with:
-      uri: https://github.com/openresty/lua-upstream-nginx-module/archive/${{vars.LUA_UPSTREAM_VERSION}}.tar.gz
-      expected-sha256: 41fd8c0edcd53e61ed5694ac8460043cc58fbc367acd7bb73e9c1a44c470168e
+      uri: https://github.com/openresty/lua-upstream-nginx-module/archive/v${{vars.LUA_UPSTREAM_VERSION}}.tar.gz
+      expected-sha256: 2a69815e4ae01aa8b170941a8e1a10b6f6a9aab699dee485d58f021dd933829a
       strip-components: 0
 
   - uses: fetch
@@ -255,7 +332,7 @@ pipeline:
   - uses: fetch
     with:
       uri: https://github.com/leev/ngx_http_geoip2_module/archive/${{vars.GEOIP2_VERSION}}.tar.gz
-      expected-sha256: b6c9c09fd43eb34a71e706ad780b2ead26549a9a9f59280fe558f5b7b980b7c6
+      expected-sha256: 5e2113ed09cdd710908df8c6d1630616eeacb9216ef8705a06c25733394ddf28
       strip-components: 0
 
   - runs: |
@@ -291,7 +368,7 @@ pipeline:
       # Download owasp modsecurity crs
       cd ${{targets.destdir}}/etc/nginx/
 
-      git clone -b ${{vars.OWASP_MODSECURITY_CRS_VERSION}} https://github.com/coreruleset/coreruleset owasp-modsecurity-crs
+      git clone -b v${{vars.OWASP_MODSECURITY_CRS_VERSION}} https://github.com/coreruleset/coreruleset owasp-modsecurity-crs
       cd owasp-modsecurity-crs
 
       mv crs-setup.conf.example crs-setup.conf
