liberica-24: set correct googletest version, add validation
This ensures we detect the need to update the googletest fetching code
when upstream make changes.

diff --git a/liberica-24.yaml b/liberica-24.yaml
--- a/liberica-24.yaml
+++ b/liberica-24.yaml
@@ -25,6 +25,7 @@ package:
 vars:
   java-home: /usr/lib/jvm/java-23-liberica
   boot-jdk: /usr/lib/jvm/java-23-openjdk
+  googletest-version: v1.14.0
 
 var-transforms:
   # The first release of a version stream lacks minor/patch segments (e.g.
@@ -81,12 +82,20 @@ pipeline:
       uri: https://github.com/bell-sw/Liberica/releases/download/${{vars.mangled-package-version}}/bellsoft-jdk${{vars.mangled-package-version}}-src-full.tar.gz
       expected-sha512: 7e6697e3332e1972b67bfa9bafcd2896d749390aad532d018e67eda62851b5d20dbecbac48424e28559dc9dd196d64034b84f7e3e7cf91c4eb1310710e17282c
 
+  - name: Extract the googletest version from the source doc and Verify
+    runs: |
+      googletest_version=$(sed -n 's/.*https:\/\/github\.com\/google\/googletest\/releases\/tag\/\(v[0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p' doc/building.md)
+      if [ "$googletest_version" != "${{vars.googletest-version}}" ]; then
+        echo "Error: googletest version mismatch. Expected ${{vars.googletest-version}}, got $googletest_version"
+        exit 1
+      fi
+
   - working-directory: /home/build/googletest
     pipeline:
       - uses: fetch
         with:
-          uri: https://github.com/google/googletest/archive/v1.16.0.tar.gz
-          expected-sha512: bec8dad2a5abbea8e9e5f0ceedd8c9dbdb8939e9f74785476b0948f21f5db5901018157e78387e106c6717326558d6642fc0e39379c62af57bf1205a9df8a18b
+          uri: https://github.com/google/googletest/archive/${{vars.googletest-version}}.tar.gz
+          expected-sha512: 765c326ccc1b87a01027385e69238266e356361cd4ee3e18e3c9d137a5d11fa5d657c164d02dd1be8fe693c8e10f2b580588dbfa57d27f070e2750f50d3e662c
 
   - name: Fix usage of C-style isnan() for C++
     uses: patch
