Add metallb-fips with subpackage tests
Signed-off-by: Jamon Camisso <jamon@chainguard.dev>

diff --git a/metallb-fips.yaml b/metallb-fips.yaml
--- a/metallb-fips.yaml
+++ b/metallb-fips.yaml
@@ -55,6 +55,21 @@ subpackages:
     pipeline:
       - runs: |
           install -Dm755 "${{targets.destdir}}"/usr/bin/metallb-controller "${{targets.subpkgdir}}"/usr/bin/metallb-controller
+    test:
+      environment:
+        contents:
+          packages:
+            - metallb-controller-fips
+            - jq
+      pipeline:
+        - name: Check controller runs
+          runs: |
+            metallb-controller --help
+            error_message="open /var/run/secrets/kubernetes.io/serviceaccount/namespace: no such file or directory"
+            if ! metallb-controller | jq -r 'select(.error) .error' | grep -q "${error_message}"; then
+                exit 1
+            fi
+            echo "verified error message when not running in kubernetes"
 
   - name: metallb-frr-fips
     pipeline:
@@ -77,7 +92,26 @@ subpackages:
     dependencies:
       runtime:
         - bash # required by frr-reloader.sh
-        - metallb-frr
+        - metallb-frr-fips
+    test:
+      environment:
+        contents:
+          packages:
+            - metallb-speaker-fips
+            - jq
+      pipeline:
+        - name: Check speaker runs
+          runs: |
+            metallb-speaker --help
+            error_message="open /var/run/secrets/kubernetes.io/serviceaccount/namespace: no such file or directory"
+            if ! metallb-speaker | jq -r 'select(.error) .error' | grep -q "${error_message}"; then
+                exit 1
+            fi
+            echo "verified error message when not running in kubernetes"
+        - name: Check frr runs
+          runs: |
+            # doesn't throw any error when invoked directly so just run --help
+            metallb-frr-metrics --help
 
 update:
   enabled: true
@@ -85,15 +119,3 @@ update:
     identifier: metallb/metallb
     strip-prefix: v
     tag-filter: v
-
-test:
-  pipeline:
-    - name: Check controller runs
-      runs: |
-        metallb-controller --help
-    - name: Check speaker runs
-      runs: |
-        metallb-speaker --help
-    - name: Check frr runs
-      runs: |
-        metallb-frr-metrics --help
