mongod - update build
Fixes #4036

- no longer install distlib
- "workaround" poetry install failure.

diff --git a/mongod.yaml b/mongod.yaml
--- a/mongod.yaml
+++ b/mongod.yaml
@@ -39,18 +39,18 @@ pipeline:
       # The build runs better in a virtualenv as well.
       set -x
       python3 -m venv .venv
-      source .venv/bin/activate
+      . .venv/bin/activate
       python3 -m pip install 'poetry==1.5.1'
-      python3 -m pip install 'distlib==0.3.8'
 
-      # Now use that to install the build deps.
-      rc=0
-      PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring \
-          python3 -m poetry install --no-root --sync || rc=$?
-      if [ $rc -ne 0 ]; then
-          echo "========= that failed, gonna try again $rc ============="
-          PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring \
-              python3 -m poetry install --no-root --sync
+      # https://jira.mongodb.org/browse/WT-12911
+      # https://github.com/mongodb/mongo/commit/fba135f07efbcd6ce5ba74e9610e7848c82d849d
+      export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
+      if python3 -m poetry install --no-root --sync; then
+          echo "WT-12911: poetry install passed the first time. delete this if/else"
+      else
+          rc=$?
+          echo 'WT-12911: poetry install failed [$rc], "fixing" that problem by doing it again'
+          python3 -m poetry install --no-root --sync
       fi
 
       # Now do the build!
