this got much further, but failed on a link i think

diff --git a/mongod.yaml b/mongod.yaml
--- a/mongod.yaml
+++ b/mongod.yaml
@@ -37,13 +37,21 @@ pipeline:
   - runs: |
       # Mongo requires a very specific build of poetry to install build deps, our packaged one doesn't work.
       # The build runs better in a virtualenv as well.
+      set -x
       python3 -m venv .venv
       source .venv/bin/activate
       python3 -m pip install 'poetry==1.5.1'
       python3 -m pip install 'distlib==0.3.8'
 
       # Now use that to install the build deps.
-      python3 -m poetry install --no-root --sync
+      rc=0
+      PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring \
+          python3 -m poetry install --no-root --sync || rc=$?
+      if [ $rc -ne 0 ]; then
+          echo "========= that failed, gonna try again $rc ============="
+          PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring \
+              python3 -m poetry install --no-root --sync
+      fi
 
       # Now do the build!
       python3 ./buildscripts/scons.py --ssl --separate-debug=on install-devcore --disable-warnings-as-errors
