test: Add license and binary tests (#2565)
Signed-off-by: Joshua Powers <joshua.powers@chainguard.dev>

diff --git a/nvidia-cuda-sanitizer-api-12.0.yaml b/nvidia-cuda-sanitizer-api-12.0.yaml
--- a/nvidia-cuda-sanitizer-api-12.0.yaml
+++ b/nvidia-cuda-sanitizer-api-12.0.yaml
@@ -1,7 +1,7 @@
 package:
   name: nvidia-cuda-sanitizer-api-12.0
   version: 12.0.140
-  epoch: 0
+  epoch: 1
   description: CUDA Compute Sanitizer API
   copyright:
     - license: PROPRIETARY
@@ -65,6 +65,19 @@ subpackages:
     dependencies:
       runtime:
         - ${{package.name}}
+
+test:
+  pipeline:
+    - name: Run --help and --version
+      runs: |
+        /usr/local/cuda-${{vars.cuda-version}}/compute-sanitizer/compute-sanitizer --help
+        /usr/local/cuda-${{vars.cuda-version}}/compute-sanitizer/compute-sanitizer --version
+    - name: Verify the license
+      runs: |
+        if [ ! -f /usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE ]; then
+          echo "License file not found"
+          exit 1
+        fi
 
 update:
   enabled: false
