test: Introduce basic tests (#2559)
Signed-off-by: Joshua Powers <joshua.powers@chainguard.dev>

diff --git a/nvidia-cuda-cuxxfilt-11.8.yaml b/nvidia-cuda-cuxxfilt-11.8.yaml
--- a/nvidia-cuda-cuxxfilt-11.8.yaml
+++ b/nvidia-cuda-cuxxfilt-11.8.yaml
@@ -58,5 +58,18 @@ subpackages:
       runtime:
         - ${{package.name}}
 
+test:
+  pipeline:
+    - uses: test/tw/ldd-check
+    - name: Test binary
+      runs: |
+        [ "$(echo '_Z3fooi' | /usr/local/cuda-${{vars.cuda-version}}/bin/cu++filt)" = "foo(int)" ] && exit 0 || exit 1
+    - name: Verify license exists
+      runs: |
+        if [ ! -f /usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE ]; then
+          echo "License file not found"
+          exit 1
+        fi
+
 update:
   enabled: false
