nvidia-cuda-nvcc-[supported]: Improve handling of case where nvcc supports latest gcc
This is a difficult case because there is no gcc-<ver> binary for the
latest GCC version, so we need to do some gymnatics. Also, since there is no
gcc-15-default until gcc-15 is version-streamed, the nvcc-gcc-default's
dependency on gcc will eventually become incorrect. There's a test case
included here that will begin to fail, but it will require manually bumping
this package to repair. Until then, anything that builds by relying on
nvcc-13.0-gcc-default will fail to build when gcc becomes gcc-16 because
nvcc will detect an unsupported compiler version.

We really should treat gcc-latest more like other gcc's.

Note: previously we had pinned nvcc-13.0 to use gcc-14 due to hangs.
I believe those hangs were due to a recursion bug in the wrapper itself
that this commit fixes, so I've returned it to gcc=~15.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

diff --git a/nvidia-cuda-nvcc-12.4.yaml b/nvidia-cuda-nvcc-12.4.yaml
--- a/nvidia-cuda-nvcc-12.4.yaml
+++ b/nvidia-cuda-nvcc-12.4.yaml
@@ -62,14 +62,6 @@ subpackages:
     description: ${{package.name}} development headers
     pipeline:
       - uses: split/dev
-      - if: ${{build.arch}} == 'aarch64'
-        runs: |
-          # Override bits/math-vector.h for aarch64 as latest glibc ships symbols that nvcc
-          # does not export ; more details:
-          # https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/2033747
-          # https://github.com/OE4T/meta-tegra/commit/981245c8bf3164f16bd7f52fca6ea9c9fa8c349a
-          mkdir -p "${{targets.contextdir}}/usr/local/cuda-${{vars.cuda-version}}/include/bits"
-          install -m644 math-vector.h "${{targets.contextdir}}/usr/local/cuda-${{vars.cuda-version}}/include/bits/math-vector.h"
     dependencies:
       runtime:
         - ${{package.name}}
@@ -97,8 +89,13 @@ subpackages:
               std::cout << __GNUC__ << "\n";
             }
             EOF
+            if [ "$(g++ -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+              gxx_bin="g++"
+            else
+              gxx_bin="g++-${{vars.gcc-latest-major-version}}"
+            fi
             # Verify that the latest default gcc is available and works
-            "$nvcc" -ccbin g++-${{vars.gcc-latest-major-version}} \
+            "$nvcc" -ccbin "$gxx_bin" \
               "$tmpdir/gcc-version.cu" -o "$tmpdir/gcc-version"
             [ "$("$tmpdir/gcc-version")" = "${{vars.gcc-latest-major-version}}" ]
             # Attempt to verify that we build w/ the system gcc by default
@@ -124,6 +121,11 @@ subpackages:
             - nvidia-cuda-cudart-${{vars.cuda-version}}-dev
       pipeline:
         - runs: |
+            [ "$(gcc -dumpversion)" = "${{vars.gcc-latest-major-version}}" ] || \
+              { echo "ERROR: gcc ${{vars.gcc-latest-major-version}} appears to have been version streamed." 1>&2;
+                echo "ERROR: Please update dependency to point at gcc-${{vars.gcc-latest-major-version}}" 1>&2;
+                exit 1; }
+        - runs: |
             nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
             tmpdir="$(mktemp -d)"
             trap "rm -rf $tmpdir" EXIT
@@ -137,7 +139,7 @@ subpackages:
             "$nvcc" "$tmpdir/gcc-version.cu" -o "$tmpdir/gcc-version"
             [ "$("$tmpdir/gcc-version")" = "${{vars.gcc-latest-major-version}}" ]
 
-  - name: nvcc-gcc-${{vars.cuda-version}}
+  - name: nvcc-${{vars.cuda-version}}-gcc-wrapper
     description: ${{package.name}} configured to use latest compatible gcc
     dependencies:
       runtime:
@@ -149,9 +151,14 @@ subpackages:
           mkdir -p "${{targets.contextdir}}$cuda_home/bin"
           for cmd in gcc g++; do
             wrapper="${{targets.contextdir}}$cuda_home/bin/$cmd"
-            cat > "$wrapper" << EOF
+            cat > "$wrapper" << 'EOF'
           #!/bin/sh
-          exec ${cmd}-${{vars.gcc-latest-major-version}} "\$@"
+          if [ "$(/usr/local/bin/${0##*/} -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+            gcc_bin="/usr/local/bin/${0##*/}"
+          else
+            gcc_bin="/usr/local/bin/${0##*/}-${{vars.gcc-latest-major-version}}"
+          fi
+          exec ${gcc_bin} "$@"
           EOF
             chmod +x "$wrapper"
           done
@@ -193,8 +200,13 @@ test:
     - uses: test/tw/ldd-check
     - name: Test .c files can be compiled
       runs: |
+        if [ "$(gcc -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+          gcc_bin="gcc"
+        else
+          gcc_bin="gcc-${{vars.gcc-latest-major-version}}"
+        fi
         nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
-        nvcc_cmd="$nvcc -ccbin gcc-${{vars.gcc-latest-major-version}}"
+        nvcc_cmd="$nvcc -ccbin $gcc_bin"
         tmpdir="$(mktemp -d)"
         trap "rm -rf $tmpdir" EXIT
         cat <<EOF > "$tmpdir/test-c.c"
@@ -207,8 +219,13 @@ test:
         "$tmpdir/test-c"
     - name: Test .cu files can be compiled
       runs: |
+        if [ "$(gcc -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+          gcc_bin="gcc"
+        else
+          gcc_bin="gcc-${{vars.gcc-latest-major-version}}"
+        fi
         nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
-        nvcc_cmd="$nvcc -ccbin gcc-${{vars.gcc-latest-major-version}}"
+        nvcc_cmd="$nvcc -ccbin $gcc_bin"
         tmpdir="$(mktemp -d)"
         trap "rm -rf $tmpdir" EXIT
         cat <<EOF > "$tmpdir/test-cu.cu"
diff --git a/nvidia-cuda-nvcc-12.8.yaml b/nvidia-cuda-nvcc-12.8.yaml
--- a/nvidia-cuda-nvcc-12.8.yaml
+++ b/nvidia-cuda-nvcc-12.8.yaml
@@ -92,8 +92,13 @@ subpackages:
               std::cout << __GNUC__ << "\n";
             }
             EOF
+            if [ "$(g++ -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+              gxx_bin="g++"
+            else
+              gxx_bin="g++-${{vars.gcc-latest-major-version}}"
+            fi
             # Verify that the latest default gcc is available and works
-            "$nvcc" -ccbin g++-${{vars.gcc-latest-major-version}} \
+            "$nvcc" -ccbin "$gxx_bin" \
               "$tmpdir/gcc-version.cu" -o "$tmpdir/gcc-version"
             [ "$("$tmpdir/gcc-version")" = "${{vars.gcc-latest-major-version}}" ]
             # Attempt to verify that we build w/ the system gcc by default
@@ -118,6 +123,11 @@ subpackages:
             - ${{package.name}}-dev
             - nvidia-cuda-cudart-${{vars.cuda-version}}-dev
       pipeline:
+        - runs: |
+            [ "$(gcc -dumpversion)" = "${{vars.gcc-latest-major-version}}" ] || \
+              { echo "ERROR: gcc ${{vars.gcc-latest-major-version}} appears to have been version streamed." 1>&2;
+                echo "ERROR: Please update dependency to point at gcc-${{vars.gcc-latest-major-version}}" 1>&2;
+                exit 1; }
         - runs: |
             nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
             tmpdir="$(mktemp -d)"
@@ -144,9 +154,14 @@ subpackages:
           mkdir -p "${{targets.contextdir}}$cuda_home/bin"
           for cmd in gcc g++; do
             wrapper="${{targets.contextdir}}$cuda_home/bin/$cmd"
-            cat > "$wrapper" << EOF
+            cat > "$wrapper" << 'EOF'
           #!/bin/sh
-          exec ${cmd}-${{vars.gcc-latest-major-version}} "\$@"
+          if [ "$(/usr/local/bin/${0##*/} -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+            gcc_bin="/usr/local/bin/${0##*/}"
+          else
+            gcc_bin="/usr/local/bin/${0##*/}-${{vars.gcc-latest-major-version}}"
+          fi
+          exec ${gcc_bin} "$@"
           EOF
             chmod +x "$wrapper"
           done
@@ -188,8 +203,13 @@ test:
     - uses: test/tw/ldd-check
     - name: Test .c files can be compiled
       runs: |
+        if [ "$(gcc -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+          gcc_bin="gcc"
+        else
+          gcc_bin="gcc-${{vars.gcc-latest-major-version}}"
+        fi
         nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
-        nvcc_cmd="$nvcc -ccbin gcc-${{vars.gcc-latest-major-version}}"
+        nvcc_cmd="$nvcc -ccbin $gcc_bin"
         tmpdir="$(mktemp -d)"
         trap "rm -rf $tmpdir" EXIT
         cat <<EOF > "$tmpdir/test-c.c"
@@ -202,8 +222,13 @@ test:
         "$tmpdir/test-c"
     - name: Test .cu files can be compiled
       runs: |
+        if [ "$(gcc -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+          gcc_bin="gcc"
+        else
+          gcc_bin="gcc-${{vars.gcc-latest-major-version}}"
+        fi
         nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
-        nvcc_cmd="$nvcc -ccbin gcc-${{vars.gcc-latest-major-version}}"
+        nvcc_cmd="$nvcc -ccbin $gcc_bin"
         tmpdir="$(mktemp -d)"
         trap "rm -rf $tmpdir" EXIT
         cat <<EOF > "$tmpdir/test-cu.cu"
diff --git a/nvidia-cuda-nvcc-13.0.yaml b/nvidia-cuda-nvcc-13.0.yaml
--- a/nvidia-cuda-nvcc-13.0.yaml
+++ b/nvidia-cuda-nvcc-13.0.yaml
@@ -69,7 +69,15 @@ subpackages:
     description: metapackage for the latest gcc version supported by ${{package.name}}
     dependencies:
       runtime:
-        - gcc-${{vars.gcc-latest-major-version}}
+        # When the ${{vars.gcc-latest-major-version}} is the latest gcc, then
+        # this dependency should be gcc=~${{vars.gcc-latest-major-version}}.
+        # Otherwise, it should be gcc-${{vars.gcc-latest-major-version}}.
+        # The gcc=~ constraint will cause build-deps to fail in the window
+        # between gcc getting bumped to a new upstream and this package
+        # getting updated to depend on a version-streamed gcc instead. Just
+        # depending on "gcc" would allow build-deps to resolve, resulting
+        # in an attempt to use an unsupported gcc.
+        - gcc=~${{vars.gcc-latest-major-version}}
     test:
       environment:
         contents:
@@ -88,8 +96,13 @@ subpackages:
               std::cout << __GNUC__ << "\n";
             }
             EOF
+            if [ "$(g++ -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+              gxx_bin="g++"
+            else
+              gxx_bin="g++-${{vars.gcc-latest-major-version}}"
+            fi
             # Verify that the latest default gcc is available and works
-            "$nvcc" -ccbin g++-${{vars.gcc-latest-major-version}} \
+            "$nvcc" -ccbin "$gxx_bin" \
               "$tmpdir/gcc-version.cu" -o "$tmpdir/gcc-version"
             [ "$("$tmpdir/gcc-version")" = "${{vars.gcc-latest-major-version}}" ]
             # Attempt to verify that we build w/ the system gcc by default
@@ -106,7 +119,8 @@ subpackages:
     description: metapackage for the latest gcc version supported by ${{package.name}} as the system default
     dependencies:
       runtime:
-        - gcc-${{vars.gcc-latest-major-version}}-default
+        # See comment block in nvcc-${{vars.cuda-version}}-gcc
+        - gcc=~${{vars.gcc-latest-major-version}}
     test:
       environment:
         contents:
@@ -114,6 +128,11 @@ subpackages:
             - ${{package.name}}-dev
             - nvidia-cuda-cudart-${{vars.cuda-version}}-dev
       pipeline:
+        - runs: |
+            [ "$(gcc -dumpversion)" = "${{vars.gcc-latest-major-version}}" ] || \
+              { echo "ERROR: gcc ${{vars.gcc-latest-major-version}} appears to have been version streamed." 1>&2;
+                echo "ERROR: Please update dependency to point at gcc-${{vars.gcc-latest-major-version}}" 1>&2;
+                exit 1; }
         - runs: |
             nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
             tmpdir="$(mktemp -d)"
@@ -140,9 +159,14 @@ subpackages:
           mkdir -p "${{targets.contextdir}}$cuda_home/bin"
           for cmd in gcc g++; do
             wrapper="${{targets.contextdir}}$cuda_home/bin/$cmd"
-            cat > "$wrapper" << EOF
+            cat > "$wrapper" << 'EOF'
           #!/bin/sh
-          exec ${cmd}-${{vars.gcc-latest-major-version}} "\$@"
+          if [ "$(/usr/local/bin/${0##*/} -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+            gcc_bin="/usr/local/bin/${0##*/}"
+          else
+            gcc_bin="/usr/local/bin/${0##*/}-${{vars.gcc-latest-major-version}}"
+          fi
+          exec ${gcc_bin} "$@"
           EOF
             chmod +x "$wrapper"
           done
@@ -177,15 +201,23 @@ test:
   environment:
     contents:
       packages:
-        - gcc-${{vars.gcc-latest-major-version}}
+        # Used to check compat with latest GCC version
+        - gcc
+        # See comment block in nvcc-${{vars.cuda-version}}-gcc
+        - gcc=~${{vars.gcc-latest-major-version}}
         - nvidia-cuda-cudart-${{vars.cuda-version}}-dev
         - nvidia-cuda-nvcc-${{vars.cuda-version}}-dev
   pipeline:
     - uses: test/tw/ldd-check
     - name: Test .c files can be compiled
       runs: |
+        if [ "$(gcc -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+          gcc_bin="gcc"
+        else
+          gcc_bin="gcc-${{vars.gcc-latest-major-version}}"
+        fi
         nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
-        nvcc_cmd="$nvcc -ccbin gcc-${{vars.gcc-latest-major-version}}"
+        nvcc_cmd="$nvcc -ccbin $gcc_bin"
         tmpdir="$(mktemp -d)"
         trap "rm -rf $tmpdir" EXIT
         cat <<EOF > "$tmpdir/test-c.c"
@@ -198,8 +230,13 @@ test:
         "$tmpdir/test-c"
     - name: Test .cu files can be compiled
       runs: |
+        if [ "$(gcc -dumpversion)" = "${{vars.gcc-latest-major-version}}" ]; then
+          gcc_bin="gcc"
+        else
+          gcc_bin="gcc-${{vars.gcc-latest-major-version}}"
+        fi
         nvcc="/usr/local/cuda-${{vars.cuda-version}}/bin/nvcc"
-        nvcc_cmd="$nvcc -ccbin gcc-${{vars.gcc-latest-major-version}}"
+        nvcc_cmd="$nvcc -ccbin $gcc_bin"
         tmpdir="$(mktemp -d)"
         trap "rm -rf $tmpdir" EXIT
         cat <<EOF > "$tmpdir/test-cu.cu"
