test: Introduce basic test to verify license and directories (#2552)
Signed-off-by: Joshua Powers <joshua.powers@chainguard.dev>

diff --git a/nvidia-cuda-cccl-12.1.yaml b/nvidia-cuda-cccl-12.1.yaml
--- a/nvidia-cuda-cccl-12.1.yaml
+++ b/nvidia-cuda-cccl-12.1.yaml
@@ -48,6 +48,25 @@ pipeline:
       mv lib ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/lib64
       mv LICENSE ${{targets.destdir}}/usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE
 
+test:
+  pipeline:
+    - name: Verify license exists
+      runs: |
+        if [ ! -f /usr/local/cuda-${{vars.cuda-version}}/${{package.name}}.LICENSE ]; then
+          echo "License file not found"
+          exit 1
+        fi
+    - name: Verify lib and include directories exist
+      runs: |
+        if [ ! -d /usr/local/cuda-${{vars.cuda-version}}/lib64 ]; then
+          echo "lib64 directory not found"
+          exit 1
+        fi
+        if [ ! -d /usr/local/cuda-${{vars.cuda-version}}/include ]; then
+          echo "include directory not found"
+          exit 1
+        fi
+
 update:
   # No release-monitoring support for the multi-arch "enterprise" driver, only
   # for x86-only consumer release train.
