opensearch-2.yaml: fix shell error on patch file conditional and add additional check
Signed-off-by: Azimjon Ulmasov <azimjon.ulmasov@chainguard.dev>

diff --git a/opensearch-2.yaml b/opensearch-2.yaml
--- a/opensearch-2.yaml
+++ b/opensearch-2.yaml
@@ -166,8 +166,14 @@ subpackages:
           cd ./plugins/${{range.key}}
 
           # apply any CVE patches
-          if [ -f "${{range.value}}" ]; then
-              patch -p1 < "../../${{range.value}}"
+          PATCH=${{range.value}}
+          if [ -n "$PATCH" ]; then
+              if [ -f "../../$PATCH" ]; then
+                  patch -p1 < "../../${{range.value}}"
+              else
+                  echo "Patch specified but not found: $PATCH" >&2
+                  exit 1
+              fi
           fi
 
           # notifications source live in a subfolder
