fix(pgAdmin4): Refactor build process and use correct dependencies (#13196)
- Remove invokation of `make pip` (this did a complete rebuild of the UI
  doubling the time to build the package)
- Correctly build documentation (the docs were never actually built with
  sphinx previously)
- Remove setcap for host Python. This didn't do anything at the package
  level. We may need to revisit as the upstream image allows Python to
  bind to lower ports
- Remove Postgres compat subpackages. pgAdmin supports all supported
  versions of Postgres. These should be subpackages of Postgres instead
- Separate entrypoint script. pgAdmin can technically be installed and
  ran standalone from the entrypoint we ship on the image
- Add missing runtime dependencies and remove unused dependencies, such
  as node
- Use sudo instead of sudo-rs. Behavior is slightly different, and not
  all features of sudo are supported by sudo-rs
- Add pgadmin to sudoers so that it can properly launch postfix
- Use the entrypoint script in our tests and run as the pgadmin user
- Correctly include licenses for dependencies
- Clean up unused assets
- Pass environment to tests and run as correct user

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

diff --git a/pgadmin4.yaml b/pgadmin4.yaml
--- a/pgadmin4.yaml
+++ b/pgadmin4.yaml
@@ -1,32 +1,46 @@
 package:
   name: pgadmin4
   version: "8.14"
-  epoch: 0
-  description: "pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL, the most advanced Open Source database in the world."
+  epoch: 1
+  description: "Administration and development platform for PostgreSQL."
   copyright:
     - license: PostgreSQL
+    - license: LicenseRef-Dependencies
+      license-path: ./DEPENDENCIES
   dependencies:
     runtime:
-      - libpq-${{vars.latest-pg-version}}
-      - nodejs
+      - ca-certificates
+      - coreutils
+      - findutils
+      - gawk
+      - glibc-locale-en
+      - grep
+      - krb5-libs
+      - libcap
+      - libedit
+      - libjpeg-turbo
+      - libldap
+      - liblz4-1
+      - libpq
+      - libzstd1
+      - posix-libc-utils
       - postfix
+      - py${{vars.py-version}}-pip
       - py${{vars.py-version}}-setuptools
       - python-${{vars.py-version}}
-      - sudo-rs
+      - sed
+      - shadow
+      - tzdata
 
 vars:
-  py-version: 3.13
-  latest-pg-version: 17
+  py-version: 3.12
+  pg-version: 17
 
-data:
-  - name: pg-versions
-    items:
-      12: '12'
-      13: '13'
-      14: '14'
-      15: '15'
-      16: '16'
-      17: '17'
+var-transforms:
+  - from: ${{package.version}}
+    match: '\.'
+    replace: "_"
+    to: mangled-package-version
 
 environment:
   contents:
@@ -42,30 +56,24 @@ environment:
       - libffi-dev
       - libjpeg-turbo-dev
       - libpng-dev
-      - libpq-${{vars.latest-pg-version}}
+      - libpq
       - libtool
-      - make
       - nasm
       - nodejs
       - npm
       - openssl-dev
       - pkgconf-dev
-      - postgresql-${{vars.latest-pg-version}}-contrib
-      - postgresql-${{vars.latest-pg-version}}-dev
+      - postgresql-${{vars.pg-version}}-dev
       - py${{vars.py-version}}-pip
       - py${{vars.py-version}}-setuptools
       - python-${{vars.py-version}}-dev
       - rust
-      - shadow
       - yarn
       - yasm
       - zlib-dev
-
-var-transforms:
-  - from: ${{package.version}}
-    match: '\.'
-    replace: "_"
-    to: mangled-package-version
+  environment:
+    LANG: en_US.UTF-8
+    LC_ALL: en_US.UTF-8
 
 pipeline:
   - uses: git-checkout
@@ -75,9 +83,16 @@ pipeline:
       tag: REL-${{vars.mangled-package-version}}
 
   - name: Building Web Assests
+    working-directory: ./web
     runs: |
-      cd web
-      export CPPFLAGS="$CPPFLAGS -DPNG_ARM_NEON_OPT=0"
+      rm -rf regression \
+        `find . -type d -name tests` \
+        `find . -type f -name .DS_Store`
+
+      # Build UI
+      if [ ${{build.arch}} = "aarch64" ]; then
+        export CPPFLAGS="$CPPFLAGS -DPNG_ARM_NEON_OPT=0"
+      fi
       npm install -g corepack
       corepack enable
       yarn set version berry
@@ -85,116 +100,114 @@ pipeline:
       yarn install
       yarn run bundle
 
+      # Cleanup
+      rm -rf node_modules yarn.lock package.json \
+        .[^.]* babel.cfg webpack.* jest.config.js \
+        babel.* ./pgadmin/static/js/generated/.cache
+
   - name: Build package
     runs: |
-      # Setup Python virtual environment
+      # Setup virtual environment
       python${{vars.py-version}} -m venv venv --system-site-packages
       source venv/bin/activate
 
-      # Install Python dependencies
+      # Install pgAdmin dependencies
       pip install --upgrade pip
       pip install -r requirements.txt
-      pip install sphinx sphinxcontrib-youtube
       pip install --no-cache-dir gunicorn
-      pip install -r web/regression/requirements.txt
 
-      # Build documentation and ignore warnings
-      make -C docs/en_US -f Makefile.sphinx SPHINXOPTS='' html || echo "Documentation warnings ignored"
+      # Copy over virtual env
+      mkdir -p ${{targets.contextdir}}/venv
+      cp -r venv/* ${{targets.contextdir}}/venv
 
-      # Build Python package
-      make pip
+      # Build documentation
+      pip install sphinx sphinxcontrib-youtube
+      sphinx-build docs/en_US docs/en_US/_build/html
 
-      # Create the /pgadmin4 directory and copy the source into it
-      mkdir -p ${{targets.destdir}}/pgadmin4
-      mkdir -p ${{targets.destdir}}/venv
-      mkdir -p ${{targets.destdir}}/var/lib/pgadmin
-      mkdir -p ${{targets.destdir}}/var/log/pgadmin
+      # Uninstall pip
+      sed -i '1s|.*/home/build.*|#!${{targets.contextdir}}/venv/bin/python|' $(find ${{targets.contextdir}}/venv/bin -maxdepth 1 -type f)
+      source ${{targets.contextdir}}/venv/bin/activate
+      pip uninstall --yes pip
 
-      # Add the pgadmin user
-      useradd -r -u 5050 -g root -s /sbin/nologin pgadmin
+      # Correct virtual env path
+      sed -i '1s|.*/home/build.*|#!/venv/bin/python|' $(find ${{targets.contextdir}}/venv/bin -maxdepth 1 -type f)
 
-      # Set permissions for directories and files
-      chown -R pgadmin:root ${{targets.destdir}}/var/lib/pgadmin ${{targets.destdir}}/var/log/pgadmin
+      # Create directories used by pgAdmin
+      mkdir -p ${{targets.contextdir}}/pgadmin4/docs
+      mkdir -p ${{targets.contextdir}}/run/pgadmin
+      mkdir -p ${{targets.contextdir}}/var/lib/pgadmin
+      mkdir -p ${{targets.contextdir}}/var/log/pgadmin
 
-      # Copy in the code and docs
-      cp -R web/* ${{targets.destdir}}/pgadmin4
-      cp -R docs/ ${{targets.destdir}}/pgadmin4/
-      cp -R venv/ ${{targets.destdir}}/
-      cp ./pkg/docker/run_pgadmin.py ${{targets.destdir}}/pgadmin4/
-      cp ./pkg/docker/gunicorn_config.py ${{targets.destdir}}/pgadmin4/
-      cp ./pkg/docker/entrypoint.sh ${{targets.destdir}}/entrypoint.sh
+      # Install pgAdmin
+      cp -r web/* ${{targets.contextdir}}/pgadmin4/
+      cp -r docs/* ${{targets.contextdir}}/pgadmin4/docs/
+      cp ./pkg/docker/run_pgadmin.py ${{targets.contextdir}}/pgadmin4/
+      cp ./pkg/docker/gunicorn_config.py ${{targets.contextdir}}/pgadmin4/
+      touch ${{targets.contextdir}}/pgadmin4/config_distro.py
 
-      # License files
-      cp -R ./LICENSE ${{targets.destdir}}/pgadmin4/
-      cp -R ./DEPENDENCIES ${{targets.destdir}}/pgadmin4/
+      # Remove pycache
+      find ${{targets.contextdir}} -type d -name '__pycache__' -exec rm -rf {} +
+      find ${{targets.contextdir}} -type f -name '*.pyc' -exec rm -rf {} +
 
-      # entrypoint.sh script required files, permissions, and path
-      touch ${{targets.destdir}}/pgadmin4/config_distro.py
-      chown pgadmin:root ${{targets.destdir}}/pgadmin4/config_distro.py
-
-      # Update the gunicorn binary path
-      sed -i '1s|^.*|#!/venv/bin/python|' ${{targets.destdir}}/venv/bin/gunicorn
-
-      # Allow Python to bind to low-numbered ports
-      setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/python${{vars.py-version}}
+      # Add pgadmin to sudoers
+      mkdir -p ${{targets.contextdir}}/etc/sudoers.d
+      echo "pgadmin ALL = NOPASSWD: /usr/sbin/postfix start" > ${{targets.contextdir}}/etc/sudoers.d/postfix
+      echo "pgadminr ALL = NOPASSWD: /usr/sbin/postfix start" >> ${{targets.contextdir}}/etc/sudoers.d/postfix
 
 subpackages:
-  - range: pg-versions
-    name: pgadmin4-pg${{range.key}}
-    description: Postgres${{range.key}} version of ${{package.name}}
+  - name: ${{package.name}}-oci-entrypoint
+    description: pgAdmin 4 OCI entrypoint
     dependencies:
       runtime:
-        - postgresql-${{range.key}}-client-base
+        - bash
+        - sudo
     pipeline:
-      - name: "Copy PG Binaries"
-        runs: |
-          # Copy the PG binaries
-          mkdir  -p ${{targets.contextdir}}/usr/local/pgsql-${{range.key}}
-          ln -sf  /usr/libexec/postgresql${{range.key}}/pg_dump ${{targets.contextdir}}/usr/local/pgsql-${{range.key}}/
-          ln -sf  /usr/libexec/postgresql${{range.key}}/pg_dumpall ${{targets.contextdir}}/usr/local/pgsql-${{range.key}}/
-          ln -sf  /usr/libexec/postgresql${{range.key}}/pg_restore ${{targets.contextdir}}/usr/local/pgsql-${{range.key}}/
-          ln -sf  /usr/libexec/postgresql${{range.key}}/psql ${{targets.contextdir}}/usr/local/pgsql-${{range.key}}/
+      - runs: |
+          mkdir -p ${{targets.contextdir}}
+          cp ./pkg/docker/entrypoint.sh ${{targets.contextdir}}/entrypoint.sh
     test:
       pipeline:
-        - name: "stat symlink"
-          runs: |
-            stat /usr/local/pgsql-${{range.key}}/pg_dump
-            stat /usr/local/pgsql-${{range.key}}/pg_dumpall
-            stat /usr/local/pgsql-${{range.key}}/pg_restore
-            stat /usr/local/pgsql-${{range.key}}/psql
+        - runs: |
+            stat /entrypoint.sh
+            if [[ ! -x /entrypoint.sh ]]; then
+              echo "Entrypoint script isn't executable!" && exit 1
+            fi
 
 test:
   environment:
     contents:
       packages:
-        - postgresql-${{vars.latest-pg-version}}
-        - postgresql-${{vars.latest-pg-version}}-client
-        - py${{vars.py-version}}-setuptools
-        - shadow
-        - sudo-rs
         - curl
-        - glibc-locale-en
-    environment:
-      PYTHONPATH: /pgadmin4
-      PGADMIN_SETUP_EMAIL: admin@gmail.com
-      PGADMIN_SETUP_PASSWORD: admin123
-      PGDATA: /tmp/test_db
-      PGUSER: wolfi
+        - sudo
+    accounts:
+      users:
+        - username: pgadmin
+          uid: 5050
+          gid: 0
+        - username: postfix
+          uid: 100
+          gid: 101
+      # sudo must retain permissions
+      run-as: 0
   pipeline:
-    - name: "Test database creation"
+    - name: "Set permissions"
       runs: |
-        useradd $PGUSER
-        sudo -u $PGUSER initdb -D /tmp/test_db
-        sudo -u $PGUSER pg_ctl -D /tmp/test_db -l /tmp/logfile start
-        createdb testdb
-        psql -lqt | cut -d \| -f 1 | grep -qw testdb
-    - name: "Start pgAdmin4 Server"
+        chown -R pgadmin:root \
+          /pgadmin4 \
+          /var/lib/pgadmin \
+          /var/log/pgadmin \
+          /run/pgadmin
+    - name: "Start pgAdmin4 server"
       uses: test/daemon-check-output
       working-directory: /pgadmin4
       with:
         start: |
-          env PATH="/venv/bin:$PATH" \
-           python${{vars.py-version}} pgAdmin4.py
+          sudo -u pgadmin env \
+            PATH="/venv/bin:$PATH" \
+            PYTHONPATH="/pgadmin4" \
+            PGADMIN_SETUP_EMAIL="admin@pgadmin.com" \
+            PGADMIN_SETUP_PASSWORD="r4nd0mP455w0rd" \
+            python${{vars.py-version}} pgAdmin4.py
         expected_output: |
           Starting pgAdmin 4. Please navigate to http://127.0.0.1:5050 in your browser.
         error_strings: |
@@ -202,7 +215,7 @@ test:
           "FAIL"
           "FATAL"
           "Traceback.*most.recent.call"
-        timeout: 60
+        timeout: 15
         post: |
           curl -X POST http://127.0.0.1:5050/login \
               -d "email=$PGADMIN_SETUP_EMAIL&password=$PGADMIN_SETUP_PASSWORD" \
