pgaudit-12: add test based on upstream's tests (#15819)

diff --git a/pgaudit-12.yaml b/pgaudit-12.yaml
--- a/pgaudit-12.yaml
+++ b/pgaudit-12.yaml
@@ -30,6 +30,42 @@ pipeline:
       mkdir -p ${{targets.destdir}}/usr/share/postgresql/extension
       make USE_PGXS=1 DESTDIR=${{targets.destdir}} PG_CONFIG=/usr/bin/pg_config install
 
+test:
+  environment:
+    contents:
+      packages:
+        - make
+        - postgresql-12
+        - postgresql-12-client
+        - postgresql-12-contrib
+        - shadow
+        - sudo-rs
+    environment:
+      PGDATA: /tmp/test_db
+      PGUSER: wolfi
+  pipeline:
+    - uses: git-checkout
+      with:
+        repository: https://github.com/pgaudit/pgaudit.git
+        tag: ${{package.version}}
+        expected-commit: 21fea0792139529302e02af145c90f7ec5cff2eb
+    - runs: |
+        # Based on upstream tests in https://github.com/pgaudit/pgaudit/tree/main/test
+        useradd $PGUSER
+        sudo -u $PGUSER initdb -D $PGDATA
+        echo "shared_preload_libraries = 'pgaudit'" >> ${PGDATA}/postgresql.conf
+        if ! sudo -u $PGUSER pg_ctl -D $PGDATA -l /tmp/logfile start; then
+          echo "!!! SERVER STARTUP FAILED"
+          cat /tmp/logfile
+          exit 1
+        fi
+
+        if ! make installcheck USE_PGXS=1; then
+          echo "!!! INSTALLCHECK FAILED"
+          cat regression.diffs
+          exit 1
+        fi
+
 update:
   enabled: true
   github:
