pgaudit-15: add test using upstream's tests

diff --git a/pgaudit-15.yaml b/pgaudit-15.yaml
--- a/pgaudit-15.yaml
+++ b/pgaudit-15.yaml
@@ -30,6 +30,42 @@ pipeline:
       mkdir -p ${{targets.destdir}}/usr/share/postgresql/extension
       make USE_PGXS=1 DESTDIR=${{targets.destdir}} PG_CONFIG=/usr/bin/pg_config install
 
+test:
+  environment:
+    contents:
+      packages:
+        - make
+        - postgresql-15
+        - postgresql-15-client
+        - postgresql-15-contrib
+        - shadow
+        - sudo-rs
+    environment:
+      PGDATA: /tmp/test_db
+      PGUSER: wolfi
+  pipeline:
+    - uses: git-checkout
+      with:
+        repository: https://github.com/pgaudit/pgaudit.git
+        tag: ${{package.version}}
+        expected-commit: 72da89c3fa02f3f2b9f3933214d91ad9c3428467
+    - runs: |
+        # Based on upstream tests in https://github.com/pgaudit/pgaudit/tree/main/test
+        useradd $PGUSER
+        sudo -u $PGUSER initdb -D $PGDATA
+        echo "shared_preload_libraries = 'pgaudit'" >> ${PGDATA}/postgresql.conf
+        if ! sudo -u $PGUSER pg_ctl -D $PGDATA -l /tmp/logfile start; then
+          echo "!!! SERVER STARTUP FAILED"
+          cat /tmp/logfile
+          exit 1
+        fi
+
+        if ! make installcheck USE_PGXS=1; then
+          echo "!!! INSTALLCHECK FAILED"
+          cat regression.diffs
+          exit 1
+        fi
+
 update:
   enabled: true
   github:
