python - replace bundled wheels (setuptools and pip) with depends. (#6512)
This applies the changes in https://github.com/wolfi-dev/os/pull/25818
to python 3.8 and python 3.9 that are in enterprise-packages.

1. Replace the bundled wheels of pip and setuptools that
   are found in python with dependencies on
   py3-pip-wheel and py3-setuptools-wheel.

2. Add tests running 'python -m venv' and
   'pip check' to make sure that the included versions are
   supported with the used python.

3. compile python with `--with-wheel-pkg-dir=/usr/share/python-wheels`.
   This enables ensurepip to find the wheels added in 2.

4. backport --with-wheel-pkg-dir to 3.8 and 3.9

Signed-off-by: Scott Moser <scott.moser@chainguard.dev>

diff --git a/python-3.8.yaml b/python-3.8.yaml
--- a/python-3.8.yaml
+++ b/python-3.8.yaml
@@ -1,7 +1,7 @@
 package:
   name: python-3.8
   version: 3.8.19
-  epoch: 1
+  epoch: 2
   description: "the Python programming language"
   copyright:
     - license: PSF-2.0
@@ -66,6 +66,10 @@ pipeline:
     with:
       patches: mpdecimal-2.5.1.patch
 
+  - uses: patch
+    with:
+      patches: wheel-pkg-dir-GH-24210.patch
+
   # remove this when a new securtiy patch is released
   - uses: patch
     with:
@@ -94,7 +98,8 @@ pipeline:
          --with-system-ffi \
          --with-system-libmpdec \
          --without-ensurepip \
-         --with-lto
+         --with-lto \
+         --with-wheel-pkg-dir=/usr/share/python-wheels
 
   - uses: autoconf/make
 
@@ -119,6 +124,9 @@ pipeline:
       rmdir site-packages
 
   - runs: |
+      rm -R ${{targets.destdir}}/usr/lib/${{vars.python}}/ensurepip/_bundled/
+
+  - runs: |
       find ${{targets.destdir}}/usr/lib -type f -name '*.pyc' -exec rm -rf '{}' +
       find ${{targets.destdir}}/usr/lib -type f -name '*.pyo' -exec rm -rf '{}' +
 
@@ -130,7 +138,11 @@ pipeline:
 
 subpackages:
   - name: "${{package.name}}-base"
-    description: "${{package.name}} as /usr/bin/python3"
+    description: "${{package.name}} without /usr/bin/python3"
+    dependencies:
+      runtime:
+        - py3-setuptools-wheel
+        - py3-pip-wheel
     pipeline:
       - runs: |
           mkdir -p ${{targets.subpkgdir}}/usr/bin ${{targets.subpkgdir}}/usr/lib
@@ -158,6 +170,40 @@ subpackages:
         - runs: |
             ${{vars.python}} CVE-2023-27043-unittest.py
             ${{vars.python}} version-check.py ${{package.version}}
+        - name: Verify venv installs expected packages
+          runs: |
+            set +x
+            d=$(mktemp -d)
+            echo "$ ${{vars.python}} -m venv $d"
+            ${{vars.python}} -m venv "$d"
+            echo "$ $d/bin/pip list"
+            $d/bin/pip list | tee "$d/list.txt"
+            wd=/usr/share/python-wheels
+            for pkg in setuptools pip ; do
+              set -- "$wd"/$pkg-*.whl
+              [ $# -eq 1 ] || {
+                echo "ERROR: found $# wheels in $wd matching $pkg-*.whl";
+                exit 1;
+              }
+              [ -f "$1" ] || {
+                echo "ERROR: $wd/$pkg-*.whl ('$1') was not a file"
+                exit 1
+              }
+              # name is like pip-24.2-py3-none-any.whl. second token is version.
+              wheel=${1}
+              tmp=${wheel##*/}
+              tmp=${tmp#*-}
+              ver=${tmp%%-*}
+              if ! grep -q "$pkg[ ]\+${ver}$" "$d/list.txt"; then
+                  echo "FAIL: did not find '$pkg==$ver' in venv"
+                  echo "pip list had:"
+                  sed 's,^,>,' "$d/list.txt"
+                  exit 1
+              fi
+              echo "PASS: venv installed '$pkg==$ver'"
+            done
+
+            rm -Rf "$d"
 
   - name: "${{package.name}}-doc"
     description: "python3 documentation"
@@ -192,7 +238,7 @@ subpackages:
         - ${{package.name}}-base=${{package.full-version}}
     pipeline:
       - runs: |
-          # usr/lib/pytyon3.X/config-3.X-x86_64-linux-gnu
+          # usr/lib/python3.X/config-3.X-x86_64-linux-gnu
           # split/dev will only move 2 files from it, but we want all of it.
           d="usr/lib/${{vars.python}}"
           mkdir -p "${{targets.subpkgdir}}/$d"
@@ -209,6 +255,13 @@ test:
     - name: "verify c-decimal"
       runs: |
         python3 -c 'import _decimal'
+    - name: Verify working python3 -m venv
+      runs: |
+        d=$(mktemp -d)
+        python3 -m venv "$d"
+        $d/bin/pip list
+        $d/bin/pip check
+        rm -Rf "$d"
 
 update:
   enabled: true
