Update spring-boot.yaml

diff --git a/spring-boot.yaml b/spring-boot.yaml
--- a/spring-boot.yaml
+++ b/spring-boot.yaml
@@ -52,15 +52,13 @@ test:
         - libudev
   pipeline:
     - runs: |
-        JARFILE="/home/nonroot/.m2/repository/org/springframework/boot/spring-boot/${{package.version}}/spring-boot-${{package.version}}.jar"
-        SNAPSHOT_JARFILE="/home/nonroot/.m2/repository/org/springframework/boot/spring-boot/${{package.version}}-SNAPSHOT/spring-boot-${{package.version}}-SNAPSHOT.jar"
-        if [ -f "$JARFILE" ] || [ -f "$SNAPSHOT_JARFILE" ]; then
-          echo "Successfully installed spring-boot jars into Maven"
-          exit 0
-        else
-          echo "Maven install was not successful"
-          exit 1
+        #!/bin/bash
+        RESULTS=$(find /home/nonroot/.m2/repository/org/springframework/boot/ -iname '*spring-boot-${{package.version}}*.jar')
+        if [[ -z "$RESULTS" ]]; then
+            echo "Error: No matching files found."
+            exit 1
         fi
+        echo "Maven install successful"
 
 update:
   enabled: true
