surrealdb/2.3.4 package update (#2789)
* surrealdb/2.3.4 package update

Signed-off-by: wolfi-bot <121097084+wolfi-bot@users.noreply.github.com>

* Fix test

Signed-off-by: egibs <20933572+egibs@users.noreply.github.com>

---------

Signed-off-by: wolfi-bot <121097084+wolfi-bot@users.noreply.github.com>
Signed-off-by: egibs <20933572+egibs@users.noreply.github.com>
Co-authored-by: wolfi-bot <121097084+wolfi-bot@users.noreply.github.com>
Co-authored-by: egibs <20933572+egibs@users.noreply.github.com>

diff --git a/surrealdb.yaml b/surrealdb.yaml
--- a/surrealdb.yaml
+++ b/surrealdb.yaml
@@ -1,7 +1,7 @@
 package:
   name: surrealdb
-  version: "2.3.3"
-  epoch: 2
+  version: "2.3.4"
+  epoch: 0
   description: "A scalable, distributed, collaborative, document-graph database, for the realtime web"
   copyright:
     - license: BUSL-1.1
@@ -27,7 +27,7 @@ pipeline:
     with:
       repository: https://github.com/surrealdb/surrealdb
       tag: v${{package.version}}
-      expected-commit: 3207642c1f5b7ffcb8798a59f37165ae5835229f
+      expected-commit: da9a256f8012c81fa8281fa6ddc5028177f6be0d
 
   - name: Configure and build
     runs: |
@@ -63,39 +63,34 @@ test:
     - name: Start SurrealDB server in memory and test basic CRUD operations
       runs: |
         # Start SurrealDB server in-memory mode with extended th root user
-        surreal start memory --user root --pass root &
+        surreal start memory --user root --pass root > out.log 2>&1 &
 
         # Wait to ensure the server is fully initialized
         sleep 5
 
         # Run CRUD operation TEST
-        {
-          echo "Running CRUD operations on SurrealDB..."
+        echo "Running CRUD operations on SurrealDB..."
 
-          # Create a record
-          echo "CREATE person SET name = 'John Doe', age = 30;" | surreal sql --namespace testns --database testdb -u root -p root
+        # Create a record
+        echo "CREATE person SET name = 'John Doe', age = 30;" | surreal sql --namespace testns --database testdb -u root -p root
 
-          # Read and verify the record
-          if ! echo "SELECT * FROM person;" | surreal sql --namespace testns --database testdb -u root -p root | grep -qi "John Doe"; then
-            echo "Record not found in READ operation."
-            exit 1
-          fi
-
-
-          # Update the record
-          echo "UPDATE person SET age = 31 WHERE name = 'John Doe';" | surreal sql --namespace testns --database testdb -u root -p root
-
-          # # Verify the updated age
-          if ! echo "SELECT * FROM person WHERE name = 'John Doe';" | surreal sql --namespace testns --database testdb -u root -p root | grep -qi "31"; then
-            echo "Failed to verify UPDATED record."
-            exit 1
-          fi
-
-          # Delete the record
-          echo "DELETE FROM person WHERE name = 'John Doe';" | surreal sql --namespace testns --database testdb -u root -p root
-
-          echo "CRUD operations completed successfully."
-        } || {
-          echo "An error occurred during CRUD operations."
+        # Read and verify the record
+        if ! echo "SELECT * FROM person;" | surreal sql --namespace testns --database testdb -u root -p root | grep -qi "John Doe"; then
+          echo "Record not found in READ operation."
           exit 1
-        }
+        fi
+
+
+        # Update the record
+        echo "UPDATE person SET age = 31 WHERE name = 'John Doe';" | surreal sql --namespace testns --database testdb -u root -p root
+
+        # # Verify the updated age
+        if ! echo "SELECT * FROM person WHERE name = 'John Doe';" | surreal sql --namespace testns --database testdb -u root -p root | grep -qi "31"; then
+          echo "Failed to verify UPDATED record."
+          exit 1
+        fi
+
+        # Delete the record
+        echo "DELETE FROM person WHERE name = 'John Doe';" | surreal sql --namespace testns --database testdb -u root -p root
+
+        echo "CRUD operations completed successfully."
