Add test to tomcat-9 with openjdk-8. (#5910)
* copy test/daemon-check-output.yaml pipeline from wolfi

daemon-check-output.yaml is a copy from wolfi-dev/os at
5c3d54dcba6a30b9de976913ab1681247867bdc3

Signed-off-by: Scott Moser <scott.moser@chainguard.dev>

* Add test to tomcat-9 with openjdk-8.

I wanted to do a range with this and test multiple java
but for now we can only do one.

https://github.com/chainguard-dev/melange/issues/1385

This recreates a failure seen
https://github.com/chainguard-dev/image-release-stats/issues/257

Signed-off-by: Scott Moser <scott.moser@chainguard.dev>

---------

Signed-off-by: Scott Moser <scott.moser@chainguard.dev>

diff --git a/tomcat-9.yaml b/tomcat-9.yaml
--- a/tomcat-9.yaml
+++ b/tomcat-9.yaml
@@ -98,6 +98,46 @@ subpackages:
           mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat/webapps.dist
           cp -r output/build/webapps/* ${{targets.subpkgdir}}/usr/share/tomcat/webapps.dist/
 
+test:
+  environment:
+    contents:
+      packages:
+        - curl
+        - ${{package.name}}-webapps
+        - openjdk-8-jre
+        - tomcat-native
+    environment:
+      LD_LIBRARY_PATH: "/usr/lib/tomcat-native"
+  pipeline:
+    - name: Test tomcat with java 8
+      uses: test/daemon-check-output
+      with:
+        setup: |
+          #!/bin/sh -ex
+          cp /usr/share/tomcat/webapps.dist/docs/appdev/sample/sample.war /usr/share/tomcat/webapps/
+        start: "env JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk /usr/share/tomcat/bin/catalina.sh run"
+        timeout: 30
+        expected_output: |
+          Tomcat/${{package.version}}
+          JVM.Version.*1.8
+          Deploying.*sample.war
+          Server startup in
+        post: |
+          #!/bin/sh -e
+          url=http://localhost:8080/sample/
+          echo "testing $url"
+          response=$(curl -s "$url") || {
+            echo "curl $url failed $?"
+            exit 1
+          }
+          expected="Sample.*Hello.*World.*Application"
+          echo "$response" | grep -q "$expected" || {
+            echo "response from $url did not contain \"$expected\""
+            echo "response: $response"
+            exit 1
+          }
+          echo "found \"$expected\" in output of curl $url"
+
 update:
   enabled: true
   ignore-regex-patterns:
