fix(tomcat): Build packages for supported JDK versions (#6795)
* fix(tomcat): Build packages for supported JDK versions

Allows us to bundle the correct JDK version with the package and run
tests for each supported JDK version at the package level

Pros:
  - Better test coverage
  - Easier at the image level to determine appopriate JDK version
  - Packages can be built with the appropriate JDK version without
    losing out on any potential enhancements from building with an older
    version

Cons:
  - In the case of Tomcat, we end up building the same package a couple
    times (same JDK version used at buildtime for 11, 17, and 21), and
    this will likley be an issue for other Java programs
      - Potential workaround here is even more subpackages, but then
	we're making things more complex, requiring duplicate code
	changes in a single package definition

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

* fix(tomcat): Make test part of build pipeline

There's a bug in melange where testing dependencies aren't added if
using a range to create subpackages

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

* chore(tomcat): Add JDK compat comments

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

---------

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

diff --git a/tomcat-9.yaml b/tomcat-9.yaml
--- a/tomcat-9.yaml
+++ b/tomcat-9.yaml
@@ -1,7 +1,7 @@
 package:
   name: tomcat-9
   version: 9.0.93
-  epoch: 0
+  epoch: 1
   description: Apache Tomcat Web Server
   copyright:
     - license: Apache-2.0
@@ -9,17 +9,29 @@ package:
     provides:
       - tomcat=${{package.full-version}}
 
+data:
+  - name: openjdk-versions
+    items:
+      21: "openjdk-21"
+      17: "openjdk-17"
+      11: "openjdk-11"
+      8: "openjdk-8"
+
 environment:
   contents:
     packages:
       - ant
       - build-base
       - busybox
+      - curl
       - ca-certificates-bundle
+      # Only 8 and 17 are used during the build process
+      # 11 and 21 are included for tests
+      - openjdk-21
       - openjdk-17
+      - openjdk-11
       - openjdk-8
-  environment:
-    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
+      - tomcat-native
 
 pipeline:
   - uses: git-checkout
@@ -35,108 +47,85 @@ pipeline:
       compile.debug=false
       EOF
 
-  - runs: |
-      ant
-
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat
-      cp LICENSE ${{targets.destdir}}/usr/share/tomcat/
-
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/bin
-      cp output/build/bin/* ${{targets.destdir}}/usr/share/tomcat/bin
-
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/conf
-      cp output/build/conf/* ${{targets.destdir}}/usr/share/tomcat/conf
-
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/lib
-      cp output/build/lib/* ${{targets.destdir}}/usr/share/tomcat/lib
-
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/logs
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/temp
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/webapps
-
 subpackages:
-  # This package includes the manager and host-manager apps.
-  # The apps are not directly usable without copying into the webapps directory.
-  # See https://github.com/docker-library/tomcat/pull/181 for more context.
-  - name: ${{package.name}}-webapps
+  - range: openjdk-versions
+    name: tomcat-9-${{range.value}}
     dependencies:
       runtime:
-        - tomcat-9
+        - ${{range.value}}-default-jvm
+        - tomcat-native
     pipeline:
       - runs: |
-          mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat/webapps.dist
-          cp -r output/build/webapps/* ${{targets.subpkgdir}}/usr/share/tomcat/webapps.dist/
+          if [[ "${{range.key}}" == "8" ]]; then
+            export JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk"
+          else
+            export JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
+          fi
 
-  - name: ${{package.name}}-jdk8
-    description: tomcat-9 with jdk 8
-    dependencies:
-    pipeline:
-      - runs: |
-          export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
-
-          # tidy up jdk 17 build
-          rm -rf output/build
-          # skip build.xml version check
           ant -Dskip.build.java.version=true
 
-          mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat
-          cp LICENSE ${{targets.subpkgdir}}/usr/share/tomcat/
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat
+          cp LICENSE ${{targets.contextdir}}/usr/share/tomcat/
 
-          mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat/bin
-          cp output/build/bin/* ${{targets.subpkgdir}}/usr/share/tomcat/bin
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/bin
+          cp output/build/bin/* ${{targets.contextdir}}/usr/share/tomcat/bin
 
-          mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat/conf
-          cp output/build/conf/* ${{targets.subpkgdir}}/usr/share/tomcat/conf
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/conf
+          cp output/build/conf/* ${{targets.contextdir}}/usr/share/tomcat/conf
 
-          mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat/lib
-          cp output/build/lib/* ${{targets.subpkgdir}}/usr/share/tomcat/lib
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/lib
+          cp output/build/lib/* ${{targets.contextdir}}/usr/share/tomcat/lib
 
-          mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat/logs
-          mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat/temp
-          mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat/webapps
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/logs
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/temp
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/webapps
 
-          mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat/webapps.dist
-          cp -r output/build/webapps/* ${{targets.subpkgdir}}/usr/share/tomcat/webapps.dist/
-
-test:
-  environment:
-    contents:
-      packages:
-        - curl
-        - ${{package.name}}-webapps
-        - openjdk-8-jre
-        - tomcat-native
-    environment:
-      LD_LIBRARY_PATH: "/usr/lib/tomcat-native"
-  pipeline:
-    - name: Test tomcat with java 8
-      uses: test/daemon-check-output
-      with:
-        setup: |
-          #!/bin/sh -ex
-          cp /usr/share/tomcat/webapps.dist/docs/appdev/sample/sample.war /usr/share/tomcat/webapps/
-        start: "env JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk /usr/share/tomcat/bin/catalina.sh run"
-        timeout: 30
-        expected_output: |
-          Tomcat/${{package.version}}
-          JVM.Version.*1.8
-          Deploying.*sample.war
-          Server startup in
-        post: |
-          #!/bin/sh -e
-          url=http://localhost:8080/sample/
-          echo "testing $url"
-          response=$(curl -s "$url") || {
-            echo "curl $url failed $?"
-            exit 1
-          }
-          expected="Sample.*Hello.*World.*Application"
-          echo "$response" | grep -q "$expected" || {
-            echo "response from $url did not contain \"$expected\""
-            echo "response: $response"
-            exit 1
-          }
-          echo "found \"$expected\" in output of curl $url"
+          # This includes the manager and host-manager apps.
+          # The apps are not directly usable without copying into the webapps directory.
+          # See https://github.com/docker-library/tomcat/pull/181 for more context.
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/webapps.dist
+          rm -rf output/build/webapps/examples
+          cp -r output/build/webapps/* ${{targets.contextdir}}/usr/share/tomcat/webapps.dist/
+      - name: Test tomcat with OpenJDK ${{range.key}}
+        uses: test/daemon-check-output
+        with:
+          setup: |
+            #!/bin/sh -ex
+            rm -rf /usr/share/tomcat/*
+            mkdir -p /usr/share/tomcat
+            cp -rf ${{targets.contextdir}}/usr/share/tomcat/* /usr/share/tomcat
+            cp /usr/share/tomcat/webapps.dist/docs/appdev/sample/sample.war /usr/share/tomcat/webapps/
+          start: |
+            sh -c "
+            if [[ "${{range.key}}" == "8" ]]; then
+              export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
+            else
+              export JAVA_HOME=/usr/lib/jvm/java-${{range.key}}-openjdk
+            fi
+            export LD_LIBRARY_PATH=/usr/lib/tomcat-native
+            /usr/share/tomcat/bin/catalina.sh run
+            "
+          timeout: 30
+          expected_output: |
+            Tomcat/${{package.version}}
+            JVM.Version
+            Deploying.*sample.war
+            Server startup in
+          post: |
+            #!/bin/sh -e
+            url=http://localhost:8080/sample/
+            echo "testing $url"
+            response=$(curl -s "$url") || {
+              echo "curl $url failed $?"
+              exit 1
+            }
+            expected="Sample.*Hello.*World.*Application"
+            echo "$response" | grep -q "$expected" || {
+              echo "response from $url did not contain \"$expected\""
+              echo "response: $response"
+              exit 1
+            }
+            echo "found \"$expected\" in output of curl $url"
 
 update:
   enabled: true
