tritonserver-backend-pytorch-cuda-13.0: remove cruft
The build system installs a bunch of cruft that should really be
supplied by other packages, or none at all. A lot of it is general
tritonserver stuff that would be best provided by the tritonserver
packages themselves. Some of it just shouldn't be installed at all,
such as the GTest cmake files.

I use case statements here so that we can have an explicit in/out
decision for all installed files. If new files get added upstream,
the build will fail so that we can make an in/out decision on those
new files.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

diff --git a/tritonserver-backend-pytorch-cuda-13.0.yaml b/tritonserver-backend-pytorch-cuda-13.0.yaml
--- a/tritonserver-backend-pytorch-cuda-13.0.yaml
+++ b/tritonserver-backend-pytorch-cuda-13.0.yaml
@@ -86,8 +86,53 @@ pipeline:
 
   - uses: cmake/install
 
-  - name: Remove tritonserver core headers
-    runs: rm -r "${{targets.contextdir}}/opt/tritonserver/include/triton/core/"
+  - name: "Remove extraneous files"
+    runs: |
+      cd ${{targets.contextdir}}/opt/tritonserver
+      for file in *; do
+        case "$file" in
+          backends|lib)
+            continue
+            ;;
+          bin|include)
+            rm -rf "$file"
+            ;;
+          *)
+            echo "ERROR: Unexpected file $(pwd)/$file" 1>&2
+            exit 1
+            ;;
+        esac
+      done
+      cd ${{targets.contextdir}}/opt/tritonserver/lib
+      for file in *; do
+        case "$file" in
+          cmake)
+            continue
+            ;;
+          *.a|pkgconfig|stubs)
+            rm -rf "$file"
+            ;;
+          *)
+            echo "ERROR: Unexpected file $(pwd)/$file" 1>&2
+            exit 1
+            ;;
+        esac
+      done
+      cd ${{targets.contextdir}}/opt/tritonserver/lib/cmake
+      for file in *; do
+        case "$file" in
+          TritonPyTorchBackend)
+            continue
+            ;;
+          GTest|TritonBackend|TritonCommon|TritonCore)
+            rm -rf "$file"
+            ;;
+          *)
+            echo "ERROR: Unexpected file $(pwd)/$file" 1>&2
+            exit 1
+            ;;
+        esac
+      done
 
 update:
   enabled: false
