feat: test secret syncing with vault in kwok

diff --git a/vault-secrets-operator.yaml b/vault-secrets-operator.yaml
--- a/vault-secrets-operator.yaml
+++ b/vault-secrets-operator.yaml
@@ -31,8 +31,16 @@ subpackages:
     description: "Compatibility package to place binaries in the location expected by upstream Dockerfile"
     pipeline:
       - runs: |
-          mkdir -p "${{targets.contextdir}}"/bin
-          ln -sf /usr/bin/vault-secrets-operator ${{targets.contextdir}}/bin/vault-secrets-operator
+          set -e
+          ln -sf /usr/bin/vault-secrets-operator "${{targets.contextdir}}"/vault-secrets-operator
+          mkdir "${{targets.contextdir}}"/scripts
+          cp -r chart/crds "${{targets.contextdir}}"/scripts/
+          ln -s /vault-secrets-operator "${{targets.contextdir}}"/scripts/upgrade-crds
+          mkdir "${{targets.contextdir}}"/licenses
+          cp LICENSE "${{targets.contextdir}}"/licenses/copyright.txt
+          mkdir -p "${{targets.contextdir}}"/usr/share/doc/${{package.name}}
+          cp LICENSE "${{targets.contextdir}}"/usr/share/doc/${{package.name}}/LICENSE.txt
+
 
 update:
   enabled: true
@@ -41,7 +49,91 @@ update:
     strip-prefix: v
 
 test:
+  environment:
+    contents:
+      packages:
+      - jq
+      - curl
+      - vault
+      - vault-secrets-operator-compat
+    environment:
+      VAULT_TOKEN: root
+      VAULT_ADDR: http://127.0.0.1:8200
+      VAULT_API_ADDR: http://127.0.0.1:8200
   pipeline:
-    - runs: |
-        vault-secrets-operator --help
-        vault-secrets-operator --version
+    - uses: test/kwok/cluster
+    - name: Install, configure, and add a secret to vault
+      runs: |
+        set -e
+        vault server -dev -dev-root-token-id $VAULT_TOKEN -dev-listen-address="0.0.0.0:8200" &
+        sleep 3s # vault startup
+        vault auth enable approle
+        vault secrets enable -path=kvv2 kv-v2
+        vault policy write webapp - <<EOF
+        path "kvv2/data/webapp/config" {
+          capabilities = ["read", "list", "update", "create"]
+        }
+        EOF
+        vault write auth/approle/role/role1 \
+          policies=webapp \
+          ttl=24h
+        vault kv put kvv2/webapp/config username="static-user" password="static-password"
+    - name: Setup and run vault-secrets-operator
+      runs: |
+        set -e
+        kubectl create ns vault-secrets-operator
+        kubectl create -f /scripts/crds/
+        export ROLE_ID=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/auth/approle/role/role1/role-id | jq -r .data.role_id)
+        export SECRET_ID=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" --request POST  $VAULT_ADDR/v1/auth/approle/role/role1/secret-id | jq -r .data.secret_id)
+        kubectl create secret -n default generic role-secret --from-literal=id=$SECRET_ID
+        cat <<-EOF | kubectl apply -f -
+          apiVersion: secrets.hashicorp.com/v1beta1
+          kind: VaultStaticSecret
+          metadata:
+            name: vault-kv-app
+            namespace: default
+          spec:
+            type: kv-v2
+            mount: kvv2
+            path: webapp/config
+            destination:
+              name: secretkv
+              create: true
+            refreshAfter: 1s
+            vaultAuthRef: static-auth
+        EOF
+        cat <<-EOF | kubectl apply -f -
+          apiVersion: secrets.hashicorp.com/v1beta1
+          kind: VaultConnection
+          metadata:
+            name: default
+            namespace: default
+          spec:
+            address: $VAULT_ADDR
+            skipTLSVerify: true
+        EOF
+        cat <<-EOF | kubectl apply -f -
+          apiVersion: secrets.hashicorp.com/v1beta1
+          kind: VaultAuth
+          metadata:
+            name: static-auth
+            namespace: default  
+          spec:
+            method: appRole  
+            appRole:
+              roleId: $ROLE_ID 
+              secretRef: role-secret
+            vaultConnectionRef: default
+            mount: approle
+        EOF
+        /vault-secrets-operator -kubeconfig /root/.kube/config -leader-elect=false &
+        sleep 3s # vault-secrets-operator startup and secret syncing
+        username=$(kubectl get secret secretkv -n default -o jsonpath='{.data.username}' | base64 -d)
+        password=$(kubectl get secret secretkv -n default -o jsonpath='{.data.password}' | base64 -d)
+
+        if [[ "$username" == "static-user" && "$password" == "static-password" ]]; then
+          echo "Secret found! Test is successful"
+        else
+          echo "Secret values do not match. Test failed."
+          exit 1
+        fi
