Added patches for hickory to prevent ring being pulled in unintentionally and unnecessarily

diff --git a/ztunnel-fips-1.26.yaml b/ztunnel-fips-1.26.yaml
--- a/ztunnel-fips-1.26.yaml
+++ b/ztunnel-fips-1.26.yaml
@@ -38,11 +38,35 @@ pipeline:
       tag: ${{package.version}}
       expected-commit: 2f601957bd172b34990612f4d8f847cadf4e880d
 
-  - uses: rust/cargobump
+  # Since hickory 0.25 now always pulls in the "ring" dependency, we need to edit the Cargo.toml
+  # files of several hickory crates to prevent this. Essentially, hickory client/resolver/server all
+  # import hickory-proto, which optionally requires ring by default. The patches prevent this.
+  - name: "Make sure upstream hasn't updated hickory-dns upstream without us realizing it, which could invalidate our patches"
+    runs: |
+      if [ "$(grep 'hickory-' Cargo.toml | grep -c '0.25')" -ne 4 ]; then
+        echo "Error: Hickory may have been updated. Please validate the patches for correctness and fix this check."
+        exit 1
+      fi
+
+  - uses: patch
+    with:
+      patches: hickory-patch-1.patch
+
+  - uses: git-checkout
+    with:
+      repository: https://github.com/hickory-dns/hickory-dns
+      tag: v0.25.1
+      expected-commit: 9cf275f750968c1612d63d585398734ae4a1b50b
+      destination: hickory-dns
+
+  - working-directory: hickory-dns
+    uses: patch
+    with:
+      patches: ../hickory-patch-2.patch
 
   # mitigate GHSA-2gh3-rmm4-6rq5
   # created upstream PR to address pprof issue https://github.com/tikv/pprof-rs/pull/264
-  # this needs to be removed once upstream fixes or merges PR
+  # this needs to be removed once pprof fixes or merges this PR, and ztunnel updates the version
   - runs: |
       sed -i 's|pprof = { version = "0.14", features = \["protobuf", "protobuf-codec", "criterion"\] }|pprof = { git = "https://github.com/kbsteere/pprof-rs.git", branch = "bump-protobuf-version-3.x", version = "0.14.0", features = ["protobuf", "protobuf-codec", "criterion"] }|' Cargo.toml
 
