cloud-ssh-keys-fetcher - support EC2 IMDSv2 (#12414)
* cloud-ssh-keys-fetcher - support EC2 IMDSv2

See doc at [1].
If an instance is created with IMDSv2 only, then the caller
is required to get a token to interact with the web service.
The IMDSv1 is token optional, so this is backwards compatible
with IMDSv1 also.

--
[1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

* Add usage, use umask, support '-' to mean stdout

diff --git a/cloud-ssh-keys-fetcher/cloud-ssh-keys-fetcher b/cloud-ssh-keys-fetcher/cloud-ssh-keys-fetcher
--- a/cloud-ssh-keys-fetcher/cloud-ssh-keys-fetcher
+++ b/cloud-ssh-keys-fetcher/cloud-ssh-keys-fetcher
@@ -1,13 +1,21 @@
 #!/bin/sh
 # shellcheck disable=SC2162,SC3043
-#
+
 read_info() {
-    local idd="/sys/class/dmi/id"
+    local idd="/sys/class/dmi/id" fails=""
+
+    # this is redirected to silence errors
     {
-    read PRODUCT_NAME < "$idd/product_name"
-    read PRODUCT_SERIAL < "$idd/product_serial"
-    read CHASSIS_ASSET < "$idd/chassis_asset_tag"
+    read PRODUCT_NAME < "$idd/product_name" ||
+        fails="$fails $idd/product_name"
+    read PRODUCT_SERIAL < "$idd/product_serial" ||
+        fails="$fails $idd/product_serial"
+    read CHASSIS_ASSET < "$idd/chassis_asset_tag" ||
+        fails="$fails $idd/chassis_asset_tag"
     } >/dev/null 2>&1
+    [ -z "$fails" ] && return 0
+    stderr "failed reading info from ${fails# }"
+    return 1
 }
 
 get_cloud() {
@@ -21,45 +29,131 @@ get_cloud() {
     return 0
 }
 
-fail() { echo "FATAL:" "$@"; exit 1; }
+stderr() { echo "$@" 1>&2; }
+fail() { stderr "FATAL:" "$@"; exit 1; }
 
-keyd="/root/.ssh"
-akeys="$keyd/authorized_keys"
+ec2md_setup() {
+    [ -n "$EC2MD_TOK" ] && [ -n "$EC2MD_URL" ] && return 0
+    local tok="" ttl=120
+    local tokurls="http://169.254.169.254:80"
+    tokurls="$tokurls http://[fd00:ec2::254]:80"
+    for tokurl in $tokurls; do
+        tok=$(curl --fail --max-time 5 --silent \
+                -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: $ttl" \
+                "${tokurl}/latest/api/token") || continue
+        [ -n "$tok" ] && url="$tokurl" && break
+    done
+    if [ -z "$url" ]; then
+        stderr "could not get a token on ec2 from $tokurls"
+        return 1
+    fi
+    EC2MD_TOK="$tok"
+    EC2MD_URL="$url"
+}
 
-read_info
-cloud=$(get_cloud)
-if [ -z "$cloud" ]; then
-    echo "unknown platform"
-    echo "product=\"$PRODUCT_NAME\" serial=\"$PRODUCT_SERIAL\"" \
-        "asset=\"$CHASSIS_ASSET\""
+ec2md_fetch() {
+    ec2md_setup || return 1
+    local path="$1" rc=0
+    local url="$EC2MD_URL/$path" tok="$EC2MD_TOK"
+    curl --silent --fail \
+        -H "X-aws-ec2-metadata-token: $tok" "$url" && return 0
+    rc=$?
+    stderr "ec2md_fetch failed [$rc] on '$url'"
+    return 1
+}
+
+ec2dump_keys() {
+    local out="" num="" tok="" ver="2024-04-11"
+    # index shows newline separated items '0=name\n1=name\n'
+    # get the index and then loop over items.
+    out=$(ec2md_fetch "$ver/meta-data/public-keys") || {
+        stderr "failed to list ec2 public-keys"
+        return 1
+    }
+    for tok in ${out}; do
+        num=${tok%%=*}
+        ec2md_fetch "$ver/meta-data/public-keys/$num/openssh-key" || {
+            stderr "failed to retrieve public key '$num' for $tok"
+            return 1
+        }
+    done
+    return 0
+}
+
+Usage() {
+    cat <<EOF
+Usage: ${0#*/} [outfile]
+
+    pull keys from cloud platform and write to outfile.
+    outfile defaults to /root/.ssh/authorized_keys
+EOF
+}
+
+if [ "$1" = "-h" -o "$1" = "--help" ]; then
+    Usage
     exit 0
 fi
 
+if [ -n "$CLOUD_PLATFORM" ]; then
+    cloud="$CLOUD_PLATFORM"
+else
+    read_info || fail "reading platform failed (sudo?)"
+    cloud=$(get_cloud)
+    if [ -z "$cloud" ]; then
+        echo "unknown platform"
+        echo "product=\"$PRODUCT_NAME\" serial=\"$PRODUCT_SERIAL\"" \
+            "asset=\"$CHASSIS_ASSET\""
+        exit 0
+    fi
+fi
 
-mkdir -p "$keyd" || fail "failed to create $keyd"
-chmod 0700 "$keyd" || fail "failed to chmod $keyd"
-touch "$akeys" || fail "failed creating $akeys"
-chmod 0600 "$akeys" || fail "failed to chmod $akeys"
+akeys="$1"
+if [ -z "$akeys" ]; then
+    akeys=$(echo ~/.ssh/authorized_keys)
+fi
 
-echo "Fetching keys on $cloud"
+keyd="."
+if [ "$akeys" != "-" ]; then
+    keyd=$(dirname "$akeys") || fail "failed getting dirname for '$akeys'"
+fi
+
+umask 077 || fail "failed setting umask"
+
+tmpf=$(mktemp) || fail "failed to create tmpfile"
+trap "rm -f '$tmpf'" EXIT
+
+if [ ! -d "$keyd" ]; then
+    mkdir "$keyd" || fail "failed to create directory '$keyd'"
+fi
+
+
+stderr "Fetching keys on $cloud"
 case "$cloud" in
     GCE)
         url="http://metadata.google.internal/computeMetadata/v1/instance/attributes/ssh-keys"
         out=$(curl --fail -H "Metadata-Flavor: Google" "$url") ||
             fail "failed retrieving keys on $cloud"
-        printf "%s" "$out" | cut -d':' -f2- > "$akeys"
+        printf "%s" "$out" | cut -d':' -f2- > "$tmpf"
         ;;
     Azure)
         local url="http://169.254.169.254/metadata/instance/compute/publicKeys?api-version=2021-02-01"
         out=$(curl --fail -H "Metadata: true" "$url") ||
             fail "failed retrieving keys on $cloud"
-        printf "%s" "$out" | cut -d':' -f2 | cut -d'"' -f2 > "$akeys"
+        printf "%s" "$out" | cut -d':' -f2 | cut -d'"' -f2 > "$tmpf"
         ;;
     EC2)
-        url="http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key"
-        out=$(curl --fail "$url")
-        fail "failed retrieving keys on $cloud"
-        printf "%s" "$out" > "$akeys"
+        ec2dump_keys > "$tmpf"
         ;;
-    *) fail "unknown cloud \"$cloud\"";;
+    *) fail "unsupported cloud \"$cloud\"";;
 esac
+
+if [ "$akeys" != "-" ]; then
+    exec > "$akeys" || fail "failed writing to $akeys"
+fi
+
+num=0
+while read line; do
+    printf "%s\n" "$line"
+    num=$((num+1))
+done < "$tmpf"
+stderr "Wrote $num keys from $cloud to $akeys"
