vms-test: test-ecs: refactor CloudFormation output validation
The number of CloudFormation stack outputs are going to grow. The
current approach to output validation doesn't scale well, and is not
even as helpful as it could be. Replace it with specific error messages.

Signed-off-by: Markus Boehme <markus.boehme@chainguard.dev>

diff --git a/vms-test/helpers/test-ecs b/vms-test/helpers/test-ecs
--- a/vms-test/helpers/test-ecs
+++ b/vms-test/helpers/test-ecs
@@ -227,12 +227,15 @@ cluster_resources() {
         cloudformation_output InstanceProfileName
     )
 
-    if [ -z "$vpc_id" ] || [ -z "$subnet_id" ] || [ -z "$sg_id" ] || [ -z "$profile_name" ]; then
-        stderr 'Failed to get all required stack outputs:'
-        stderr "                 VPC ID: $vpc_id"
-        stderr "              Subnet ID: $sg_id"
-        stderr "      Security Group ID: $sg_id"
-        stderr "  Instance Profile Name: $profile_name"
+    local errors=()
+    [ -n "$vpc_id" ]         || errors+=( 'VPC ID is missing' )
+    [ -n "$subnet_id" ]      || errors+=( 'Subnet ID is missing' )
+    [ -n "$sg_id" ]          || errors+=( 'Security Group ID is missing' )
+    [ -n "$profile_name" ]   || errors+=( 'Instance Profile Name is missing' )
+
+    if [ "${#errors[@]}" -ne 0 ]; then
+        stderr "Failed to get required stack outputs:"
+        stderr "$(printf "  %s\n" "${errors[@]}")"
         return 1
     fi
 
