Implement test configurations for qemu (#372)

diff --git a/vms-test/helpers/test-wolfi-vm b/vms-test/helpers/test-wolfi-vm
--- a/vms-test/helpers/test-wolfi-vm
+++ b/vms-test/helpers/test-wolfi-vm
@@ -32,10 +32,6 @@ cleanup() {
     [ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
 }
 
-cleanup_qemu() {
-    [ -z "$RUNNERPID" ] || kill "$RUNNERPID"
-    cleanup
-}
 
 log() {
     local now=""
@@ -107,98 +103,205 @@ yqassert() {
 }
 
 test_qemu() {
-    RUNNERPID=""
     local wolfivmd="$1" outd="$2" arch="" rund="" key="" vmname
     local runner="${TOP_D}/runner/qemu"
     shift 2
-    local vmnames=generic arches=""
+    local arches=""
     arches=( "$@" )
 
     TEMP_D=$(mktemp -d) || return
-    trap cleanup_qemu EXIT
 
     rund="$TEMP_D/run"
     mkdir "$rund" || return
-
-    log "making builder/ovmf-<arch>.fd for ${arches[*]}"
-    for arch in "${arches[@]}"; do
-        rq make -C "$wolfivmd" "builder/ovmf-$arch.fd" || {
-            stderr "failed creating builder/ovmf-$arch in $wolfivmd"
-            return 1
-        }
-    done
 
     known_hosts="$rund/known_hosts"
     key="$rund/id_ed25519"
     rq ssh-keygen -t ed25519 -N '' -f "$key" ||
         { stderr "failed creating ssh key"; return 1; }
 
-    local vmd="" tfile="" tname="" vfails="" voutd="" fails=""
+    local vmnames="" vmoutd="" vmname="" vfails="" fails="" testconfig="" vmconfigs="" user="" num_vmconfigs=""
     for arch in "${arches[@]}"; do
-        for vmname in $vmnames; do
+        for vmoutd in "$wolfivmd/output/$arch/"*; do
+            vmname="${vmoutd##*/}"
             vfails=""
-            voutd="$outd/$arch/$vmname"
-            vmd="$rund/$arch/$vmname"
-            mkdir -p "$voutd" "$vmd" || { stderr "failed creating dir"; return 1; }
-
-            vr "$runner" create --fwcode="$wolfivmd/builder/ovmf-$arch.fd" \
-                "$vmd" "$wolfivmd/output/$arch/generic/disk.raw" || {
-                    stderr "failed $runner create";
-                    vfails="$arch-$vmname/create"
-                    continue
-                }
-
-            set -- "$runner" start "--arch=$arch" --public-key="$key.pub" "$vmd"
-            log "starting $*"
-            "$@" > "$voutd/vm-start.log" 2>&1 &
-            RUNNERPID=$!
-
-            vr "$runner" --timeout="${WAIT_SSH_TIMEOUT}" wait-for-ssh "$vmd" \
-                >> "$known_hosts" || {
-                stderr "failed runner wait-for-ssh $arch-$vmname"
-                vfails="$vfails $arch-$vmname/wait-for-ssh"
-                if [ ! -f "$vmd/ttyS0.log" ]; then
-                    stderr "[$arch-$vmname] FATAL wait-for-ssh timeout." \
-                        "console log missing."
-                else
-                    sed -e 's,^,> ,' "$vmd/ttyS0.log" 2>&1
-                    stderr "[$arch-$vmname] FATAL wait-for-ssh timeout." \
-                        "console log above"
-                fi
+            testconfig="$wolfivmd/configs/$vmname/test.yaml"
+            [ -f "$testconfig" ] || {
+                vfails="$arch-$vmname/missing-test-config"
+                log "finished $arch-$vmname FAIL - $vfails"
+                fails="${fails+$fails }$vfails"
+                continue
+            }
+            yqassert "1" -re 'explode(.) | .version' "$testconfig" || {
+                vfails="$arch-$vmname/version-mismatch"
+                log "finished $arch-$vmname FAIL - $vfails"
+                fails="${fails+$fails }$vfails"
+                continue
+            }
+            yqassert "qemu" -re 'explode(.) | .cloud' "$testconfig" || {
+                vfails="$arch-$vmname/cloud-mismatch"
+                log "finished $arch-$vmname FAIL - $vfails"
+                fails="${fails+$fails }$vfails"
+                continue
+            }
+            # convert to json because bash mangles yaml
+            vmconfigs=$(yq -o json -re "explode(.) | .vmconfigs.$arch" "$testconfig") || {
+                vfails="$arch-$vmname/read-vmconfigs"
+                log "finished $arch-$vmname FAIL - $vfails"
+                fails="${fails+$fails }$vfails"
+                continue
+            }
+            user=$(yq -re "explode(.) | .data.vmuser" "$testconfig") || { log "using default user 'linky'"; user="linky"; }
+            num_vmconfigs=$(echo "$vmconfigs" | jq 'length') || {
+                vfails="$arch-$vmname/malformed-vmconfigs"
+                log "finished $arch-$vmname FAIL - $vfails"
+                fails="${fails+$fails }$vfails"
                 continue
             }
 
-            for tfile in "${TOP_D}/test/$arch"/*/*; do
-                tname=${tfile##*/}
-                vrl "$voutd/test-$tname" "$runner" run-remote \
-                    --private-key="$key" --file="$tfile" "$vmd" --known-hosts="$known_hosts" \
-                       -- -test.v -metric-tags "arch:$arch,$METRIC_TAGS" ||
-                       vfails="$vfails $arch-$vmname/test-$tname"
-                if test_emits_metrics "$tfile"; then
-                    "$runner" ssh --private-key="$key" --known-hosts="$known_hosts" "$vmd" \
-                        "cat $METD/$tname" >  "$voutd/$tname-metrics.json" ||
-                        vfails="$vfails $arch-$vmname/$tname-metrics"
+            log "starting $vmname with arch $arch"
+
+            local i="" fwcode="" fwcode_relative="" vmconfig_name="" named_tests="" test_groups="" vm_testd="" voutd="" runnerpid="" group="" tname="" vm_testd="" vmd="" launcher="" runnerpid=""
+            for i in $(seq 0 $((num_vmconfigs-1))); do
+
+                fwcode_relative=$(echo "$vmconfigs" | jq -re ".[$i].fwcode") || {
+                    vfails="$vfails $arch-$vmname/no-fwcode-defined"
+                    continue
+                }
+		fwcode=$(dirname "$testconfig")/"$fwcode_relative"
+                [ -f "$fwcode" ] || {
+                    vfails="$vfails $arch-$vmname/missing-fwcode-file"
+                    continue
+                }
+                vmconfig_name=$(echo "$vmconfigs" | jq -re ".[$i].name" 2>/dev/null) || vmconfig_name=$(basename "$fwcode")
+                named_tests=$(echo "$vmconfigs" | jq -re ".[$i].tests[].name | select (. != null)" 2>/dev/null) || named_tests=""
+                test_groups=$(echo "$vmconfigs" | jq -re ".[$i].tests[].group | select (. != null)" 2>/dev/null) || test_groups=""
+                for group in $test_groups; do
+                    for tname in "$TOP_D/pkg/test/$group/"*; do
+                        named_tests="$named_tests $group/$(basename "$tname")"
+                    done
+                done
+                if [ -z "$named_tests" ]; then
+                    vfails="$vfails $arch-$vmname/$vmconfig_name/no-tests-defined"
+                    continue
                 fi
+
+                vm_testd="$TEMP_D/$arch/$vmname/$vmconfig_name"
+                rq mkdir -p "$vm_testd" || {
+                    stderr "failed creating vm test dir $vm_testd"
+                    return 1
+                }
+                vmd="$rund/$arch/$vmname/$vmconfig_name"
+                rq mkdir -p "$vmd" || {
+                    stderr "failed creating vmdir $vmd"
+                    return 1
+                }
+                voutd="$outd/$arch/$vmname/$vmconfig_name"
+                rq mkdir -p "$voutd" || {
+                    stderr "failed creating vm out dir $voutd"
+                    return 1
+                }
+
+                vr "$runner" create --fwcode="$fwcode" \
+                    "$vmd" "$wolfivmd/output/$arch/generic/disk.raw" || {
+                        stderr "failed $runner create";
+                        vfails="$arch-$vmname/$vmconfig_name/create"
+                        continue
+                }
+
+                if launcher=$(echo "$vmconfigs" | jq -re ".[$i].launch"); then
+                    local test_config_dir=""
+                    test_config_dir=$(dirname "$testconfig") || {
+                        stderr "failed to get dir of $testconfig"
+                        continue
+                    }
+                    launcher="$test_config_dir/$launcher"
+                else
+                    log "launch option is unspecified for $vmconfig_name, using default runner"
+                    launcher=("$runner" "start")
+                fi
+                # Start VM
+                set -- env RUNNER="$runner" "${launcher[@]}" "--arch=$arch" --public-key="$key.pub" "$vmd"
+                log "starting $*"
+                "$@" > "$voutd/vm-start.log" 2>&1 &
+                runnerpid=$!
+
+                vr "$runner" --timeout="${WAIT_SSH_TIMEOUT}" wait-for-ssh "$vmd" \
+                    >> "$known_hosts" || {
+                    stderr "failed runner wait-for-ssh $arch-$vmname-$vmconfig_name"
+                    vfails="$vfails $arch-$vmname/$vmconfig_name/wait-for-ssh"
+                    if [ ! -f "$vmd/ttyS0.log" ]; then
+                        stderr "[$arch-$vmname-$vmconfig_name] FATAL wait-for-ssh timeout." \
+                            "console log missing."
+                    else
+                        sed -e 's,^,> ,' "$vmd/ttyS0.log" 2>&1
+                        stderr "[$arch-$vmname-$vmconfig_name] FATAL wait-for-ssh timeout." \
+                            "console log above"
+                    fi
+                    kill "$runnerpid"
+                    continue
+                }
+
+                # Run tests 
+                for tid in $named_tests; do
+                    case "$tid" in
+                        *"/"*)
+                            tname="${tid##*/}"
+                            tgroup="${tid%%/*}"
+                            tname_pretty="$tgroup-$tname"
+                            tfile="$TOP_D/test/$arch/$tgroup/$tname"
+                            ;;
+                        *)
+                            tname="$tid"
+                            tgroup=""
+                            tname_pretty="$tname"
+                            location=$(dirname "$testconfig")"/"$(echo "$vmconfigs" | jq -re ".[$i].tests[] | select(.name==\"$tname\").location") || {
+                                vfails="$vfails $arch/$vmname/$vmconfig_name/missing-test-location-$tname"
+                                continue
+                            }
+                            goarch=$(goarch "$arch") || {
+                                vfails="$vfails $arch/$vmname/$vmconfig_name/invalid-test-arch-$tname"
+                                continue
+                            }
+                            tfile="$vm_testd/$tname"
+                            rq env GOOS="linux" GOARCH="$goarch" go test -C "$location" -c -o "$tfile" -tags vmtest || {
+                                vfails="$vfails $arch/$vmname/$vmconfig_name/compile-test-$tname"
+                                continue
+                            }
+                            ;;
+                    esac
+
+                    test_user=$(echo "$vmconfigs" | jq -re ".[$i].vmuser" 2>/dev/null) || test_user="$user"
+                    vrl "$voutd/test-$tname" "$runner" run-remote \
+                        --private-key="$key" --file="$tfile" "$vmd" --known-hosts="$known_hosts" \
+                           -- -test.v -metric-tags "arch:$arch,$METRIC_TAGS" ||
+                           vfails="$vfails $arch-$vmname/test-$tname"
+                    if test_emits_metrics "$tfile"; then
+                        "$runner" ssh --private-key="$key" --known-hosts="$known_hosts" "$vmd" \
+                            "cat $METD/$tname" >  "$voutd/$tname-metrics.json" ||
+                            vfails="$vfails $arch-$vmname/$tname-metrics"
+                    fi
+                done
+
+                kill "$runnerpid"
+                wait "$runnerpid"
+
+                if [ ! -f "$vmd/ttyS0.log" ]; then
+                    vfails="$vfails $arch-$vmname/$vmconfig_name/console-log"
+                    stderr "$vmd/ttyS0.log did not exist"
+                elif ! cp "$vmd/ttyS0.log" "$voutd/console.log"; then
+                    vfails="$vfails $arch-$vmname/$vmconfig_name/console-log"
+                    stderr "failed copy of $vmd/ttyS0.log"
+                fi
+
+                vfails=${vfails# }
+                if [ -z "$vfails" ]; then
+                    log "finished $arch/$vmname/$vmconfig_name PASS"
+                else
+                    log "finished $arch/$vmname/$vmconfig_name FAIL - $vfails"
+                fi
+
             done
 
-            kill "$RUNNERPID"
-            wait "$RUNNERPID"
-            RUNNERPID=""
-
-            if [ ! -f "$vmd/ttyS0.log" ]; then
-                vfails="$vfails $arch-$vmname/console-log"
-                stderr "$vmd/ttyS0.log did not exist"
-            elif ! cp "$vmd/ttyS0.log" "$voutd/console.log"; then
-                vfails="$vfails $arch-$vmname/console-log"
-                stderr "failed copy of $vmd/ttyS0.log"
-            fi
-
-            vfails=${vfails# }
-            if [ -z "$vfails" ]; then
-                log "finished $arch/$vmname PASS"
-            else
-                log "finished $arch/$vmname FAIL - $vfails"
-            fi
         done
         fails="${fails:+$fails }$vfails"
     done
