Fix/separate builder (#49)
* fix grab-pkg-artifact to pass --arch flag through to fetch-pkg
  
  This was not getting the correct arch kernel as it
  was not telling fetch-pkg what arch to get.

* Move the builder (the disk creation) into tools/tar2efi-disk
  
  This moves a bunch of stuff that was in the makefile into
  a tools/tar2efi, which makes it easier to do things
  as shell is easier to do conditionals than make.
  
  The point of tar2efi-disk is simply to do the conversion.
  
  A couple small changes in the vm -
   * we pass through environment variables now (so we can specify
     DEBUG=true)
   * copy the script to a temp dir to execute it.
     the primary value here is we can write a result to that
     dir as well and only do 1 plan9 mount. (the script dir)
     and the temp dir can be safely writable
   * make mkvm's runner write the result rather than
     install-target-disk
  
  TODO:
   * enable/disable acceleration in tar2efi-disk's invocation
     of qemu.  The intent of --accel is to allow turning this
     on or off.

* Move size calculation to tar2efi-disk
  
  you can play with size calculation via
  
      tar2efi-disk fitsize your/image.tar
  
  currently this does:
    workstation - 6G
    generic - 2G

diff --git a/tools/grab-pkg-artifact b/tools/grab-pkg-artifact
--- a/tools/grab-pkg-artifact
+++ b/tools/grab-pkg-artifact
@@ -108,13 +108,14 @@ main() {
     local apk="${TEMP_D}/${package#*/}-$fullver.apk"
     local tmpf="$outfile.$$"
 
-    fetch-pkg "--output=$apk" "$package" ||
+    fetch-pkg "--arch=$arch" "--output=$apk" "$package" ||
         fail "failed to download $package at $fullver"
 
     tmpf="$outfile.$$"
     tar -xzOf "$apk" "$extract_file" > "$tmpf" 2>/dev/null || {
         rm -f "$tmpf"
-        fail "failed extracting $extract_file from $package"
+        tar tvf "$apk" | sed 's,^,> ,' 2>&1
+        fail "failed extracting '$extract_file' from $package. see tar tvf above."
     }
 
     if [ ! -s "$tmpf" ]; then
