Make debug disk have 'rw' if the non-debug version has 'rw'. (#43)
linux kernel root= flip-flopped on presense of 'rw'. the debug version
didn't get updated. That meant that 'make debug-disk-generic' would
_not_ have 'rw' on it while the regular version would.

This is hacky, but we search for 'rw' from the main and then adjust the
debug entry to have it.

Long term solution is to have a debug package (or metadata package) that
does this and so we don't fish around and hackily build content during a
debug build process but rather just include debug packages.

diff --git a/tools/install-target-disk b/tools/install-target-disk
--- a/tools/install-target-disk
+++ b/tools/install-target-disk
@@ -1,5 +1,17 @@
 #!/bin/sh -ex
 
+_grep() {
+    set +x
+    local m="$1"; shift;
+    for f in "$@"; do
+        while read line ; do
+            case "$line" in
+                *$m*) echo "$f: $line"; continue;;
+            esac
+        done < "$f"
+    done
+}
+
 write_kernel_conf() {
     local rootd="$1" rootflag="" out="" ver="" opts="" fname="" kernel=""
     ( cd "$rootd/boot/efi" && find . -type f )
@@ -18,26 +30,29 @@ write_kernel_conf() {
     ver=${ver%/linux}
     rootflag="root=PARTUUID=33333333-3333-3333-3333-333333333333"
     opts="$rootflag systemd.debug-shell=ttyS1 console=ttyS0"
+
+    local rwflag="" ofname="boot/efi/loader/entries/chainguard-$ver.conf"
+    if [ ! -f "$rootd/$ofname" ]; then
+        echo "expected config file in $ofname was not found." 1>&2
+        return 1
+    else
+        local line=""
+        line=$(_grep "options * rw" "$rootd/$ofname")
+        if [ -n "$line" ]; then
+            rwflag="rw"
+        fi
+    fi
+
     fname="boot/efi/loader/entries/chainguard-$ver-debug.conf"
 
     cat > "$rootd/$fname" <<EOF || return 1
 title      Chainguard-debug
 version    $ver
 sort-key   0chainguard
-options    $opts
+options    $opts${rwflag:+ $rwflag}
 linux      $kernel
 EOF
 
-    _grep() {
-        local m="$1"; shift;
-        for f in "$@"; do
-            while read line ; do
-                case "$line" in
-                    *$m*) echo "$f: $line";;
-                esac
-            done < "$f"
-        done
-    }
     ( set +x;
       echo "=== /$fname =="
       sed 's,^,| ,' "$rootd/$fname"
