fix: hardened builder should also apply stig (#941)
This is why our builds are reporting bad stig coverage

Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

diff --git a/cgr-install/scripts/builder-default b/cgr-install/scripts/builder-default
--- a/cgr-install/scripts/builder-default
+++ b/cgr-install/scripts/builder-default
@@ -86,10 +86,13 @@ fi
 if [ "$cis" = "true" ]; then
     ln -sf /proc/self/fd /dev/fd ||
         fail "failed symlinking /dev/fd -> /proc/self/fd"
-    # Run CIS Hardening
-    # TODO: this is not reproducible yet
+    # Run CIS lv1 Hardening
     vr env SOURCE_DATE_EPOCH="$FROZEN_TIMESTAMP" \
         apply-hardening --profile=cis-level-1 --sysroot="${ROOT_DIR}" ||
+        fail "failed apply hardening"
+    # Run STIG Hardening
+    vr env SOURCE_DATE_EPOCH="$FROZEN_TIMESTAMP" \
+        apply-hardening --profile=stig --sysroot="${ROOT_DIR}" ||
         fail "failed apply hardening"
 fi
 
