cgr-install: relabel files with SELinux contexts quietly (#1174)
Relabel files with their appropriate SELinux contexts quietly during
build. Only emit verbose logs if the relabeling fails. Otherwise, build
logs are cluttered with thousands of lines of output with no value in
the happy path.

Signed-off-by: Markus Boehme <markus.boehme@chainguard.dev>

diff --git a/cgr-install/scripts/cgr-install b/cgr-install/scripts/cgr-install
--- a/cgr-install/scripts/cgr-install
+++ b/cgr-install/scripts/cgr-install
@@ -69,6 +69,16 @@ vr() {
     return $rc
 }
 
+# rq(cmd) - run cmd quietly unless it fails
+rq() {
+    local rc="" out=""
+    out=$("$@" 2>&1) && return 0
+    rc=$?
+    stderr "failed [$rc]: $*"
+    printf "%s\n" "$out" | sed -e 's,^,> ,' 1>&2
+    return "$rc"
+}
+
 ptdev() {
     local dev="$1" part="$2" delim=""
     for delim in p ""; do
@@ -875,7 +885,8 @@ adjust_var_run() {
 selinux_label() {
     local rootd="$1"
     if [ -e "$rootd/etc/selinux/targeted/contexts/files/file_contexts" ]; then
-        vr setfiles -v -m -r "$rootd" "$rootd/etc/selinux/targeted/contexts/files/file_contexts" "$rootd" ||
+        debug 1 "Relabeling $rootd"
+        rq setfiles -v -m -r "$rootd" "$rootd/etc/selinux/targeted/contexts/files/file_contexts" "$rootd" ||
             { stderr "failed running setfiles"; return 1; }
     fi
     return 0
