Get rid of scary warnings from hash-to-efi-sig-list
We would see this in logs:

    execute: hash-to-efi-sig-list /dev/null /output/secureboot/PK.esl
    Failed to get hash of /dev/null: 3

Those look like errors to humans and ai.

diff --git a/cgr-install/scripts/cgr-install b/cgr-install/scripts/cgr-install
--- a/cgr-install/scripts/cgr-install
+++ b/cgr-install/scripts/cgr-install
@@ -586,6 +586,19 @@ _uki_setup() {
     return 0
 }
 
+empty_sig_list() {
+    local out="$1"
+    # hash-to-efi-sig-list writes scary messages that look like failures:
+    #   Failed to get hash of /dev/null: 3
+    # so instead of running it, we collect its 76 byte output here. base64 is output from
+    #    $ hash-to-efi-sig-list /dev/null out.esl
+    #    $ base64 --wrap=74 out.esl
+    base64 -d > "$out" <<EOF
+JhbEwUxQkkCsqUH5NpNDKEwAAAAAAAAAMAAAAFCrXWBG4ABDq7Y92BDdiyMAAAAAAAAAAAAAAA
+AAAAAAAAAAAAAAAAAAAAAAAAAAAA==
+EOF
+}
+
 secureboot_setup() {
     # this expects to on a full 'bootd' and make changes to it (populating boot/loader/keys/auto)
     local bootd="$1" outd="$2"
@@ -598,9 +611,9 @@ secureboot_setup() {
     local GUID="c04269ed-5f3b-46df-ac37-95e3e70e4027"
 
     ## Empty key for PK, KEK, DBX
-    local ktype=""
+    local ktype="" out=""
     for ktype in PK KEK dbx; do
-        vr hash-to-efi-sig-list /dev/null "$outd/$ktype.esl" ||
+        empty_sig_list "$outd/$ktype.esl" ||
             { stderr "Failed creating empty sig list for $ktype"; return 1; }
     done
 
