Remove obsolete package linux-boot-configuration (#699)

diff --git a/iac/builder-debug.yaml b/iac/builder-debug.yaml
--- a/iac/builder-debug.yaml
+++ b/iac/builder-debug.yaml
@@ -229,6 +229,10 @@ cmd: |
   if [ -d "$root_dir/boot/efi/EFI" ]; then
      espmp="boot/efi"
   fi
+  if [ -e "$root_dir/boot/EFI" ] && [ -e "$root_dir/boot/efi" ]; then
+    echo "ERROR: installation has boot /boot/EFI and /boot/efi" 1>&2
+    exit 1
+  fi
   # First create directories
   find $root_dir/$espmp -type d -printf "%P\n" | sort | while read -r dir; do
       if [ -n "$dir" ]; then
