Feat/dmverity (#732)
Depends on:
- https://github.com/chainguard-dev/enterprise-packages/pull/34754
- https://github.com/chainguard-dev/enterprise-packages/pull/34769

This setup correctly dm-verity for the immutable runner
needs the other PR in order to enable needed modules for early dm-verity
initialization

Related: https://github.com/chainguard-dev/internal-dev/issues/8596

---------

Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

diff --git a/iac/builder-immutable.yaml b/iac/builder-immutable.yaml
--- a/iac/builder-immutable.yaml
+++ b/iac/builder-immutable.yaml
@@ -33,10 +33,13 @@ contents:
   # We mount the output 9p shared dir
   - mount
   # We need to run sysuser and systemctl on target root
-  - sed
+  - busybox
   - systemd-systemctl
   - systemd-sysusers-standalone
+  # Make commands reproducible
   - stampdalf
+  # veritysetup dm-verity
+  - cryptsetup
 
 entrypoint:
   command: /bin/bash
@@ -55,36 +58,51 @@ cmd: |
 
   FROZEN_TIMESTAMP=1744654025
 
+  ############################## DISK SETUP ###################################
   GPT_UUID=11111111-1111-1111-11111111111111111
   PT_UUID_EFI=22222222-2222-2222-2222-222222222222
   PT_UUID_ROOT=33333333-3333-3333-3333-333333333333
+  PT_UUID_DMVERITY=66666666-6666-6666-6666-666666666666
   FS_UUID_ROOT=44444444-4444-4444-4444-444444444444
   FS_UUID_EFI=55555555 # 32 bit int
+  FS_UUID_DMVERITY=77777777-7777-7777-7777-777777777777
   DISK_UUID=5A82A03F-386A-43C8-8DD5-DD0E5452A3F1
 
   # https://uapi-group.org/specifications/specs/discoverable_partitions_specification
   EFI_TYPE="c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
   ROOT_X86_64="4f68bce3-e8cd-4db1-96e7-fbcaf984b709"
   ROOT_ARM64="b921b045-1df0-41c3-af44-4c6f280d3fae"
+  DM_VERITY_X86_64="2c7357ed-ebd2-46d9-aec1-23d437ec2bf5"
+  DM_VERITY_ARM64="df3300ce-d69f-4c92-978c-9bfb0f38d820"
+  VERITY_SALT="85dafa347119380f271b1f90d07143e6"
 
   if [ "$(cat /output/buildArch)" = "x86_64" ]; then
       ROOT_TYPE="${ROOT_X86_64}"
+      DM_VERITY="${DM_VERITY_X86_64}"
   elif [ "$(cat /output/buildArch)" = "aarch64" ]; then
       ROOT_TYPE="${ROOT_ARM64}"
+      DM_VERITY="${DM_VERITY_ARM64}"
   fi
 
   [ -e "$tarball" ]
   [ -b "$disk" ]
 
   # Create a GPT parition table on our disk where the
-  # EFI System Partition (ESP) is 100M to hold the kernel,
+  # EFI System Partition (ESP) is 512M to hold the kernel,
   # systemd-boot, and a handful of configuration files.
   # The root partition will be the remainder of the disk.
   gib=$((1024 * 1024 * 1024))
   start=$((1024 * 1024 * 4)) # Start 4Mib for maximum alignment
   sectsize=512
+  #  4 MiB      510 MiB       510 MiB
+  # +---------+-------------+----------------------------------------------+
+  # | (Align) |     ESP     | Verity Hash |              Root              |
+  # +---------+-------------+----------------------------------------------+
+  # |         |             |             |
+  # 0       4 MiB        514 MiB        1 GiB
   sstart=$((start / sectsize))
-  efisize=$(((gib - start) / sectsize)) # make efisize 1GiB - startsize, so second part starts at 1GiB
+  efisize=$((((gib - start) / sectsize)/2))
+  veritysize=$((((gib - start) / sectsize)/2))
   sfdisk $disk << EOF
   label: gpt
   label-id: $GPT_UUID
@@ -92,15 +110,19 @@ cmd: |
   sector-size: $sectsize
 
   disk.raw1 : start=  $sstart, size=$efisize, type=$EFI_TYPE, uuid=$PT_UUID_EFI, name="ESP"
-  disk.raw2 : start=, size=, type=$ROOT_TYPE, uuid=$PT_UUID_ROOT, name="Chainguard", attrs="GUID:59"
+  disk.raw2 : start=, size=$veritysize, type=$DM_VERITY, uuid=$PT_UUID_DMVERITY, name="Chainguard-verity", attrs="GUID:60"
+  disk.raw3 : start=, size=, type=$ROOT_TYPE, uuid=$PT_UUID_ROOT, name="Chainguard", attrs="GUID:60"
   EOF
 
   # Reproducibility improvements, this way partition layout is reproducible
   sfdisk --disk-id $disk "$DISK_UUID"
 
   uefi_partition="${disk}1"
-  root_partition="${disk}2"
+  verity_partition="${disk}2"
+  root_partition="${disk}3"
+  ############################## DISK SETUP ###################################
 
+  ############################## UNPACK ROOTFS#################################
   # Create a scratch disk in /tmp where we unpack potentially
   # very large disks
   mkfs.xfs "${scratch}"
@@ -125,9 +147,9 @@ cmd: |
 
   # Remove included char devices that we dont need
   SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP stampdalf "$root_dir/dev" rm -rf $root_dir/dev/* $root_dir/dev/.*
+  ############################## UNPACK ROOTFS#################################
 
-  ############################################################################
-  ### Fix immutable VM situation ############################################
+  ############ IMMUTABLE VM SETUP #############################################
   ## We need ro flag at boot, this will remount root as rw, remove
   if [ ! -e "${root_dir}/etc/fstab" ]; then
     echo "/etc/fstab not included in base rootfs, continuing"
@@ -136,14 +158,6 @@ cmd: |
       stampdalf "$root_dir/etc" \
                 rm $root_dir/etc/fstab
   fi
-  # We need ro flag for our boot configuration and add
-  # chainguard.immutable=volatile
-  # to enable the overlayfs /etc and /var mounts
-  for entry in "$root_dir"/boot/loader/entries/chainguard-*; do
-    SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP \
-      stampdalf "$root_dir/boot/loader/entries" \
-                sed -i "s| rw | ro -- chainguard.immutable=volatile |g" "$entry"
-  done
 
   # To modify all our systemd units to already ship
   # a symlink to their target
@@ -154,59 +168,20 @@ cmd: |
   SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP \
     stampdalf "$root_dir/etc" \
               /usr/bin/systemd-sysusers --root=$root_dir
-  ############################################################################
-  ############################################################################
+  ############ IMMUTABLE VM SETUP #############################################
 
-  # Format our EFP System Partition with FAT32 (required)
-  # using invariant will make the partition reproducible
-  mkfs.vfat --invariant -i "$FS_UUID_EFI" -F 32 $uefi_partition
-
-  # Extract the boot directory from the tar, then populate
-  # our EFI partition.
-  # We will use mtools so we wont need to mount, this making the
-  # partition not reproducible
-  # configure mtools to correctly read out vfat partition
-  cat > /root/.mtoolsrc << EOF
-  drive c: file="$uefi_partition" partition=0 hidden=$sstart
-  EOF
-
-  # ESP mount point should be /boot, but old 'boot-installed' packages
-  # effectively expected it to be /boot/efi.  Those are identifyable
-  # by presence of /boot/efi/EFI rather than /boot/EFI.
-  espmp="boot"
-  if [ -d "$root_dir/boot/efi/EFI" ]; then
-     espmp="boot/efi"
-  fi
-  if [ -e "$root_dir/boot/EFI" ] && [ -e "$root_dir/boot/efi" ]; then
-    echo "ERROR: installation has boot /boot/EFI and /boot/efi" 1>&2
-    exit 1
-  fi
-  # First create directories
-  find $root_dir/$espmp -type d -printf "%P\n" | sort | while read -r dir; do
-      if [ -n "$dir" ]; then
-          MTOOLS_SKIP_CHECK=1 \
-              SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP \
-              TZ=UTC \
-              mmd -D o "c:/$dir"
-      fi
-  done
-  # Then copy all files
-  find $root_dir/$espmp -type f -printf "%P\n" | sort | while read -r file; do
-      MTOOLS_SKIP_CHECK=1 \
-          SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP \
-          TZ=UTC \
-          mcopy -o -p -m -Q "$root_dir/$espmp/$file" "c:/$file"
-  done
-
-  # Remove files in boot which were copied to ESP
-  SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP stampdalf "$root_dir/$espmp" rm -rf $root_dir/$espmp/*
-
+  ######################### POPULATE ROOTFS ##################################
   # Format our root partition with xfs
   FAKE_TIME="$(date -d @"$FROZEN_TIMESTAMP" +"%Y-%m-%d %H:%M:%S")"
   export LD_PRELOAD="/usr/lib/faketime/libfaketime.so.1"
   export FAKERANDOM_SEED="0x12345678DEADBEEF"
   export FAKETIME=$FAKE_TIME
   export NO_FAKE_STAT=1
+
+  mkdir /tmp/boot
+  SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP \
+    stampdalf "$root_dir" \
+              mv "$root_dir"/boot/* /tmp/boot/
 
   mkfs.xfs \
     -b size=4096 \
@@ -230,6 +205,115 @@ cmd: |
   # by default it will inherit whatever permission $root_dir will have
   # for consistency lets set it manually.
   xfs_db -x $root_partition -c "inode 128" -c "write core.mode 040755"
+  unset LD_PRELOAD
+
+  ######################### POPULATE ROOTFS ##################################
+  #
+  ######################### SETUP DM-VERITY ##################################
+  VERITY_VERSION=1
+  VERITY_HASH_ALGORITHM=sha256
+  # Here we need to use the block size chosen in sfdisk and mkfs.xfs, 512
+  VERITY_DATA_BLOCK_SIZE=512
+  VERITY_HASH_BLOCK_SIZE=512
+
+  veritysetup format \
+      --format "$VERITY_VERSION" \
+      --hash "$VERITY_HASH_ALGORITHM" \
+      --data-block-size "$VERITY_DATA_BLOCK_SIZE" \
+      --hash-block-size "$VERITY_HASH_BLOCK_SIZE" \
+      --salt="$VERITY_SALT" \
+      --uuid="$FS_UUID_DMVERITY" \
+      $root_partition $verity_partition | tee /tmp/verity.log
+
+  # The block size reported here, are of the size we decided at format time.
+  VERITY_DATA_512B_BLOCKS="$(grep "^Data blocks:" /tmp/verity.log | awk "{ print \$NF }")"
+  VERITY_ROOT_HASH="$(grep "^Root hash:" /tmp/verity.log | awk "{ print \$NF }")"
+
+  dm_verity_root="root,,,ro,0"
+  # Here we need to use 512 block size ALWAYS, so if in future we format to 4k
+  # we need to report it back to 512 blocks for it to work.
+  dm_verity_root="$dm_verity_root ${VERITY_DATA_512B_BLOCKS}"
+  dm_verity_root="$dm_verity_root verity"
+  dm_verity_root="$dm_verity_root ${VERITY_VERSION}"
+  dm_verity_root="$dm_verity_root PARTLABEL=Chainguard"
+  dm_verity_root="$dm_verity_root PARTLABEL=Chainguard-verity"
+  dm_verity_root="$dm_verity_root ${VERITY_DATA_BLOCK_SIZE}"
+  dm_verity_root="$dm_verity_root ${VERITY_HASH_BLOCK_SIZE}"
+  # here instead we just use the output of "Data Blocks:" in veritysetup
+  dm_verity_root="$dm_verity_root ${VERITY_DATA_512B_BLOCKS}"
+  dm_verity_root="$dm_verity_root 1"
+  dm_verity_root="$dm_verity_root ${VERITY_HASH_ALGORITHM}"
+  dm_verity_root="$dm_verity_root ${VERITY_ROOT_HASH}"
+  dm_verity_root="$dm_verity_root ${VERITY_SALT}"
+  dm_verity_root="$dm_verity_root 2"
+  dm_verity_root="$dm_verity_root restart_on_corruption"
+  dm_verity_root="$dm_verity_root ignore_zero_blocks"
+
+  # Double check we did things well
+  veritysetup verify \
+    "${root_partition}" \
+    "${verity_partition}" \
+    "${VERITY_ROOT_HASH}"
+
+  # We need ro flag for our boot configuration and add
+  # chainguard.immutable=volatile
+  # to enable the overlayfs /etc and /var mounts
+  for entry in /tmp/boot/loader/entries/chainguard-*; do
+    SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP \
+      stampdalf /tmp/boot/loader/entries \
+                sed -i "s| rw | ro |g" "$entry"
+    SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP \
+      stampdalf /tmp/boot/loader/entries \
+                sed -i "s| root=PARTLABEL=Chainguard | root=/dev/dm-0 rootwait raid=noautodetect dm-mod.create=\"$dm_verity_root\" |g" "$entry"
+    SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP \
+      stampdalf /tmp/boot/loader/entries \
+                sed -i "s/\(options.*\)$/\1 -- chainguard.immutable=volatile/" "$entry"
+    cat $entry
+  done
+  ######################### SETUP DM-VERITY ##################################
+
+  ######################### POPULATE BOOTFS ##################################
+  # Format our EFP System Partition with FAT32 (required)
+  # using invariant will make the partition reproducible
+  mkfs.vfat --invariant -i "$FS_UUID_EFI" -F 32 $uefi_partition
+
+  # Extract the boot directory from the tar, then populate
+  # our EFI partition.
+  # We will use mtools so we wont need to mount, this making the
+  # partition not reproducible
+  # configure mtools to correctly read out vfat partition
+  cat > /root/.mtoolsrc << EOF
+  drive c: file="$uefi_partition" partition=0 hidden=$sstart
+  EOF
+
+  # ESP mount point should be /boot, but old 'boot-installed' packages
+  # effectively expected it to be /boot/efi.  Those are identifyable
+  # by presence of /boot/efi/EFI rather than /boot/EFI.
+  espmp="boot"
+  if [ -d "/tmp/boot/efi/EFI" ]; then
+     espmp="boot/efi"
+  fi
+  if [ -e "/tmp/boot/EFI" ] && [ -e "/tmp/boot/efi" ]; then
+    echo "ERROR: installation has boot /boot/EFI and /boot/efi" 1>&2
+    exit 1
+  fi
+  # First create directories
+  find /tmp/$espmp -type d -printf "%P\n" | sort | while read -r dir; do
+      if [ -n "$dir" ]; then
+          MTOOLS_SKIP_CHECK=1 \
+              SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP \
+              TZ=UTC \
+              mmd -D o "c:/$dir"
+      fi
+  done
+  # Then copy all files
+  find /tmp/$espmp -type f -printf "%P\n" | sort | while read -r file; do
+      MTOOLS_SKIP_CHECK=1 \
+          SOURCE_DATE_EPOCH=$FROZEN_TIMESTAMP \
+          TZ=UTC \
+          mcopy -o -p -m -Q "/tmp/$espmp/$file" "c:/$file"
+  done
+  ######################### POPULATE BOOTFS ##################################
 
   sync
   echo -n 0 > /output/result
