feat(cg-sccache-config): Add rust support
Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

diff --git a/enterprise-packages/cg-sccache-config.yaml b/enterprise-packages/cg-sccache-config.yaml
--- a/enterprise-packages/cg-sccache-config.yaml
+++ b/enterprise-packages/cg-sccache-config.yaml
@@ -11,6 +11,7 @@ package:
 
 vars:
   test-cuda-version: 13.1
+  test-sccache-source-version: 0.14.0
 
 environment:
   contents:
@@ -41,9 +42,13 @@ test:
         - nvidia-cuda-nvrtc-${{vars.test-cuda-version}}-dev
         - nvidia-cuda-cudart-${{vars.test-cuda-version}}-dev
         - nvcc-${{vars.test-cuda-version}}-gcc-wrapper
+        - openssl-dev # sccache build-dep
+        - rust
     environment:
       SCCACHE_LOG: debug
       SCCACHE_ERROR_LOG: /tmp/sccache.log
+      # git fetch pipeline is failing w/o this
+      SOURCE_DATE_EPOCH: 315532800
   pipeline:
     - uses: sccache/enable
     - name: "smoke test gcc/g++ after wrapper install"
@@ -148,6 +153,32 @@ test:
         # Will only exist if sccache was spawned
         cat "$SCCACHE_ERROR_LOG"
         grep -E '^Cache hits \(C/C\+\+\)\s+1$' stats.out
+    - uses: git-checkout
+      with:
+        destination: rust-test
+        repository: https://github.com/mozilla/sccache
+        tag: v${{vars.test-sccache-source-version}}
+        expected-commit: 6ea77c318e4a50fb713a7b1e7a09a87a0b7e114c
+    - name: "validate that rust objects are getting cached"
+      working-directory: rust-test
+      runs: |
+        trap "rm -rf $PWD" EXIT
+        export RUSTC_WRAPPER=sccache
+        cargo build --release
+        cargo clean
+        cargo build --release
+        sccache --show-stats | tee stats.out
+        killall sccache
+        for i in $(seq 10); do
+          pidof sccache || break
+          sleep 1
+        done
+        # Will only exist if sccache was spawned
+        cat "$SCCACHE_ERROR_LOG"
+        grep -E '^Cache hits \(Rust\)\s+[0-9]+$' stats.out >rust-hits.out
+        hits="$(sed -r 's/Cache hits \(Rust\)\s+([0-9]+)$/\1/' < rust-hits.out)"
+        test -n "${hits}"
+        [ "${hits}" -gt 0 ]
     - name: "validate that nvcc objects are getting cached"
       runs: |
         tmpdir="$(mktemp -d)"
