Add istio-envoy 1.29 version stream

diff --git a/enterprise-packages/istio-envoy-fips-1.29.yaml b/enterprise-packages/istio-envoy-fips-1.29.yaml
--- a/enterprise-packages/istio-envoy-fips-1.29.yaml
+++ b/enterprise-packages/istio-envoy-fips-1.29.yaml
@@ -1,16 +1,18 @@
 package:
-  name: istio-envoy-1.28
-  version: "1.28.4"
+  name: istio-envoy-fips-1.29
+  version: "1.29.0"
   epoch: 0
   description: Envoy with additional Istio plugins (wasm, telemetry, etc)
   copyright:
     - license: Apache-2.0
   resources:
-    cpu: 20
-    memory: 50Gi
+    cpu: 30
+    memory: 60Gi
   dependencies:
     provides:
-      - istio-envoy=${{package.full-version}}
+      - istio-envoy-fips=${{package.full-version}}
+    runtime:
+      - boringssl-fips-static-${{vars.boringssl}}-tools
 
 environment:
   contents:
@@ -21,6 +23,7 @@ environment:
       - bash
       - bazel-7
       - binutils
+      - boringssl-fips-static-${{vars.boringssl}}
       - build-base
       - busybox
       - ca-certificates-bundle
@@ -28,80 +31,76 @@ environment:
       - cmake
       - coreutils
       - git
+      - glibc-locale-en
       - libtool
+      - libunwind-dev
       - llvm-18
       - llvm-18-dev
       - llvm-libcxx-18
       - llvm-libcxx-18-dev
       - llvm-libcxxabi-18
       - llvm-lld-18~18
-      - openjdk-21
-      - openssl-dev
+      - openjdk-25-default-jdk
       - patch
       - python3-dev
       - samurai
       - wolfi-baselayout
+  environment:
+    LANG: en_US.UTF-8
+    LANGUAGE: en_US:en
+    LC_ALL: en_US.UTF-8
+
+vars:
+  boringssl: "20240407"
 
 pipeline:
   - uses: git-checkout
     with:
       repository: https://github.com/istio/proxy
       tag: ${{package.version}}
-      expected-commit: cc703bb68e23c81898b82a0205549300295851e8
+      expected-commit: 1fdadc301aaaa0326255f82bd27387a0e101c164
 
-  - runs: |
-      export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
+  - name: Apply patches, to vendored envoy and quiche vendored in envoy
+    uses: patch
+    with:
+      patches: 0001-Add-envoy-patches.patch
+
+  - name: Build envoy
+    runs: |
+      export CARGO_BAZEL_REPIN=true
       mkdir -p .cache/bazel/_bazel_root
-
-      # -Wno-macro-redefined is passed to avoid errors where `_FORTIFY_SOURCE`
-      # is redefined from (I assume) our defaults to the value defined by the
-      # liburing is built without builtins and fails to link with -ftrivial-auto-var-init=zero
-      # Bazel build tasks
 
       # isitio-envoy won't build with FORTIFY_SOURCE set to 3 which our clang-18 version is setting
       sed -i 's/-D_FORTIFY_SOURCE=3//g' /etc/clang-18/common.cfg
 
+      # The flag boringssl=fips is to build with FIPS boringssl
+      # See https://github.com/envoyproxy/envoy/blob/v1.27.0/bazel/BUILD#L475
       bazel build \
+        --define=boringssl=fips \
+        --override_repository=boringssl_fips=/usr/lib/boringssl-fips-static \
+        --discard_analysis_cache \
+        --nokeep_state_after_build \
+        --notrack_incremental_state \
         --verbose_failures \
-        -c opt \
         --action_env=LIBURING_CFLAGS="-ftrivial-auto-var-init=uninitialized" \
-        envoy
+        -c opt envoy
 
+      # Bazel sometimes fails to build with an exit code 0.
+      if [ ! -f bazel-bin/envoy ]; then
+        echo "Bazel build did not complete"
+        exit 1
+      fi
       mkdir -p ${{targets.destdir}}/usr/bin/
-      mv bazel-bin/envoy ${{targets.destdir}}/usr/bin/envoy
-
-      # We no longer need this cache dir, which has some writable files.
-      rm -rf .cache/bazel
+      cp bazel-bin/envoy ${{targets.destdir}}/usr/bin/envoy
 
   - uses: strip
 
-subpackages:
-  - name: ${{package.name}}-compat
-    pipeline:
-      - runs: |
-          # link /usr/bin/envoy /usr/local/bin/envoy because Istio proxy-agent expects Envoy here
-          # See https://github.com/istio/istio/blob/1.18.0/pkg/config/constants/constants.go#L59-L60
-          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
-          ln -sf /usr/bin/envoy ${{targets.subpkgdir}}/usr/local/bin/envoy
-    dependencies:
-      provides:
-        - istio-envoy-compat=${{package.full-version}}
-    test:
-      pipeline:
-        - uses: test/virtualpackage
-          with:
-            virtual-pkg-name: istio-envoy-compat
-            real-pkg-name: ${{subpkg.name}}
-
 update:
   enabled: true
-  ignore-regex-patterns:
-    - "-rc"
-    - "-beta"
   github:
     identifier: istio/proxy
-    tag-filter-prefix: 1.28.
     use-tag: true
+    tag-filter: 1.29.
 
 test:
   environment:
@@ -112,11 +111,20 @@ test:
         - netcat-openbsd
         - procps
         - jq
+        - openssl
   pipeline:
     - name: "Verify binary installation"
       runs: |
         envoy --version
         envoy --help
+    - runs: |
+        envoy_version=$(envoy --version | sed -n 's|.*/BoringSSL-FIPS-\(.*\)|\1|p')
+        [ "$envoy_version" = "${{vars.boringssl}}" ]
+        /usr/bin/bssl-test_fips
+        /usr/bin/bssl-test_fips | grep "^Module: 'BoringCrypto', version: ${{vars.boringssl}} hash:$"
+    - uses: test/cmvp-fips-certification-check
+      with:
+        certificate-number: 5104
     - name: "Test Envoy admin interface startup"
       uses: test/daemon-check-output
       with:
@@ -169,11 +177,37 @@ test:
         post: |
           #!/bin/sh -e
           first_pid=$(pgrep -f "restart-epoch 0")
-          envoy --config-path /tmp/minimal.yaml --restart-epoch 1 > /dev/null 2>&1 &
+          envoy --config-path /tmp/minimal.yaml --restart-epoch 1 &
           sleep 2
 
           # Verify both processes exist
           if ! ps -p $first_pid > /dev/null; then
             echo "Original Envoy process not found"
             exit 1
+          fi
+    - name: "Test TLS ciphers"
+      uses: test/daemon-check-output
+      with:
+        setup: |
+          #!/bin/sh -e
+          # Generate self-signed certificate for TLS listener
+          openssl req -x509 -newkey rsa:2048 -nodes \
+            -keyout serverkey.pem \
+            -out servercert.pem \
+            -days 1 \
+            -subj "/CN=localhost"
+        start: envoy --config-path envoy-demo-tls.yaml
+        timeout: 30
+        expected_output: |
+          starting main dispatch loop
+          all dependencies initialized
+        post: |
+          #!/bin/sh -e
+          # Test that curl works
+          curl --cacert servercert.pem  -o /dev/null https://localhost:10000
+          # Force CHACHA20 connection, and ensure it doesn't work
+          result=$(echo Q | OPENSSL_CONF=/dev/null openssl s_client -tls1_3 -CAfile servercert.pem -ciphersuites TLS_CHACHA20_POLY1305_SHA256  -connect localhost:10000 2>&1| tail -n1)
+          if [ "$result" = "DONE" ]; then
+             echo Error: non-approved TLS_CHACHA20_POLY1305_SHA256 connection successful
+             exit 1
           fi
