add coverage for verifying non FIPS modules are not being shipped
Signed-off-by: Aditya Tirmanwar <aditya.tirmanwar@chainguard.dev>

diff --git a/enterprise-packages/pgadmin4-fips.yaml b/enterprise-packages/pgadmin4-fips.yaml
--- a/enterprise-packages/pgadmin4-fips.yaml
+++ b/enterprise-packages/pgadmin4-fips.yaml
@@ -21,6 +21,7 @@ package:
       - liblz4-1
       - libpq
       - libzstd1
+      - openssl-config-fipshardened
       - posix-libc-utils
       - postfix
       - py${{vars.python-version}}-jinja2
@@ -262,6 +263,18 @@ test:
           curl -X POST http://127.0.0.1:5050/login \
               -d "email=$PGADMIN_SETUP_EMAIL&password=$PGADMIN_SETUP_PASSWORD" \
               -H "Content-Type: application/x-www-form-urlencoded" || { echo "Failed to log in to pgAdmin4"; exit 1; }
+    - name: Verify non-FIPS algorithms are not present
+      runs: |
+        cd /venv
+        if ./bin/python -m pip list | grep -iE '(PyNaCl|python-rsa|bcrypt|SecretStorage)'; then
+          echo "ERROR: Found non-FIPS crypto packages installed"
+          exit 1
+        fi
+        cd /lib/python${{vars.python-version}}/site-packages
+        if ls | grep -iE '(PyNaCl|rsa|bcrypt|[Ss]ecret[Ss]torage).*dist-info'; then
+          echo "ERROR: Found non-FIPS crypto package metadata"
+          exit 1
+        fi
 
 update:
   version-separator: _
