convert it to automated update
Using ignore regex pattern to ignore odd version
- add pipeline validation step to ensure we only update to major even versions

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

diff --git a/enterprise-packages/postgrest.yaml b/enterprise-packages/postgrest.yaml
--- a/enterprise-packages/postgrest.yaml
+++ b/enterprise-packages/postgrest.yaml
@@ -1,9 +1,5 @@
 package:
   name: postgrest
-  # https://docs.postgrest.org/en/latest/ says "Starting from v14.0, only
-  # even-numbered MAJOR versions will be released, reserving odd-numbered
-  # MAJOR versions for development".  Be careful to only update this to
-  # even-numbered major versions.
   version: "14.4"
   epoch: 0
   description: "Serve a RESTful API from any PostgreSQL database"
@@ -20,7 +16,28 @@ environment:
       - postgresql-dev
       - zlib-dev
 
+var-transforms:
+  - from: ${{package.version}}
+    match: '^(\d+)\..*'
+    replace: "$1"
+    to: major-version
+
 pipeline:
+  - name: Validation for EVEN major version
+    runs: |
+      # https://docs.postgrest.org/en/v14/ says "Starting from v14.0, only
+      # even-numbered MAJOR versions will be released, reserving odd-numbered
+      # MAJOR versions for development".  Be careful to only update this to
+      # even-numbered major versions.
+      MAJOR=${{vars.major-version}}
+      if [ $((MAJOR % 2)) -eq 0 ]; then
+        echo "Major version is even, proceeding with build..."
+      else
+        echo "ERROR: Major version is odd, Stable releases are only for even-numbered major versions."
+        echo "Odd versions are reserved for development and testing. see https://docs.postgrest.org/en/v14/"
+        exit 1
+      fi
+
   - uses: git-checkout
     with:
       repository: "https://github.com/PostgREST/postgrest"
@@ -53,8 +70,9 @@ pipeline:
 
 update:
   enabled: true
-  manual: true
   exclude-reason: "Requires manual updates using haskell/record-dependencies"
+  ignore-regex-patterns:
+    - '^v\d*[13579]\.' # Ignoring odd versions
   github:
     identifier: PostgREST/postgrest
     strip-prefix: "v"
