fix: add more pam and faillock stig fixes
This changes will fix all of the pam stig failures, and faillock checks.

Fixes VMS-45
Fixes VMS-46

Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

diff --git a/harden-vm/apply-hardening b/harden-vm/apply-hardening
--- a/harden-vm/apply-hardening
+++ b/harden-vm/apply-hardening
@@ -489,17 +489,34 @@ harden_stig_pam()
 			bail "Failed to configure pwquality with '${option} ${value}'"
 		fi
 	done
-	sed -i "s|^#? *enforce_for_root|enforce_for_root|g" "${sysroot}/etc/security/pwquality.conf"
+
+	sed -i "s|^# enforce_for_root|enforce_for_root|g" "${sysroot}/etc/security/pwquality.conf"
+
+	sed -i '/^auth.*sufficient.*pam_rootok.so/a auth required pam_wheel.so use_uid' /etc/pam.d/su
+
+	sed -i '/^auth.*sufficient.*pam_rootok.so/a auth required pam_wheel.so use_uid' /etc/pam.d/su
 	for i in base-password base-auth base-account; do
 		sed -i '/^password required/i password requisite pam_pwquality.so' "${sysroot}/etc/pam.d/$i"
 		sed -i 's|nullok||g' "${sysroot}/etc/pam.d/$i"
-		echo 'auth        required      pam_faillock.so preauth silent' >> "${sysroot}/etc/pam.d/$i"
-		echo 'auth        required      pam_faillock.so authfail' >> "${sysroot}/etc/pam.d/$i"
-		echo 'account     required      pam_faillock.so' >> "${sysroot}/etc/pam.d/$i"
+		sed -i 's/^\(password.*pam_unix\.so.*\)$/\1 rounds=100000/' "${sysroot}/etc/pam.d/$i"
+		sed -i 's/^password.*required.*pam_unix\.so/password sufficient pam_unix.so/' "${sysroot}/etc/pam.d/$i"
+		if ! grep -q pam_faillock.so "${sysroot}/etc/pam.d/$i"; then
+			echo 'auth        required      pam_faillock.so preauth silent' >> "${sysroot}/etc/pam.d/$i"
+			echo 'auth        sufficient    pam_unix.so try_first_pass' >> "${sysroot}/etc/pam.d/$i"
+			echo 'auth        required      pam_faillock.so authfail' >> "${sysroot}/etc/pam.d/$i"
+			echo 'account     required      pam_faillock.so' >> "${sysroot}/etc/pam.d/$i"
+			echo 'account     required      pam_unix.so' >> "${sysroot}/etc/pam.d/$i"
+		fi
 	done
 	# TODO: fix the benchmark to search our own paths
 	ln -sf /etc/pam.d/base-password "${sysroot}/etc/pam.d/password-auth"
 	ln -sf /etc/pam.d/base-password "${sysroot}/etc/pam.d/system-auth"
+
+	cat > /etc/pam.d/postlogin << 'EOF'
+#%PAM-1.0
+# Display last login/logon information
+session     optional      pam_lastlog.so showfailed
+EOF
 }
 
 harden_stig_systemd_ctrlaltdel()
@@ -521,6 +538,32 @@ harden_stig_fixnews()
 	chown 0:0 "${sysroot}/usr/lib/news"
 }
 
+harden_stig_faillock()
+{
+	sed -i 's|^# dir = .*|dir = /var/log/faillock|' /etc/security/faillock.conf
+	sed -i 's/^# audit/audit/' /etc/security/faillock.conf
+	sed -i 's/^# deny = .*/deny = 3/' /etc/security/faillock.conf
+	sed -i 's/^# even_deny_root/even_deny_root/' /etc/security/faillock.conf
+	sed -i 's/^# fail_interval.*/fail_interval = 900/' /etc/security/faillock.conf
+	sed -i 's/^# unlock_time.*/unlock_time = 0/' /etc/security/faillock.conf
+}
+
+harden_stig_logindefs()
+{
+	echo "PASS_MAX_DAYS 60" >> /etc/login.defs
+	echo "PASS_MIN_DAYS 1" >> /etc/login.defs
+	echo "ENCRYPT_METHOD SHA512" >> /etc/login.defs
+	echo "FAIL_DELAY 4" >> /etc/login.defs
+	echo "CREATE_HOME yes" >> /etc/login.defs
+	echo "UMASK 077" >> /etc/login.defs
+}
+
+harden_stig_limits()
+{
+	echo "* hard maxlogins 10" >> /etc/security/limits.conf
+	echo "* hard core 0" >> /etc/security/limits.conf
+}
+
 harden_stig()
 {
 	harden_stig_sshd
@@ -533,6 +576,9 @@ harden_stig()
 	harden_stig_systemd_ctrlaltdel
 	harden_stig_systemd_coredump
 	harden_stig_fixnews
+	harden_stig_faillock
+	harden_stig_logindefs
+	harden_stig_limits
 }
 
 main()
