backfill: add more logging, and silence some output (#4620)
Signed-off-by: Jason Hall <jason@chainguard.dev>

diff --git a/.github/workflows/backfill.yaml b/.github/workflows/backfill.yaml
--- a/.github/workflows/backfill.yaml
+++ b/.github/workflows/backfill.yaml
@@ -43,24 +43,37 @@ jobs:
           for arch in "aarch64" "x86_64"; do
             echo "Processing ${arch}"
             while IFS= read -r pkg; do
+              # Ignore empty lines and comments
+              if [[ -z "${pkg}" ]]; then
+                continue
+              fi
+              if [[ "${pkg}" == \#* ]]; then
+                continue
+              fi
+
               tok=$(chainctl auth token --audience apk.cgr.dev)
               tmp=$(mktemp -d)
 
               # Check if package already exists in apk.cgr.dev
+              echo "Checking if package ${pkg} exists in apk.cgr.dev"
               curl -s --head \
                 --user "user:${tok}" \
-                "https://apk.cgr.dev/chainguard-private/${arch}/${pkg}" && continue
+                "https://apk.cgr.dev/chainguard-private/${arch}/${pkg}" > /dev/null 2>&1 && continue
+              echo "Package ${pkg} not found in apk.cgr.dev"
 
               # Get package from GCS, continue if it doesn't exist (e.g., not in enterprise)
-              gsutil cp gs://chainguard-enterprise-registry-destination/os/${arch}/${pkg} ${tmp}/ || continue
+              echo "Downloading ${pkg} from GCS"
+              gsutil cp gs://chainguard-enterprise-registry-destination/os/${arch}/${pkg} ${tmp}/ > /dev/null 2>&1 || continue
+              echo "Downloaded ${pkg} from GCS"
 
               echo "Uploading ${pkg} to apk.cgr.dev"
               curl --fail -X POST \
                 --user "user:${tok}" \
                 --data-binary "@${tmp}/${pkg}" \
                 "https://apk.cgr.dev/chainguard-private/${arch}/${pkg}"
+              echo "Uploaded ${pkg} to apk.cgr.dev"
               rm ${tmp}/${pkg}
-            done < <(grep -v -e '^$' -v '\#' backfill-packages.txt | cut -d':' -f2) # Ignore empty lines and comments
+            done < backfill-packages.txt
           done
 
       - uses: rtCamp/action-slack-notify@4e5fb42d249be6a45a298f3c9543b111b02f7907 # v2.3.0
