VMWare image build plumbing (#597)
First config is basic agents-docker-dev

diff --git a/.github/workflows/build-publish-vmware.yaml b/.github/workflows/build-publish-vmware.yaml
--- a/.github/workflows/build-publish-vmware.yaml
+++ b/.github/workflows/build-publish-vmware.yaml
@@ -1,7 +1,7 @@
 # Copyright 2025 Chainguard, Inc.
 # SPDX-License-Identifier: Apache-2.0
 
-name: "Build and push QEMU VMs images"
+name: "Build and push VMWare VMs images"
 
 on:
   schedule:
@@ -16,11 +16,11 @@ on:
       notify-slack-success:
         type: boolean
         required: false
-        default: true
+        default: false
         description: Send notifications on success as well as failure.
       with-compliance-scan:
         type: boolean
-        required: true
+        required: false
         description: Run CIS Benchmarks compliance scanning and generate a report
   # Only build when main is updated, we won't publish the artifacts out
   push:
@@ -31,7 +31,7 @@ permissions: {}
 
 # Allow only one workflow run at a time
 concurrency:
-  group: 'release-qemu'
+  group: 'release-vmware'
   cancel-in-progress: false
 
 jobs:
@@ -46,7 +46,7 @@ jobs:
         run: |
           echo BUILD_TIMESTAMP=$(date --utc "+%Y%m%d-%H%M") >> "$GITHUB_OUTPUT"
 
-  qemu-build-push:
+  vmware-build-push:
     runs-on: ubuntu-8-core
     needs:
       - init
@@ -65,7 +65,7 @@ jobs:
     env:
       BUILD_TIMESTAMP: ${{ needs.init.outputs.BUILD_TIMESTAMP }}
       VM_ARCH: ${{ matrix.arch }}
-      VM_CLOUD: "qemu"
+      VM_CLOUD: "vmware"
       WITH_COMPLIANCE_SCAN: ${{ github.event.inputs.with-compliance-scan || 'false' }}
 
     steps:
@@ -85,13 +85,13 @@ jobs:
         uses: './.github/actions/build-disks'
         with:
           cg_identity: "ce2d1984a010471142503340d670612d63ffb9f6/381a2db906b88c20"
-          vm_group: "qemu"
+          vm_group: "vmware"
           arch: '${{ matrix.arch }}'
 
       - name: Scan disks
         uses: './.github/actions/scan-disks'
         with:
-          cloud_provider: "qemu"
+          cloud_provider: "vmware"
           arch: '${{ matrix.arch }}'
 
       - name: add HOME/bin to PATH
@@ -109,15 +109,15 @@ jobs:
         run: |
           make "builder/ovmf-${{ matrix.arch }}.fd"
 
-      - name: "Create qcow2 images"
+      - name: "Create vmdk images"
         run: |
-          names=$(make list-qemu)
-          [ -n "$names" ] || { echo "make list-qemu produced empty output"; exit 1; }
+          names=$(make list-vmware)
+          [ -n "$names" ] || { echo "make list-vmware produced empty output"; exit 1; }
 
-          echo "Creating qcow2 images for: $names"
+          echo "Creating vmdk images for: $names"
           for name in $names; do
-            echo "Creating qcow2 for $name"
-            make "qcow-$name"
+            echo "Creating vmdk for $name"
+            make "vmdk-$name"
           done
 
       - name: "Setup GCP Creds for GCS Publishing"
@@ -133,35 +133,45 @@ jobs:
         with:
           project_id: wolfi-vm
 
-      - name: "Test QEMU images"
-        uses: './.github/actions/vms-test'
-        with:
-          cloud_provider: "qemu"
-          vm_group: "qemu"
-          arch: '${{ matrix.arch }}'
-          with-compliance-scan: '${{ env.WITH_COMPLIANCE_SCAN }}'
-
       - name: "Configure gcloud"
         if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
         run: |
           gcloud config set storage/parallel_composite_upload_enabled True
 
-      - name: "Publish QEMU Images to GCS"
+      - name: "Publish VMware Images to GCS staging"
         if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
         run: |
           arch="${{ env.VM_ARCH }}"
-          names=$(make list-qemu)
-          [ -n "$names" ] || { echo "make list-qemu produced empty output"; exit 1; }
+          names=$(make list-vmware)
+          [ -n "$names" ] || { echo "make list-vmware produced empty output"; exit 1; }
+          make -j$(nproc) --output-sync=recurse publish-vmware PREFIX=chainguard PUBLISH_TARGET=staging ARCH=$arch
 
-          make -j$(nproc) --output-sync=recurse publish-qemu PREFIX=chainguard PUBLISH_TARGET=eap ARCH=$arch
+      # TODO We don't have a test setup for vmware yet. QEMU won't work because we're not including the qemu guest helper.
+      # Don't publish images anywhere else yet.
 
-      - uses: './.github/actions/notify-slack'
-        if: ${{ (inputs.notify-slack-success || failure()) && (github.event_name == 'schedule' || inputs.notify-slack) }}
-        with:
-          webhook: ${{ secrets.SLACK_WEBHOOK_INPUT }}
-          title: ${{ github.workflow }} (${{ matrix.arch }}) ${{ job.status }}
-          message-color: ${{ job.status == 'success' && '#3fb950' || '#f85149'}}
-          text: |
-            For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-            Or run ./hack/fetch-test-result -c ${{ env.VM_CLOUD }} -r ${{ github.run_id }} -a ${{matrix.arch}}
-          unfurl-links: true
+      #- name: "Test VMWare images"
+      #  uses: './.github/actions/vms-test'
+      #  with:
+      #    cloud_provider: "vmware"
+      #    vm_group: "vmware"
+      #    arch: '${{ matrix.arch }}'
+      #    with-compliance-scan: '${{ env.WITH_COMPLIANCE_SCAN }}'
+
+      #- name: "Publish VMware Images to GCS"
+      #  if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
+      #  run: |
+      #    arch="${{ env.VM_ARCH }}"
+      #    names=$(make list-vmware)
+      #    [ -n "$names" ] || { echo "make list-vmware produced empty output"; exit 1; }
+      #    make -j$(nproc) --output-sync=recurse publish-vmware PREFIX=chainguard PUBLISH_TARGET=eap ARCH=$arch
+
+      #- uses: './.github/actions/notify-slack'
+      #  if: ${{ (inputs.notify-slack-success || failure()) && (github.event_name == 'schedule' || inputs.notify-slack) }}
+      #  with:
+      #    webhook: ${{ secrets.SLACK_WEBHOOK_INPUT }}
+      #    title: ${{ github.workflow }} (${{ matrix.arch }}) ${{ job.status }}
+      #    message-color: ${{ job.status == 'success' && '#3fb950' || '#f85149'}}
+      #    text: |
+      #      For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+      #      Or run ./hack/fetch-test-result -c ${{ env.VM_CLOUD }} -r ${{ github.run_id }}
+      #    unfurl-links: true
