build-publish-aws: publish to AWS Marketplace once a week only (#501)
Publish Amazon EC2 AMIs to the AWS Marketplace once a week only. All
images are still built, uploaded, and tested anytime the workflow runs,
but only actually published as new product version on the AWS
Marketplace during the nightly run on Monday. Manual workflow
invocations can override that behavior by forcing the publication step,
e.g. for bug fixes or security patches that need to go out immediately.

Slowing the release cadence from once a day to once a week helps us stay
clear of hard limits on the AWS Marketplace. A product may only have 100
published versions to it. After reaching that limit, no new versions can
be published for that product. While we can restrict old versions from
use via API ourselves, this is not sufficient and we need manual support
intervention from AWS to archive them and actually get back below 100
versions per product.

Signed-off-by: Markus Boehme <markus.boehme@chainguard.dev>

diff --git a/.github/workflows/build-publish-aws.yaml b/.github/workflows/build-publish-aws.yaml
--- a/.github/workflows/build-publish-aws.yaml
+++ b/.github/workflows/build-publish-aws.yaml
@@ -7,6 +7,11 @@ on:
   schedule:
     - cron: "0 0 * * *"
   workflow_dispatch:
+    inputs:
+      publish-to-marketplace:
+        type: boolean
+        required: true
+        description: Publish uploaded and tested AMIs to the AWS Marketplace
 
 permissions: {}
 
@@ -58,6 +63,7 @@ jobs:
       BUILD_TIMESTAMP: ${{ needs.init.outputs.BUILD_TIMESTAMP }}
       VM_ARCH: ${{ matrix.arch }}
       VM_GROUP: ${{ matrix.group }}
+      PUBLISH_TO_MP: ${{ github.event.inputs.publish-to-marketplace || 'on-schedule' }}
 
     steps:
       - uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
@@ -188,4 +194,31 @@ jobs:
 
       - name: "Publish AWS Images to marketplace"
         run: |
+          if [ "$PUBLISH_TO_MP" = 'on-schedule' ]; then
+            if ! weekday=$(date +%A); then
+              echo 'Trying to publish once a week only, but failed to determine the weekday. Bailing!'
+              exit 1
+            fi
+            echo "The automated job is publishing to the AWS Marketplace once a week on Mondays only. Today is $weekday."
+            if [ "$weekday" = 'Monday' ]; then
+              echo 'Will publish.'
+              PUBLISH_TO_MP=true
+            else
+              echo 'Will not publish.'
+              PUBLISH_TO_MP=false
+            fi
+          fi
+
+          case "$PUBLISH_TO_MP" in
+            true)
+              :
+              ;;
+            false)
+              exit 0
+              ;;
+            *)
+              echo "Unexpected value for PUBLISH_TO_MP: '$PUBLISH_TO_MP'. Allowed values: 'true', 'false', 'on-schedule.'"
+              exit 1
+          esac
+
           make -j4 --output-sync=recurse "aws-publish-${VM_GROUP}" BUILD_TIMESTAMP=${BUILD_TIMESTAMP} ARCH=${{ env.VM_ARCH }}
