Make withdraw safe again (#1152)
This uses object generations to make the withdrawal workflow fail if
something else concurrently modifies the APKINDEX (to avoid data loss).

Signed-off-by: Jon Johnson <jon.johnson@chainguard.dev>

diff --git a/.github/workflows/withdraw-packages.yaml b/.github/workflows/withdraw-packages.yaml
--- a/.github/workflows/withdraw-packages.yaml
+++ b/.github/workflows/withdraw-packages.yaml
@@ -55,16 +55,6 @@ jobs:
           sudo mkdir -p /etc/apk/keys
           sudo cp ./chainguard-extras.rsa.pub /etc/apk/keys/chainguard-extras.rsa.pub
 
-      - name: Withdraw from index
-        run: |
-          set -euo pipefail
-          for arch in x86_64 aarch64; do
-            mkdir -p $arch
-            curl https://packages.cgr.dev/extras/$arch/APKINDEX.tar.gz | wolfictl withdraw $(grep -v '\#' withdrawn-packages.txt) --signing-key="${{ env.SIGNING_KEY }}" > $arch/APKINDEX.tar.gz
-          done
-        env:
-          SIGNING_KEY: "${{ github.workspace }}/chainguard-extras.rsa"
-
       # We use a different GSA for our interaction with GCS.
       - uses: google-github-actions/auth@62cf5bd3e4211a0a0b51f2c6d6a37129d828611d # v2.1.5
         with:
@@ -75,6 +65,25 @@ jobs:
         with:
           project_id: "prod-images-c6e5"
 
+      - name: Withdraw from index
+        run: |
+          set -euo pipefail
+          for arch in x86_64 aarch64; do
+            mkdir -p $arch
+            curl -v https://packages.cgr.dev/extras/$arch/APKINDEX.tar.gz 2>verbose | wolfictl withdraw $(grep -v '\#' withdrawn-packages.txt) --signing-key="${{ env.SIGNING_KEY }}" > $arch/APKINDEX.tar.gz
+
+            # Parse the object generation from the -v output.
+            GEN=$(grep "x-goog-generation" verbose | cut -d' ' -f3)
+            echo "APKINDEX.tar.gz object generation for ${arch} was ${GEN}"
+
+            # This will fail if the APKINDEX is modified between when we download it and when we upload the modified version.
+            # That's totally fine, just re-run the withdrawl workflow.
+            # This is a bit of a hack until we drop this APKINDEX entirely.
+            gcloud storage cp --if-generation-match="${GEN}" --cache-control="no-store" $arch/APKINDEX.tar.gz gs://chainguard-extras-apk-registry/extras/$arch/APKINDEX.tar.gz
+          done
+        env:
+          SIGNING_KEY: "${{ github.workspace }}/chainguard-extras.rsa"
+
       - name: Delete withdrawn packages
         run: |
           set -euo pipefail
@@ -83,14 +92,6 @@ jobs:
               echo "=> $pkg"
               gsutil -m rm -f gs://chainguard-extras-apk-registry/extras/$arch/$pkg || true
             done
-          done
-
-      - name: Upload modified index
-        run: |
-          set -euxo pipefail
-          for arch in x86_64 aarch64; do
-            gsutil -h "Cache-Control:no-store" \
-                $arch/APKINDEX.tar.gz gs://chainguard-extras-apk-registry/extras/$arch/APKINDEX.tar.gz || true
           done
 
       - name: Upload full withdrawn packages list
